import type { Food } from '@/core/types'

/** Burger King UK menu, per item as BK publishes it (per 100 g with BK's serving weight where given).
 *  GENERATED by scripts/import/burgerking_web.py from docs/data/snapshots/burgerking-2026-09-25.json: don't edit by hand. */
export const BURGERKING: Food[] = [
  {
    "n": "Burger King Whopper",
    "k": 207.32,
    "p": 10.1,
    "c": 18.47,
    "f": 10.45,
    "g": 287,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 287,
      "k": 595,
      "p": 29,
      "c": 53,
      "f": 30
    }
  },
  {
    "n": "Burger King Chicken Royale",
    "k": 261.75,
    "p": 10.6,
    "c": 23.96,
    "f": 13.36,
    "g": 217,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 217,
      "k": 568,
      "p": 23,
      "c": 52,
      "f": 29
    }
  },
  {
    "n": "Burger King Bacon Butty",
    "k": 239.49,
    "p": 12.78,
    "c": 31.91,
    "f": 6.38,
    "g": 117,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 117,
      "k": 280.2,
      "p": 14.95,
      "c": 37.34,
      "f": 7.47
    }
  },
  {
    "n": "Burger King Sausage Butty",
    "k": 238.11,
    "p": 11.82,
    "c": 27.26,
    "f": 8.76,
    "g": 138.1,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 138.1,
      "k": 328.83,
      "p": 16.33,
      "c": 37.64,
      "f": 12.1
    }
  },
  {
    "n": "Burger King Breakfast King",
    "k": 250.25,
    "p": 17.18,
    "c": 18.5,
    "f": 11.71,
    "g": 202,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 202,
      "k": 505.51,
      "p": 34.699,
      "c": 37.38,
      "f": 23.649
    }
  },
  {
    "n": "Burger King Bacon Caesar Angus",
    "k": 869,
    "p": 40,
    "c": 41,
    "f": 59,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 869,
      "p": 40,
      "c": 41,
      "f": 59
    }
  },
  {
    "n": "Burger King Bacon Caesar Crispy Chicken",
    "k": 762,
    "p": 31,
    "c": 57,
    "f": 45,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 762,
      "p": 31,
      "c": 57,
      "f": 45
    }
  },
  {
    "n": "Burger King Texan BBQ King",
    "k": 996,
    "p": 53,
    "c": 63,
    "f": 59,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 996,
      "p": 53,
      "c": 63,
      "f": 59
    }
  },
  {
    "n": "Burger King Texan BBQ Royale",
    "k": 691,
    "p": 28,
    "c": 66,
    "f": 34,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 691,
      "p": 28,
      "c": 66,
      "f": 34
    }
  },
  {
    "n": "Burger King Texan BBQ Double Royale",
    "k": 922,
    "p": 43,
    "c": 79,
    "f": 47,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 922,
      "p": 43,
      "c": 79,
      "f": 47
    }
  },
  {
    "n": "Burger King BBQ Steakhouse Angus",
    "k": 284.89,
    "p": 14.75,
    "c": 16.19,
    "f": 17.63,
    "g": 278,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 278,
      "k": 792,
      "p": 41,
      "c": 45,
      "f": 49
    }
  },
  {
    "n": "Burger King BBQ Steakhouse Crispy Chicken",
    "k": 265.42,
    "p": 13.33,
    "c": 26.25,
    "f": 11.67,
    "g": 240,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 240,
      "k": 637,
      "p": 32,
      "c": 63,
      "f": 28
    }
  },
  {
    "n": "Burger King Whopper with Bacon and Cheese",
    "k": 223.91,
    "p": 12.11,
    "c": 15.53,
    "f": 15.22,
    "g": 322,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 322,
      "k": 721,
      "p": 39,
      "c": 50,
      "f": 49
    }
  },
  {
    "n": "Burger King Double Whopper",
    "k": 225.81,
    "p": 13.98,
    "c": 12.9,
    "f": 12.9,
    "g": 372,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 372,
      "k": 840,
      "p": 52,
      "c": 48,
      "f": 48
    }
  },
  {
    "n": "Burger King Double Whopper with Bacon and Cheese",
    "k": 235.87,
    "p": 14.74,
    "c": 12.29,
    "f": 14.0,
    "g": 407,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 407,
      "k": 960,
      "p": 60,
      "c": 50,
      "f": 57
    }
  },
  {
    "n": "Burger King Bacon Double Cheese XL",
    "k": 287.97,
    "p": 19.94,
    "c": 14.24,
    "f": 16.46,
    "g": 316,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 316,
      "k": 910,
      "p": 63,
      "c": 45,
      "f": 52
    }
  },
  {
    "n": "Burger King Bacon Double Cheeseburger",
    "k": 295.3,
    "p": 20.13,
    "c": 17.45,
    "f": 16.11,
    "g": 149,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 149,
      "k": 440,
      "p": 30,
      "c": 26,
      "f": 24
    }
  },
  {
    "n": "Burger King Classic Double Beef Melt",
    "k": 260.74,
    "p": 17.04,
    "c": 18.52,
    "f": 12.59,
    "g": 135,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 135,
      "k": 352,
      "p": 23,
      "c": 25,
      "f": 17
    }
  },
  {
    "n": "Burger King Chicken Royale Bacon & Cheese",
    "k": 274.9,
    "p": 12.35,
    "c": 21.51,
    "f": 15.14,
    "g": 251,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 251,
      "k": 690,
      "p": 31,
      "c": 54,
      "f": 38
    }
  },
  {
    "n": "Burger King Double Chicken Royale",
    "k": 253.85,
    "p": 12.18,
    "c": 20.83,
    "f": 13.14,
    "g": 312,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 312,
      "k": 792,
      "p": 38,
      "c": 65,
      "f": 41
    }
  },
  {
    "n": "Burger King Double Chicken Royale Bacon & Cheese",
    "k": 244.51,
    "p": 12.17,
    "c": 18.01,
    "f": 13.58,
    "g": 346,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 346,
      "k": 846,
      "p": 42.1,
      "c": 62.3,
      "f": 47
    }
  },
  {
    "n": "Burger King Classic Chicken Melt",
    "k": 261.78,
    "p": 12.1,
    "c": 25.48,
    "f": 12.1,
    "g": 157,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 157,
      "k": 411,
      "p": 19,
      "c": 40,
      "f": 19
    }
  },
  {
    "n": "Burger King Vegan Royale",
    "k": 256.68,
    "p": 7.83,
    "c": 24.42,
    "f": 13.36,
    "g": 217,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 217,
      "k": 557,
      "p": 17,
      "c": 53,
      "f": 29
    }
  },
  {
    "n": "Burger King Plant-based Whopper",
    "k": 189.93,
    "p": 9.71,
    "c": 16.91,
    "f": 8.63,
    "g": 278,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 278,
      "k": 528,
      "p": 27,
      "c": 47,
      "f": 24
    }
  },
  {
    "n": "Burger King Sticky Toffee Loaded Churros",
    "k": 298,
    "p": 4.5,
    "c": 41,
    "f": 12,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 298,
      "p": 4.5,
      "c": 41,
      "f": 12
    }
  },
  {
    "n": "Burger King Flame-Grilled Mayo",
    "k": 176,
    "p": 0.5,
    "c": 2.9,
    "f": 18,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 176,
      "p": 0.5,
      "c": 2.9,
      "f": 18
    }
  },
  {
    "n": "Burger King BBQ Mayo",
    "k": 185,
    "p": 0.5,
    "c": 6.1,
    "f": 18,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 185,
      "p": 0.5,
      "c": 6.1,
      "f": 18
    }
  },
  {
    "n": "Burger King Burger Buddies (3 pieces)",
    "k": 220.53,
    "p": 10.37,
    "c": 20.24,
    "f": 10.67,
    "g": 375,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 375,
      "k": 827,
      "p": 38.9,
      "c": 75.9,
      "f": 40
    }
  },
  {
    "n": "Burger King Double Cheeseburger",
    "k": 262.89,
    "p": 16.98,
    "c": 17.61,
    "f": 13.84,
    "g": 159,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 159,
      "k": 418,
      "p": 27,
      "c": 28,
      "f": 22
    }
  },
  {
    "n": "Burger King Cheeseburger",
    "k": 247.83,
    "p": 13.91,
    "c": 23.48,
    "f": 10.43,
    "g": 115,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 115,
      "k": 285,
      "p": 16,
      "c": 27,
      "f": 12
    }
  },
  {
    "n": "Burger King Hamburger",
    "k": 239.81,
    "p": 13.59,
    "c": 25.24,
    "f": 9.13,
    "g": 103,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 103,
      "k": 247,
      "p": 14,
      "c": 26,
      "f": 9.4
    }
  },
  {
    "n": "Burger King Truffle Loaded King Fries",
    "k": 318.66,
    "p": 4.26,
    "c": 29.19,
    "f": 20.1,
    "g": 209,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 209,
      "k": 666,
      "p": 8.9,
      "c": 61,
      "f": 42
    }
  },
  {
    "n": "Burger King Pringles Sour Cream & Onion Chicken Fries (6 pieces)",
    "k": 236.27,
    "p": 14.12,
    "c": 18.63,
    "f": 11.76,
    "g": 102,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 102,
      "k": 241,
      "p": 14.4,
      "c": 19,
      "f": 12
    }
  },
  {
    "n": "Burger King Chicken Nuggets (6 pieces)",
    "k": 255.0,
    "p": 14.0,
    "c": 18.0,
    "f": 14.0,
    "g": 100,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 100,
      "k": 255,
      "p": 14,
      "c": 18,
      "f": 14
    }
  },
  {
    "n": "Burger King Halloumi Fries (5 pieces)",
    "k": 369.23,
    "p": 24.62,
    "c": 2.0,
    "f": 29.23,
    "g": 65,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 65,
      "k": 240,
      "p": 16,
      "c": 1.3,
      "f": 19
    }
  },
  {
    "n": "Burger King Chilli Cheese Bites (6 pieces)",
    "k": 286.49,
    "p": 9.01,
    "c": 27.93,
    "f": 15.32,
    "g": 111,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 111,
      "k": 318,
      "p": 10,
      "c": 31,
      "f": 17
    }
  },
  {
    "n": "Burger King Fries (regular)",
    "k": 237.07,
    "p": 3.1,
    "c": 31.03,
    "f": 10.34,
    "g": 116,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 116,
      "k": 275,
      "p": 3.6,
      "c": 36,
      "f": 12
    }
  },
  {
    "n": "Burger King Fries (large)",
    "k": 237.11,
    "p": 3.08,
    "c": 30.82,
    "f": 10.06,
    "g": 159,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 159,
      "k": 377,
      "p": 4.9,
      "c": 49,
      "f": 16
    }
  },
  {
    "n": "Burger King Loaded King Fries with Bacon",
    "k": 228.14,
    "p": 4.62,
    "c": 25.63,
    "f": 11.06,
    "g": 199,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 199,
      "k": 454,
      "p": 9.2,
      "c": 51,
      "f": 22
    }
  },
  {
    "n": "Burger King Loaded King Fries",
    "k": 219.58,
    "p": 3.49,
    "c": 26.46,
    "f": 10.05,
    "g": 189,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 189,
      "k": 415,
      "p": 6.6,
      "c": 50,
      "f": 19
    }
  },
  {
    "n": "Burger King Onion Rings (9 pieces)",
    "k": 249.63,
    "p": 5.11,
    "c": 31.11,
    "f": 11.11,
    "g": 135,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 135,
      "k": 337,
      "p": 6.9,
      "c": 42,
      "f": 15
    }
  },
  {
    "n": "Burger King Mango and Passionfruit Cheesecake Bar",
    "k": 356.76,
    "p": 4.45,
    "c": 43.65,
    "f": 18.38,
    "g": 74,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 74,
      "k": 264,
      "p": 3.29,
      "c": 32.3,
      "f": 13.6
    }
  },
  {
    "n": "Burger King Chocolate Brownie Cheesecake Bar",
    "k": 358.54,
    "p": 5.49,
    "c": 42.93,
    "f": 18.29,
    "g": 82,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 82,
      "k": 294,
      "p": 4.5,
      "c": 35.2,
      "f": 15
    }
  },
  {
    "n": "Burger King Strawberry Milkshake Cheesecake Bar",
    "k": 346.34,
    "p": 4.88,
    "c": 38.66,
    "f": 19.51,
    "g": 82,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 82,
      "k": 284,
      "p": 4,
      "c": 31.7,
      "f": 16
    }
  },
  {
    "n": "Burger King Ben & Jerry's Cookie Dough (large)",
    "k": 269.95,
    "p": 3.94,
    "c": 32.02,
    "f": 15.02,
    "g": 406,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 406,
      "k": 1096,
      "p": 16,
      "c": 130,
      "f": 61
    }
  },
  {
    "n": "Burger King Ben & Jerry's Cookie Dough (small)",
    "k": 245.0,
    "p": 3.3,
    "c": 33.33,
    "f": 10.9,
    "g": 60,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 60,
      "k": 147,
      "p": 1.98,
      "c": 20,
      "f": 6.54
    }
  },
  {
    "n": "Burger King Ben & Jerry's Chocolate Fudge Brownie (large)",
    "k": 249.26,
    "p": 4.41,
    "c": 29.41,
    "f": 12.5,
    "g": 408,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 408,
      "k": 1017,
      "p": 18,
      "c": 120,
      "f": 51
    }
  },
  {
    "n": "Burger King Ben & Jerry's Chocolate Fudge Brownie (small)",
    "k": 245.0,
    "p": 4.19,
    "c": 29.0,
    "f": 13.0,
    "g": 72,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 72,
      "k": 176.4,
      "p": 3.02,
      "c": 20.88,
      "f": 9.36
    }
  },
  {
    "n": "Burger King Ben & Jerry's Caramel Chew Chew (small)",
    "k": 270.0,
    "p": 3.5,
    "c": 28.0,
    "f": 15.0,
    "g": 72,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 72,
      "k": 194.4,
      "p": 2.52,
      "c": 20.16,
      "f": 10.8
    }
  },
  {
    "n": "Burger King Twix Fusion",
    "k": 152.32,
    "p": 2.61,
    "c": 26.55,
    "f": 3.91,
    "g": 138,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 138,
      "k": 210.2,
      "p": 3.6,
      "c": 36.64,
      "f": 5.4
    }
  },
  {
    "n": "Burger King Mini Twix Fusion",
    "k": 166.33,
    "p": 2.55,
    "c": 29.59,
    "f": 4.08,
    "g": 98,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 98,
      "k": 163,
      "p": 2.5,
      "c": 29,
      "f": 4
    }
  },
  {
    "n": "Burger King Smarties King Fusion",
    "k": 150.76,
    "p": 2.95,
    "c": 23.48,
    "f": 5.08,
    "g": 132,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 132,
      "k": 199,
      "p": 3.9,
      "c": 31,
      "f": 6.7
    }
  },
  {
    "n": "Burger King Mini Smarties Fusion",
    "k": 165.22,
    "p": 3.04,
    "c": 25.0,
    "f": 5.65,
    "g": 92,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 92,
      "k": 152,
      "p": 2.8,
      "c": 23,
      "f": 5.2
    }
  },
  {
    "n": "Burger King Vanilla Sundae",
    "k": 119.17,
    "p": 2.67,
    "c": 18.33,
    "f": 3.67,
    "g": 120,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 120,
      "k": 143,
      "p": 3.2,
      "c": 22,
      "f": 4.4
    }
  },
  {
    "n": "Burger King Mint Chocolate Sundae",
    "k": 184,
    "p": 3.4,
    "c": 30.5,
    "f": 5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 184,
      "p": 3.4,
      "c": 30.5,
      "f": 5
    }
  },
  {
    "n": "Burger King Chocolate Sundae",
    "k": 136.3,
    "p": 2.59,
    "c": 22.96,
    "f": 3.7,
    "g": 135,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 135,
      "k": 184,
      "p": 3.5,
      "c": 31,
      "f": 5
    }
  },
  {
    "n": "Burger King Strawberry Sundae",
    "k": 132.59,
    "p": 2.52,
    "c": 22.22,
    "f": 3.33,
    "g": 135,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 135,
      "k": 179,
      "p": 3.4,
      "c": 30,
      "f": 4.5
    }
  },
  {
    "n": "Burger King Salted Caramel Sundae",
    "k": 135.56,
    "p": 2.59,
    "c": 22.22,
    "f": 3.85,
    "g": 135,
    "cat": "fastfood",
    "src": "bk-gb",
    "ref": {
      "g": 135,
      "k": 183,
      "p": 3.5,
      "c": 30,
      "f": 5.2
    }
  },
  {
    "n": "Burger King Coca-Cola Zero",
    "k": 2,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 2,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Coca-Cola Zero (large)",
    "k": 3,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 3,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Diet Coca-Cola",
    "k": 1,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 1,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Diet Coca-Cola (large)",
    "k": 2,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 2,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Sprite Zero",
    "k": 4.5,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 4.5,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Sprite Zero (large)",
    "k": 6.3,
    "p": 0,
    "c": 0,
    "f": 0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 6.3,
      "p": 0,
      "c": 0,
      "f": 0
    }
  },
  {
    "n": "Burger King Semi-Skimmed Milk",
    "k": 49.2,
    "p": 3.6,
    "c": 4.8,
    "f": 1.68,
    "g": 250,
    "cat": "drinks",
    "src": "bk-gb",
    "ref": {
      "g": 250,
      "k": 123,
      "p": 9,
      "c": 12,
      "f": 4.2
    }
  },
  {
    "n": "Burger King Cheddar Cheese Sauce XL",
    "k": 238.46,
    "p": 9.54,
    "c": 8.92,
    "f": 18.46,
    "g": 65,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 65,
      "k": 155,
      "p": 6.2,
      "c": 5.8,
      "f": 12
    }
  },
  {
    "n": "Burger King Garlic Mayo",
    "k": 92,
    "p": 0.5,
    "c": 1.3,
    "f": 9.6,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 1,
      "k": 92,
      "p": 0.5,
      "c": 1.3,
      "f": 9.6
    }
  },
  {
    "n": "Burger King BBQ Dip Pot",
    "k": 152.0,
    "p": 1.2,
    "c": 36.0,
    "f": 0.0,
    "g": 25,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 25,
      "k": 38,
      "p": 0.3,
      "c": 9,
      "f": 0
    }
  },
  {
    "n": "Burger King Mayo Dip Pot",
    "k": 472.0,
    "p": 0.1,
    "c": 5.85,
    "f": 49.8,
    "g": 20,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 20,
      "k": 94.4,
      "p": 0.02,
      "c": 1.17,
      "f": 9.96
    }
  },
  {
    "n": "Burger King Sweet Chilli Dip Pot",
    "k": 188.0,
    "p": 0.0,
    "c": 48.0,
    "f": 0.0,
    "g": 25,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 25,
      "k": 47,
      "p": 0,
      "c": 12,
      "f": 0
    }
  },
  {
    "n": "Burger King Spicy Mayo Dip Pot",
    "k": 380.0,
    "p": 1.6,
    "c": 14.4,
    "f": 35.2,
    "g": 25,
    "cat": "sauces",
    "src": "bk-gb",
    "ref": {
      "g": 25,
      "k": 95,
      "p": 0.4,
      "c": 3.6,
      "f": 8.8
    }
  }
]
