import type { Food } from '@/core/types'

/** Greggs UK menu, per 100 g (per 100 ml for drinks); `g` is Greggs' own portion.
 *  GENERATED by scripts/import/greggs.py from Greggs' nutrition PDF: don't edit by hand. */
export const GREGGS: Food[] = [
  {
    "n": "Greggs Cheese & Onion Bake",
    "k": 308.35,
    "p": 6.08,
    "c": 23.34,
    "f": 21.22,
    "g": 141.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 141.4,
      "k": 436.0,
      "p": 8.6,
      "c": 33.0,
      "f": 30.0
    }
  },
  {
    "n": "Greggs Sausage Roll",
    "k": 336.89,
    "p": 8.83,
    "c": 23.3,
    "f": 23.3,
    "g": 103.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 103.0,
      "k": 347.0,
      "p": 9.1,
      "c": 24.0,
      "f": 24.0
    }
  },
  {
    "n": "Greggs Steak Bake",
    "k": 301.32,
    "p": 11.0,
    "c": 21.26,
    "f": 19.06,
    "g": 136.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 136.4,
      "k": 411.0,
      "p": 15.0,
      "c": 29.0,
      "f": 26.0
    }
  },
  {
    "n": "Greggs Yum Yum",
    "k": 396.42,
    "p": 4.73,
    "c": 43.48,
    "f": 21.74,
    "g": 78.2,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 78.2,
      "k": 310.0,
      "p": 3.7,
      "c": 34.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs 6 Mini Sausage Rolls",
    "k": 321.01,
    "p": 8.9,
    "c": 28.06,
    "f": 19.16,
    "g": 146.1,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 146.1,
      "k": 469.0,
      "p": 13.0,
      "c": 41.0,
      "f": 28.0
    }
  },
  {
    "n": "Greggs All Butter Croissant",
    "k": 369.62,
    "p": 8.99,
    "c": 44.3,
    "f": 16.46,
    "g": 79.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 79.0,
      "k": 292.0,
      "p": 7.1,
      "c": 35.0,
      "f": 13.0
    }
  },
  {
    "n": "Greggs Americano Large",
    "k": 3.93,
    "p": 0.16,
    "c": 0.6,
    "f": 0.0,
    "g": 382.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 382.0,
      "k": 15.0,
      "p": 0.6,
      "c": 2.3,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Americano Regular",
    "k": 3.86,
    "p": 0.0,
    "c": 0.6,
    "f": 0.0,
    "g": 285.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 285.0,
      "k": 11.0,
      "p": 0.0,
      "c": 1.7,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Apple & Cinnamon Flavour Porridge",
    "k": 99.15,
    "p": 3.42,
    "c": 15.81,
    "f": 1.88,
    "g": 234.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 234.0,
      "k": 232.0,
      "p": 8.0,
      "c": 37.0,
      "f": 4.4
    }
  },
  {
    "n": "Greggs Apple and Strawberry Fruit Pot",
    "k": 47.78,
    "p": 0.56,
    "c": 9.67,
    "f": 0.0,
    "g": 90.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 90.0,
      "k": 43.0,
      "p": 0.5,
      "c": 8.7,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Apple Danish",
    "k": 277.63,
    "p": 4.03,
    "c": 47.13,
    "f": 7.88,
    "g": 116.7,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 116.7,
      "k": 324.0,
      "p": 4.7,
      "c": 55.0,
      "f": 9.2
    }
  },
  {
    "n": "Greggs Bacon & Lorne Breakfast Baguette",
    "k": 274.04,
    "p": 14.9,
    "c": 29.8,
    "f": 9.93,
    "g": 221.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 221.5,
      "k": 607.0,
      "p": 33.0,
      "c": 66.0,
      "f": 22.0
    }
  },
  {
    "n": "Greggs Bacon & Omelette Breakfast Roll",
    "k": 234.19,
    "p": 14.19,
    "c": 21.94,
    "f": 9.68,
    "g": 155.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 155.0,
      "k": 363.0,
      "p": 22.0,
      "c": 34.0,
      "f": 15.0
    }
  },
  {
    "n": "Greggs Bacon & Sausage Breakfast Baguette",
    "k": 263.79,
    "p": 13.91,
    "c": 30.22,
    "f": 9.59,
    "g": 208.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 208.5,
      "k": 550.0,
      "p": 29.0,
      "c": 63.0,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Bacon and Cheese Wrap",
    "k": 365.31,
    "p": 14.29,
    "c": 25.51,
    "f": 23.47,
    "g": 98.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 98.0,
      "k": 358.0,
      "p": 14.0,
      "c": 25.0,
      "f": 23.0
    }
  },
  {
    "n": "Greggs Bacon and Lorne Breakfast Roll",
    "k": 271.18,
    "p": 15.29,
    "c": 25.29,
    "f": 11.76,
    "g": 170.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 170.0,
      "k": 461.0,
      "p": 26.0,
      "c": 43.0,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Bacon and Omelette Breakfast Baguette",
    "k": 244.07,
    "p": 14.04,
    "c": 28.09,
    "f": 8.23,
    "g": 206.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 206.5,
      "k": 504.0,
      "p": 29.0,
      "c": 58.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs Bacon and Sausage Breakfast Roll",
    "k": 257.96,
    "p": 14.01,
    "c": 24.84,
    "f": 10.83,
    "g": 157.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 157.0,
      "k": 405.0,
      "p": 22.0,
      "c": 39.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs Bacon Breakfast Baguette",
    "k": 270.18,
    "p": 15.2,
    "c": 32.75,
    "f": 8.19,
    "g": 171.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 171.0,
      "k": 462.0,
      "p": 26.0,
      "c": 56.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Bacon Breakfast Roll",
    "k": 268.62,
    "p": 15.9,
    "c": 27.62,
    "f": 10.04,
    "g": 119.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 119.5,
      "k": 321.0,
      "p": 19.0,
      "c": 33.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Baguette",
    "k": 254.63,
    "p": 8.8,
    "c": 51.85,
    "f": 0.74,
    "g": 108.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 108.0,
      "k": 275.0,
      "p": 9.5,
      "c": 56.0,
      "f": 0.8
    }
  },
  {
    "n": "Greggs Bavarian Slice",
    "k": 296.06,
    "p": 3.39,
    "c": 40.94,
    "f": 13.39,
    "g": 127.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 127.0,
      "k": 376.0,
      "p": 4.3,
      "c": 52.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs BBQ Bites Meal Box",
    "k": 207.09,
    "p": 8.27,
    "c": 24.02,
    "f": 8.27,
    "g": 254.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 254.0,
      "k": 526.0,
      "p": 21.0,
      "c": 61.0,
      "f": 21.0
    }
  },
  {
    "n": "Greggs BBQ Chicken & Bacon Pizza",
    "k": 322.11,
    "p": 13.06,
    "c": 34.82,
    "f": 14.03,
    "g": 206.76,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 206.76,
      "k": 666.0,
      "p": 27.0,
      "c": 72.0,
      "f": 29.0
    }
  },
  {
    "n": "Greggs BBQ Chicken and Bacon Melt Baguette",
    "k": 246.17,
    "p": 13.09,
    "c": 34.04,
    "f": 5.99,
    "g": 267.3,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 267.3,
      "k": 658.0,
      "p": 35.0,
      "c": 91.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs BBQ Chicken and Bacon Pasta",
    "k": 170.88,
    "p": 9.12,
    "c": 17.89,
    "f": 6.67,
    "g": 285.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 285.0,
      "k": 487.0,
      "p": 26.0,
      "c": 51.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Belgian Bun",
    "k": 302.86,
    "p": 4.98,
    "c": 63.67,
    "f": 2.61,
    "g": 122.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 122.5,
      "k": 371.0,
      "p": 6.1,
      "c": 78.0,
      "f": 3.2
    }
  },
  {
    "n": "Greggs BLT",
    "k": 217.11,
    "p": 10.16,
    "c": 24.06,
    "f": 8.56,
    "g": 187.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 187.0,
      "k": 406.0,
      "p": 19.0,
      "c": 45.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs Blueberry Iced Matcha Latte",
    "k": 28.03,
    "p": 1.4,
    "c": 4.18,
    "f": 0.69,
    "g": 478.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 478.0,
      "k": 134.0,
      "p": 6.7,
      "c": 20.0,
      "f": 3.3
    }
  },
  {
    "n": "Greggs Bonfire Toffee Muffin",
    "k": 352.43,
    "p": 4.56,
    "c": 50.49,
    "f": 13.59,
    "g": 103.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 103.0,
      "k": 363.0,
      "p": 4.7,
      "c": 52.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Breakfast Box",
    "k": 219.08,
    "p": 16.03,
    "c": 4.81,
    "f": 15.27,
    "g": 131.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 131.0,
      "k": 287.0,
      "p": 21.0,
      "c": 6.3,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Buffalo Chicken Pizza",
    "k": 318.96,
    "p": 12.8,
    "c": 32.23,
    "f": 15.17,
    "g": 211.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 211.0,
      "k": 673.0,
      "p": 27.0,
      "c": 68.0,
      "f": 32.0
    }
  },
  {
    "n": "Greggs Buffalo Sauce",
    "k": 160.0,
    "p": 0.0,
    "c": 9.75,
    "f": 13.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 64.0,
      "p": 0.0,
      "c": 3.9,
      "f": 5.2
    }
  },
  {
    "n": "Greggs Cappuccino Large",
    "k": 34.86,
    "p": 2.51,
    "c": 3.98,
    "f": 1.01,
    "g": 327.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 327.0,
      "k": 114.0,
      "p": 8.2,
      "c": 13.0,
      "f": 3.3
    }
  },
  {
    "n": "Greggs Cappuccino Regular",
    "k": 34.18,
    "p": 2.4,
    "c": 4.36,
    "f": 0.8,
    "g": 275.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 275.0,
      "k": 94.0,
      "p": 6.6,
      "c": 12.0,
      "f": 2.2
    }
  },
  {
    "n": "Greggs Caramel Crispy",
    "k": 484.0,
    "p": 4.4,
    "c": 70.0,
    "f": 22.0,
    "g": 50.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 50.0,
      "k": 242.0,
      "p": 2.2,
      "c": 35.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Caramel Custard Doughnut",
    "k": 282.47,
    "p": 4.23,
    "c": 41.24,
    "f": 11.34,
    "g": 97.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 97.0,
      "k": 274.0,
      "p": 4.1,
      "c": 40.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Caramel Latte Large",
    "k": 52.93,
    "p": 2.4,
    "c": 6.47,
    "f": 1.89,
    "g": 417.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 417.5,
      "k": 221.0,
      "p": 10.0,
      "c": 27.0,
      "f": 7.9
    }
  },
  {
    "n": "Greggs Caramel Latte Regular",
    "k": 56.12,
    "p": 2.2,
    "c": 7.15,
    "f": 2.01,
    "g": 363.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 363.5,
      "k": 204.0,
      "p": 8.0,
      "c": 26.0,
      "f": 7.3
    }
  },
  {
    "n": "Greggs Cheese & Onion Stottie",
    "k": 244.06,
    "p": 9.76,
    "c": 30.14,
    "f": 8.91,
    "g": 235.6,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 235.6,
      "k": 575.0,
      "p": 23.0,
      "c": 71.0,
      "f": 21.0
    }
  },
  {
    "n": "Greggs Cheese & Pickle",
    "k": 275.69,
    "p": 11.11,
    "c": 31.94,
    "f": 11.11,
    "g": 144.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 144.0,
      "k": 397.0,
      "p": 16.0,
      "c": 46.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs Cheese & Tomato",
    "k": 216.95,
    "p": 9.04,
    "c": 23.73,
    "f": 9.04,
    "g": 177.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 177.0,
      "k": 384.0,
      "p": 16.0,
      "c": 42.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs Cheese and Caramelised Onion Toastie",
    "k": 263.06,
    "p": 12.0,
    "c": 33.12,
    "f": 8.64,
    "g": 208.32,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 208.32,
      "k": 548.0,
      "p": 25.0,
      "c": 69.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs Cheese Sandwich",
    "k": 270.18,
    "p": 12.28,
    "c": 31.58,
    "f": 9.65,
    "g": 114.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 114.0,
      "k": 308.0,
      "p": 14.0,
      "c": 36.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Cheese Scone",
    "k": 350.52,
    "p": 13.4,
    "c": 28.87,
    "f": 19.59,
    "g": 97.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 97.0,
      "k": 340.0,
      "p": 13.0,
      "c": 28.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Cherry & Mango Cooler",
    "k": 19.05,
    "p": 0.0,
    "c": 4.76,
    "f": 0.0,
    "g": 420.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 420.0,
      "k": 80.0,
      "p": 0.0,
      "c": 20.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Cherry Lemonade",
    "k": 14.04,
    "p": 0.0,
    "c": 3.69,
    "f": 0.0,
    "g": 406.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 406.0,
      "k": 57.0,
      "p": 0.0,
      "c": 15.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Chicken & Pepperoni Pizza Toastie",
    "k": 275.0,
    "p": 12.98,
    "c": 29.81,
    "f": 11.06,
    "g": 208.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 208.0,
      "k": 572.0,
      "p": 27.0,
      "c": 62.0,
      "f": 23.0
    }
  },
  {
    "n": "Greggs Chicken Bake",
    "k": 279.26,
    "p": 8.64,
    "c": 19.95,
    "f": 17.95,
    "g": 150.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 150.4,
      "k": 420.0,
      "p": 13.0,
      "c": 30.0,
      "f": 27.0
    }
  },
  {
    "n": "Greggs Chicken Caesar Salad with Egg",
    "k": 193.19,
    "p": 11.91,
    "c": 6.38,
    "f": 13.19,
    "g": 235.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 235.0,
      "k": 454.0,
      "p": 28.0,
      "c": 15.0,
      "f": 31.0
    }
  },
  {
    "n": "Greggs Chicken Roll",
    "k": 308.08,
    "p": 8.59,
    "c": 25.25,
    "f": 19.19,
    "g": 99.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 99.0,
      "k": 305.0,
      "p": 8.5,
      "c": 25.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Chocolate Brownie Bar",
    "k": 430.0,
    "p": 5.2,
    "c": 52.0,
    "f": 22.0,
    "g": 50.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 50.0,
      "k": 215.0,
      "p": 2.6,
      "c": 26.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Chocolate Cake Bar",
    "k": 402.7,
    "p": 7.03,
    "c": 43.24,
    "f": 21.62,
    "g": 74.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 74.0,
      "k": 298.0,
      "p": 5.2,
      "c": 32.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs Cloudy Lemonade",
    "k": 14.04,
    "p": 0.0,
    "c": 3.45,
    "f": 0.0,
    "g": 406.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 406.0,
      "k": 57.0,
      "p": 0.0,
      "c": 14.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Corn Topped Roll",
    "k": 254.93,
    "p": 9.3,
    "c": 46.48,
    "f": 2.82,
    "g": 71.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 71.0,
      "k": 181.0,
      "p": 6.6,
      "c": 33.0,
      "f": 2.0
    }
  },
  {
    "n": "Greggs Corned Beef Bake",
    "k": 290.86,
    "p": 7.67,
    "c": 22.32,
    "f": 18.83,
    "g": 143.37,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 143.37,
      "k": 417.0,
      "p": 11.0,
      "c": 32.0,
      "f": 27.0
    }
  },
  {
    "n": "Greggs Cream Éclair",
    "k": 398.77,
    "p": 5.19,
    "c": 30.86,
    "f": 28.4,
    "g": 81.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 81.0,
      "k": 323.0,
      "p": 4.2,
      "c": 25.0,
      "f": 23.0
    }
  },
  {
    "n": "Greggs Cream Iced Finger",
    "k": 335.14,
    "p": 5.14,
    "c": 42.34,
    "f": 16.22,
    "g": 111.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 111.0,
      "k": 372.0,
      "p": 5.7,
      "c": 47.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs Egg Mayonnaise & Tomato",
    "k": 187.26,
    "p": 7.56,
    "c": 23.75,
    "f": 5.94,
    "g": 185.3,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 185.3,
      "k": 347.0,
      "p": 14.0,
      "c": 44.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Egg Mayonnaise Sandwich",
    "k": 212.32,
    "p": 10.05,
    "c": 26.12,
    "f": 6.7,
    "g": 149.3,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 149.3,
      "k": 317.0,
      "p": 15.0,
      "c": 39.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Empire Biscuit",
    "k": 414.6,
    "p": 3.36,
    "c": 65.69,
    "f": 14.01,
    "g": 68.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 68.5,
      "k": 284.0,
      "p": 2.3,
      "c": 45.0,
      "f": 9.6
    }
  },
  {
    "n": "Greggs Espresso Extra Shot",
    "k": 20.2,
    "p": 1.52,
    "c": 3.28,
    "f": 0.0,
    "g": 39.6,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 39.6,
      "k": 8.0,
      "p": 0.6,
      "c": 1.3,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Espresso Shot",
    "k": 20.0,
    "p": 1.33,
    "c": 3.17,
    "f": 0.0,
    "g": 60.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 60.0,
      "k": 12.0,
      "p": 0.8,
      "c": 1.9,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Extra Bacon",
    "k": 310.34,
    "p": 28.97,
    "c": 0.0,
    "f": 20.69,
    "g": 14.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 14.5,
      "k": 45.0,
      "p": 4.2,
      "c": 0.0,
      "f": 3.0
    }
  },
  {
    "n": "Greggs Extra Breakfast Sausage",
    "k": 238.46,
    "p": 13.08,
    "c": 10.0,
    "f": 16.15,
    "g": 26.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 26.0,
      "k": 62.0,
      "p": 3.4,
      "c": 2.6,
      "f": 4.2
    }
  },
  {
    "n": "Greggs Extra Lorne Sausage",
    "k": 284.62,
    "p": 16.92,
    "c": 15.08,
    "f": 16.92,
    "g": 65.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 65.0,
      "k": 185.0,
      "p": 11.0,
      "c": 9.8,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Extra Omelette with Cheese",
    "k": 154.0,
    "p": 12.0,
    "c": 1.8,
    "f": 11.0,
    "g": 50.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 50.0,
      "k": 77.0,
      "p": 6.0,
      "c": 0.9,
      "f": 5.5
    }
  },
  {
    "n": "Greggs Fairtrade Apple Juice from Concentrate",
    "k": 46.0,
    "p": 0.0,
    "c": 11.33,
    "f": 0.0,
    "g": 150.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 150.0,
      "k": 69.0,
      "p": 0.0,
      "c": 17.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Fairtrade Orange Juice from Concentrate 250ml",
    "k": 45.0,
    "p": 0.0,
    "c": 10.0,
    "f": 0.0,
    "g": 250.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 100,
      "k": 45.0,
      "p": 0.0,
      "c": 10.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Fairtrade Orange Juice from Concentrate 500ml",
    "k": 45.0,
    "p": 0.0,
    "c": 10.0,
    "f": 0.0,
    "g": 500.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 100,
      "k": 45.0,
      "p": 0.0,
      "c": 10.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Fat Free Greek Style Yoghurt with Strawberry Compote",
    "k": 76.0,
    "p": 4.73,
    "c": 13.33,
    "f": 0.47,
    "g": 150.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 150.0,
      "k": 114.0,
      "p": 7.1,
      "c": 20.0,
      "f": 0.7
    }
  },
  {
    "n": "Greggs Flat White Regular",
    "k": 31.9,
    "p": 2.38,
    "c": 3.91,
    "f": 0.81,
    "g": 222.6,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 222.6,
      "k": 71.0,
      "p": 5.3,
      "c": 8.7,
      "f": 1.8
    }
  },
  {
    "n": "Greggs Free Range Egg Mayonnaise Baguette",
    "k": 211.2,
    "p": 7.88,
    "c": 26.14,
    "f": 7.88,
    "g": 241.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 241.0,
      "k": 509.0,
      "p": 19.0,
      "c": 63.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Free Range Egg Mayonnaise Half Baguette",
    "k": 210.79,
    "p": 7.88,
    "c": 25.73,
    "f": 7.97,
    "g": 120.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 120.5,
      "k": 254.0,
      "p": 9.5,
      "c": 31.0,
      "f": 9.6
    }
  },
  {
    "n": "Greggs Free Range Egg Mayonnaise",
    "k": 221.95,
    "p": 9.92,
    "c": 27.28,
    "f": 7.44,
    "g": 161.3,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 161.3,
      "k": 358.0,
      "p": 16.0,
      "c": 44.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Free Range Egg Pot",
    "k": 141.11,
    "p": 13.33,
    "c": 1.44,
    "f": 9.11,
    "g": 90.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 90.0,
      "k": 127.0,
      "p": 12.0,
      "c": 1.3,
      "f": 8.2
    }
  },
  {
    "n": "Greggs Fruit Scone",
    "k": 311.46,
    "p": 6.56,
    "c": 50.0,
    "f": 8.96,
    "g": 96.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 96.0,
      "k": 299.0,
      "p": 6.3,
      "c": 48.0,
      "f": 8.6
    }
  },
  {
    "n": "Greggs Fruity Flapjack",
    "k": 421.67,
    "p": 6.5,
    "c": 56.67,
    "f": 18.33,
    "g": 60.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 60.0,
      "k": 253.0,
      "p": 3.9,
      "c": 34.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Garlic & Herb Dip",
    "k": 320.0,
    "p": 0.0,
    "c": 7.25,
    "f": 32.5,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 128.0,
      "p": 0.0,
      "c": 2.9,
      "f": 13.0
    }
  },
  {
    "n": "Greggs Gingerbread Man",
    "k": 419.05,
    "p": 5.71,
    "c": 71.43,
    "f": 10.95,
    "g": 42.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 42.0,
      "k": 176.0,
      "p": 2.4,
      "c": 30.0,
      "f": 4.6
    }
  },
  {
    "n": "Greggs Glazed Ring Doughnut",
    "k": 346.55,
    "p": 3.28,
    "c": 60.34,
    "f": 10.0,
    "g": 58.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 58.0,
      "k": 201.0,
      "p": 1.9,
      "c": 35.0,
      "f": 5.8
    }
  },
  {
    "n": "Greggs Golden Syrup Flavour Porridge",
    "k": 105.06,
    "p": 3.21,
    "c": 18.14,
    "f": 1.81,
    "g": 237.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 237.0,
      "k": 249.0,
      "p": 7.6,
      "c": 43.0,
      "f": 4.3
    }
  },
  {
    "n": "Greggs Green Tea Regular",
    "k": 0.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 330.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 330.0,
      "k": 0.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Mature Cheddar & Onion Hand Cooked Crisps 40g",
    "k": 500.0,
    "p": 7.5,
    "c": 57.5,
    "f": 25.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 200.0,
      "p": 3.0,
      "c": 23.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Natural Mineral Water 500ml",
    "k": 0.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 500.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 100,
      "k": 0.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Natural Mineral Water 750ml",
    "k": 0.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 750.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 100,
      "k": 0.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Sea Salt & Cider Vinegar Hand Cooked Crisps 40g",
    "k": 500.0,
    "p": 6.75,
    "c": 57.5,
    "f": 25.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 200.0,
      "p": 2.7,
      "c": 23.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Thai Sweet Chilli Flavour Hand Cooked Crisps 40g",
    "k": 502.5,
    "p": 7.0,
    "c": 57.5,
    "f": 25.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 201.0,
      "p": 2.8,
      "c": 23.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Ham & Cheese Baguette",
    "k": 245.92,
    "p": 13.78,
    "c": 29.08,
    "f": 7.65,
    "g": 196.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 196.0,
      "k": 482.0,
      "p": 27.0,
      "c": 57.0,
      "f": 15.0
    }
  },
  {
    "n": "Greggs Ham and Cheese Toastie",
    "k": 261.86,
    "p": 14.95,
    "c": 27.97,
    "f": 9.65,
    "g": 207.36,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 207.36,
      "k": 543.0,
      "p": 31.0,
      "c": 58.0,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Ham Sandwich",
    "k": 204.76,
    "p": 11.9,
    "c": 29.37,
    "f": 3.89,
    "g": 126.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 126.0,
      "k": 258.0,
      "p": 15.0,
      "c": 37.0,
      "f": 4.9
    }
  },
  {
    "n": "Greggs Hash Browns",
    "k": 201.57,
    "p": 1.44,
    "c": 28.8,
    "f": 8.25,
    "g": 76.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 76.4,
      "k": 154.0,
      "p": 1.1,
      "c": 22.0,
      "f": 6.3
    }
  },
  {
    "n": "Greggs Honey Roast Ham & Egg Salad",
    "k": 172.25,
    "p": 8.9,
    "c": 23.04,
    "f": 4.5,
    "g": 191.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 191.0,
      "k": 329.0,
      "p": 17.0,
      "c": 44.0,
      "f": 8.6
    }
  },
  {
    "n": "Greggs Honey Roast Ham and Egg Salad Roll",
    "k": 169.9,
    "p": 9.18,
    "c": 20.92,
    "f": 4.9,
    "g": 196.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 196.0,
      "k": 333.0,
      "p": 18.0,
      "c": 41.0,
      "f": 9.6
    }
  },
  {
    "n": "Greggs Hot Buffalo Chicken Baguette",
    "k": 230.0,
    "p": 13.18,
    "c": 29.09,
    "f": 6.36,
    "g": 220.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 220.0,
      "k": 506.0,
      "p": 29.0,
      "c": 64.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Hot Chocolate Brownies",
    "k": 451.19,
    "p": 6.55,
    "c": 54.17,
    "f": 23.21,
    "g": 168.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 168.0,
      "k": 758.0,
      "p": 11.0,
      "c": 91.0,
      "f": 39.0
    }
  },
  {
    "n": "Greggs Hot Chocolate Large",
    "k": 66.04,
    "p": 2.0,
    "c": 10.93,
    "f": 1.5,
    "g": 439.1,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 439.1,
      "k": 290.0,
      "p": 8.8,
      "c": 48.0,
      "f": 6.6
    }
  },
  {
    "n": "Greggs Hot Chocolate Regular",
    "k": 58.87,
    "p": 1.8,
    "c": 9.68,
    "f": 1.4,
    "g": 372.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 372.0,
      "k": 219.0,
      "p": 6.7,
      "c": 36.0,
      "f": 5.2
    }
  },
  {
    "n": "Greggs Hot Ham & Cheese Baguette",
    "k": 257.23,
    "p": 14.88,
    "c": 29.76,
    "f": 7.97,
    "g": 188.16,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 188.16,
      "k": 484.0,
      "p": 28.0,
      "c": 56.0,
      "f": 15.0
    }
  },
  {
    "n": "Greggs Hot Honey",
    "k": 155.0,
    "p": 0.0,
    "c": 37.5,
    "f": 0.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 62.0,
      "p": 0.0,
      "c": 15.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Hot Mexican Chicken Baguette",
    "k": 218.95,
    "p": 11.94,
    "c": 33.17,
    "f": 3.89,
    "g": 226.08,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 226.08,
      "k": 495.0,
      "p": 27.0,
      "c": 75.0,
      "f": 8.8
    }
  },
  {
    "n": "Greggs Hot Milk Chocolate Cookies",
    "k": 490.0,
    "p": 5.93,
    "c": 54.29,
    "f": 25.71,
    "g": 140.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 140.0,
      "k": 686.0,
      "p": 8.3,
      "c": 76.0,
      "f": 36.0
    }
  },
  {
    "n": "Greggs Hot Yum Yums",
    "k": 395.78,
    "p": 4.73,
    "c": 44.12,
    "f": 21.74,
    "g": 156.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 156.4,
      "k": 619.0,
      "p": 7.4,
      "c": 69.0,
      "f": 34.0
    }
  },
  {
    "n": "Greggs Iced Americano",
    "k": 2.95,
    "p": 0.18,
    "c": 0.43,
    "f": 0.0,
    "g": 440.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 440.9,
      "k": 13.0,
      "p": 0.8,
      "c": 1.9,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Iced Caramel Chocolate",
    "k": 52.01,
    "p": 1.11,
    "c": 9.69,
    "f": 0.9,
    "g": 423.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 423.0,
      "k": 220.0,
      "p": 4.7,
      "c": 41.0,
      "f": 3.8
    }
  },
  {
    "n": "Greggs Iced Caramel Latte Regular",
    "k": 35.06,
    "p": 1.79,
    "c": 4.95,
    "f": 0.91,
    "g": 484.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 484.9,
      "k": 170.0,
      "p": 8.7,
      "c": 24.0,
      "f": 4.4
    }
  },
  {
    "n": "Greggs Iced Chocolate",
    "k": 40.97,
    "p": 1.2,
    "c": 6.62,
    "f": 0.99,
    "g": 393.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 393.0,
      "k": 161.0,
      "p": 4.7,
      "c": 26.0,
      "f": 3.9
    }
  },
  {
    "n": "Greggs Iced Latte Regular",
    "k": 26.9,
    "p": 1.91,
    "c": 2.82,
    "f": 0.89,
    "g": 460.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 460.9,
      "k": 124.0,
      "p": 8.8,
      "c": 13.0,
      "f": 4.1
    }
  },
  {
    "n": "Greggs Iced Matcha Latte",
    "k": 20.92,
    "p": 1.59,
    "c": 2.09,
    "f": 0.69,
    "g": 478.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 478.0,
      "k": 100.0,
      "p": 7.6,
      "c": 10.0,
      "f": 3.3
    }
  },
  {
    "n": "Greggs Iced Mocha",
    "k": 37.08,
    "p": 1.1,
    "c": 6.18,
    "f": 0.8,
    "g": 436.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 436.9,
      "k": 162.0,
      "p": 4.8,
      "c": 27.0,
      "f": 3.5
    }
  },
  {
    "n": "Greggs Iced Pumpkin Spice Latte with Salted Caramel Drizzle",
    "k": 37.08,
    "p": 1.4,
    "c": 6.21,
    "f": 0.7,
    "g": 498.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 498.9,
      "k": 185.0,
      "p": 7.0,
      "c": 31.0,
      "f": 3.5
    }
  },
  {
    "n": "Greggs Iced Vanilla Latte Regular",
    "k": 35.06,
    "p": 1.79,
    "c": 4.95,
    "f": 0.91,
    "g": 484.9,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 484.9,
      "k": 170.0,
      "p": 8.7,
      "c": 24.0,
      "f": 4.4
    }
  },
  {
    "n": "Greggs Jam Doughnut",
    "k": 310.53,
    "p": 5.26,
    "c": 48.68,
    "f": 10.0,
    "g": 76.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 76.0,
      "k": 236.0,
      "p": 4.0,
      "c": 37.0,
      "f": 7.6
    }
  },
  {
    "n": "Greggs Jammy Heart Biscuit",
    "k": 459.32,
    "p": 5.25,
    "c": 59.32,
    "f": 22.03,
    "g": 59.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 59.0,
      "k": 271.0,
      "p": 3.1,
      "c": 35.0,
      "f": 13.0
    }
  },
  {
    "n": "Greggs Latte Large",
    "k": 35.0,
    "p": 2.61,
    "c": 3.68,
    "f": 1.0,
    "g": 380.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 380.0,
      "k": 133.0,
      "p": 9.9,
      "c": 14.0,
      "f": 3.8
    }
  },
  {
    "n": "Greggs Latte Regular",
    "k": 34.97,
    "p": 2.39,
    "c": 3.99,
    "f": 1.01,
    "g": 326.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 326.0,
      "k": 114.0,
      "p": 7.8,
      "c": 13.0,
      "f": 3.3
    }
  },
  {
    "n": "Greggs Lorne & Omelette Breakfast Baguette",
    "k": 241.84,
    "p": 11.9,
    "c": 26.87,
    "f": 9.21,
    "g": 260.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 260.5,
      "k": 630.0,
      "p": 31.0,
      "c": 70.0,
      "f": 24.0
    }
  },
  {
    "n": "Greggs Lorne & Omelette Breakfast Roll",
    "k": 232.98,
    "p": 12.04,
    "c": 23.04,
    "f": 9.95,
    "g": 191.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 191.0,
      "k": 445.0,
      "p": 23.0,
      "c": 44.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Lorne Breakfast Baguette",
    "k": 267.9,
    "p": 13.17,
    "c": 30.86,
    "f": 9.88,
    "g": 243.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 243.0,
      "k": 651.0,
      "p": 32.0,
      "c": 75.0,
      "f": 24.0
    }
  },
  {
    "n": "Greggs Lorne Breakfast Roll",
    "k": 261.7,
    "p": 12.06,
    "c": 29.79,
    "f": 9.93,
    "g": 141.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 141.0,
      "k": 369.0,
      "p": 17.0,
      "c": 42.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Mac & Cheese",
    "k": 189.85,
    "p": 8.32,
    "c": 13.87,
    "f": 11.1,
    "g": 324.46,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 324.46,
      "k": 616.0,
      "p": 27.0,
      "c": 45.0,
      "f": 36.0
    }
  },
  {
    "n": "Greggs Malted Brown Loaf",
    "k": 264.29,
    "p": 9.52,
    "c": 50.0,
    "f": 2.62,
    "g": 42.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 42.0,
      "k": 111.0,
      "p": 4.0,
      "c": 21.0,
      "f": 1.1
    }
  },
  {
    "n": "Greggs Mango and Strawberry Cooler",
    "k": 24.07,
    "p": 0.0,
    "c": 6.02,
    "f": 0.0,
    "g": 432.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 432.0,
      "k": 104.0,
      "p": 0.0,
      "c": 26.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Mango Lemonade",
    "k": 18.05,
    "p": 0.0,
    "c": 4.51,
    "f": 0.0,
    "g": 421.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 421.0,
      "k": 76.0,
      "p": 0.0,
      "c": 19.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Margherita Pizza",
    "k": 366.25,
    "p": 11.88,
    "c": 40.0,
    "f": 16.88,
    "g": 160.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 160.0,
      "k": 586.0,
      "p": 19.0,
      "c": 64.0,
      "f": 27.0
    }
  },
  {
    "n": "Greggs Mature Cheddar Cheese Ploughman's Oval Bite",
    "k": 200.88,
    "p": 8.81,
    "c": 22.91,
    "f": 7.49,
    "g": 227.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 227.0,
      "k": 456.0,
      "p": 20.0,
      "c": 52.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs Mature Cheddar Cheese Salad Baguette",
    "k": 210.0,
    "p": 8.57,
    "c": 28.1,
    "f": 6.67,
    "g": 210.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 210.0,
      "k": 441.0,
      "p": 18.0,
      "c": 59.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Mexican Chicken Baguette",
    "k": 208.92,
    "p": 11.89,
    "c": 31.0,
    "f": 3.69,
    "g": 235.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 235.5,
      "k": 492.0,
      "p": 28.0,
      "c": 73.0,
      "f": 8.7
    }
  },
  {
    "n": "Greggs Mexican Chicken Flatbread",
    "k": 189.85,
    "p": 12.18,
    "c": 24.87,
    "f": 4.11,
    "g": 197.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 197.0,
      "k": 374.0,
      "p": 24.0,
      "c": 49.0,
      "f": 8.1
    }
  },
  {
    "n": "Greggs Mexican Chicken Oval Bite",
    "k": 212.9,
    "p": 11.98,
    "c": 29.03,
    "f": 4.61,
    "g": 217.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 217.0,
      "k": 462.0,
      "p": 26.0,
      "c": 63.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Mexican Chicken Sandwich",
    "k": 198.86,
    "p": 13.07,
    "c": 27.84,
    "f": 3.41,
    "g": 176.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 176.0,
      "k": 350.0,
      "p": 23.0,
      "c": 49.0,
      "f": 6.0
    }
  },
  {
    "n": "Greggs Milk Chocolate Caramel Shortbread Offcuts",
    "k": 472.83,
    "p": 5.66,
    "c": 58.11,
    "f": 24.15,
    "g": 265.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 265.0,
      "k": 1253.0,
      "p": 15.0,
      "c": 154.0,
      "f": 64.0
    }
  },
  {
    "n": "Greggs Milk Chocolate Caramel Shortbreads",
    "k": 464.52,
    "p": 5.65,
    "c": 58.06,
    "f": 22.58,
    "g": 62.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 62.0,
      "k": 288.0,
      "p": 3.5,
      "c": 36.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Milk Chocolate Cookies",
    "k": 490.0,
    "p": 5.86,
    "c": 54.29,
    "f": 25.71,
    "g": 70.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 70.0,
      "k": 343.0,
      "p": 4.1,
      "c": 38.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs Milk Chocolate Dipping Sauce",
    "k": 333.33,
    "p": 1.83,
    "c": 56.67,
    "f": 11.0,
    "g": 60.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 60.0,
      "k": 200.0,
      "p": 1.1,
      "c": 34.0,
      "f": 6.6
    }
  },
  {
    "n": "Greggs Mocha Large",
    "k": 77.95,
    "p": 2.51,
    "c": 13.08,
    "f": 1.79,
    "g": 390.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 390.0,
      "k": 304.0,
      "p": 9.8,
      "c": 51.0,
      "f": 7.0
    }
  },
  {
    "n": "Greggs Mocha Regular",
    "k": 66.01,
    "p": 2.01,
    "c": 11.05,
    "f": 1.5,
    "g": 353.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 353.0,
      "k": 233.0,
      "p": 7.1,
      "c": 39.0,
      "f": 5.3
    }
  },
  {
    "n": "Greggs Mozzarella & Cheddar Bites",
    "k": 332.53,
    "p": 13.43,
    "c": 22.72,
    "f": 20.65,
    "g": 96.834,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 96.834,
      "k": 322.0,
      "p": 13.0,
      "c": 22.0,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Novelty Bun (pink)",
    "k": 396.76,
    "p": 3.24,
    "c": 52.63,
    "f": 18.02,
    "g": 49.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 49.4,
      "k": 196.0,
      "p": 1.6,
      "c": 26.0,
      "f": 8.9
    }
  },
  {
    "n": "Greggs Novelty Bun (white)",
    "k": 395.96,
    "p": 3.23,
    "c": 52.53,
    "f": 17.98,
    "g": 49.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 49.5,
      "k": 196.0,
      "p": 1.6,
      "c": 26.0,
      "f": 8.9
    }
  },
  {
    "n": "Greggs Omelette Breakfast Baguette",
    "k": 207.04,
    "p": 9.86,
    "c": 27.23,
    "f": 6.1,
    "g": 213.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 213.0,
      "k": 441.0,
      "p": 21.0,
      "c": 58.0,
      "f": 13.0
    }
  },
  {
    "n": "Greggs Omelette Breakfast Roll",
    "k": 200.0,
    "p": 10.8,
    "c": 19.89,
    "f": 7.95,
    "g": 176.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 176.0,
      "k": 352.0,
      "p": 19.0,
      "c": 35.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Oval Bite",
    "k": 262.86,
    "p": 11.43,
    "c": 43.81,
    "f": 3.71,
    "g": 105.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 105.0,
      "k": 276.0,
      "p": 12.0,
      "c": 46.0,
      "f": 3.9
    }
  },
  {
    "n": "Greggs Pain au Chocolat",
    "k": 378.48,
    "p": 8.35,
    "c": 44.3,
    "f": 17.72,
    "g": 79.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 79.0,
      "k": 299.0,
      "p": 6.6,
      "c": 35.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Peach Melba",
    "k": 372.73,
    "p": 2.63,
    "c": 43.43,
    "f": 21.21,
    "g": 99.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 99.0,
      "k": 369.0,
      "p": 2.6,
      "c": 43.0,
      "f": 21.0
    }
  },
  {
    "n": "Greggs Peppermint Tea Regular",
    "k": 0.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 330.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 330.0,
      "k": 0.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Pepperoni Pizza",
    "k": 372.09,
    "p": 12.21,
    "c": 37.21,
    "f": 19.19,
    "g": 172.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 172.0,
      "k": 640.0,
      "p": 21.0,
      "c": 64.0,
      "f": 33.0
    }
  },
  {
    "n": "Greggs Pineapple Cake",
    "k": 359.42,
    "p": 2.32,
    "c": 59.42,
    "f": 12.03,
    "g": 69.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 69.0,
      "k": 248.0,
      "p": 1.6,
      "c": 41.0,
      "f": 8.3
    }
  },
  {
    "n": "Greggs Pineapple Fruit Pot",
    "k": 50.0,
    "p": 0.55,
    "c": 10.91,
    "f": 0.0,
    "g": 110.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 110.0,
      "k": 55.0,
      "p": 0.6,
      "c": 12.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Pink Jammie Doughnut",
    "k": 343.33,
    "p": 4.56,
    "c": 51.11,
    "f": 13.33,
    "g": 90.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 90.0,
      "k": 309.0,
      "p": 4.1,
      "c": 46.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Prawn Layered Pasta Salad",
    "k": 116.9,
    "p": 4.14,
    "c": 15.17,
    "f": 4.14,
    "g": 290.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 290.0,
      "k": 339.0,
      "p": 12.0,
      "c": 44.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Pumpkin Spice Doughnut",
    "k": 336.96,
    "p": 4.67,
    "c": 50.0,
    "f": 13.04,
    "g": 92.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 92.0,
      "k": 310.0,
      "p": 4.3,
      "c": 46.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Pumpkin Spice Iced Matcha Latte with Salted Caramel Drizzle",
    "k": 31.97,
    "p": 1.39,
    "c": 4.92,
    "f": 0.7,
    "g": 488.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 488.0,
      "k": 156.0,
      "p": 6.8,
      "c": 24.0,
      "f": 3.4
    }
  },
  {
    "n": "Greggs Pumpkin Spice Latte with Salted Caramel Drizzle Large",
    "k": 54.91,
    "p": 2.37,
    "c": 7.1,
    "f": 1.89,
    "g": 422.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 422.5,
      "k": 232.0,
      "p": 10.0,
      "c": 30.0,
      "f": 8.0
    }
  },
  {
    "n": "Greggs Pumpkin Spice Latte with Salted Caramel Drizzle Regular",
    "k": 58.07,
    "p": 2.2,
    "c": 7.87,
    "f": 2.01,
    "g": 368.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 368.5,
      "k": 214.0,
      "p": 8.1,
      "c": 29.0,
      "f": 7.4
    }
  },
  {
    "n": "Greggs Roast Chicken and Bacon Club Baguette",
    "k": 191.13,
    "p": 10.04,
    "c": 25.93,
    "f": 5.02,
    "g": 239.1,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 239.1,
      "k": 457.0,
      "p": 24.0,
      "c": 62.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Roast Chicken and Bacon Club Half Baguette",
    "k": 190.72,
    "p": 10.04,
    "c": 25.93,
    "f": 4.94,
    "g": 119.55,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 119.55,
      "k": 228.0,
      "p": 12.0,
      "c": 31.0,
      "f": 5.9
    }
  },
  {
    "n": "Greggs Roast Chicken Mayonnaise Baguette",
    "k": 205.94,
    "p": 10.79,
    "c": 27.88,
    "f": 5.4,
    "g": 222.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 222.4,
      "k": 458.0,
      "p": 24.0,
      "c": 62.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Roast Chicken Salad",
    "k": 177.07,
    "p": 9.64,
    "c": 22.83,
    "f": 4.82,
    "g": 197.1,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 197.1,
      "k": 349.0,
      "p": 19.0,
      "c": 45.0,
      "f": 9.5
    }
  },
  {
    "n": "Greggs Roast Chicken Salad Roll",
    "k": 180.21,
    "p": 11.11,
    "c": 22.21,
    "f": 4.8,
    "g": 198.1,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 198.1,
      "k": 357.0,
      "p": 22.0,
      "c": 44.0,
      "f": 9.5
    }
  },
  {
    "n": "Greggs Roast Chicken with Honey Mustard Mayonnaise Oval Bite",
    "k": 181.06,
    "p": 11.89,
    "c": 22.03,
    "f": 4.41,
    "g": 227.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 227.0,
      "k": 411.0,
      "p": 27.0,
      "c": 50.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Salted Caramel Dipping Sauce",
    "k": 358.33,
    "p": 2.17,
    "c": 56.67,
    "f": 14.0,
    "g": 60.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 60.0,
      "k": 215.0,
      "p": 1.3,
      "c": 34.0,
      "f": 8.4
    }
  },
  {
    "n": "Greggs Sausage and Omelette Breakfast Baguette",
    "k": 231.12,
    "p": 11.2,
    "c": 26.97,
    "f": 8.3,
    "g": 241.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 241.0,
      "k": 557.0,
      "p": 27.0,
      "c": 65.0,
      "f": 20.0
    }
  },
  {
    "n": "Greggs Sausage and Omelette Breakfast Roll",
    "k": 221.91,
    "p": 11.24,
    "c": 21.91,
    "f": 9.55,
    "g": 178.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 178.0,
      "k": 395.0,
      "p": 20.0,
      "c": 39.0,
      "f": 17.0
    }
  },
  {
    "n": "Greggs Sausage Breakfast Baguette",
    "k": 250.23,
    "p": 11.06,
    "c": 30.88,
    "f": 8.76,
    "g": 217.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 217.0,
      "k": 543.0,
      "p": 24.0,
      "c": 67.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Sausage Breakfast Roll",
    "k": 244.81,
    "p": 11.04,
    "c": 27.27,
    "f": 9.74,
    "g": 154.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 154.0,
      "k": 377.0,
      "p": 17.0,
      "c": 42.0,
      "f": 15.0
    }
  },
  {
    "n": "Greggs Sausage, Bean & Cheese Melt",
    "k": 305.22,
    "p": 7.36,
    "c": 24.77,
    "f": 18.74,
    "g": 149.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 149.4,
      "k": 456.0,
      "p": 11.0,
      "c": 37.0,
      "f": 28.0
    }
  },
  {
    "n": "Greggs Savoury Mince Pie",
    "k": 339.92,
    "p": 11.07,
    "c": 24.11,
    "f": 22.13,
    "g": 253.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 253.0,
      "k": 860.0,
      "p": 28.0,
      "c": 61.0,
      "f": 56.0
    }
  },
  {
    "n": "Greggs Scotch Pie",
    "k": 241.01,
    "p": 12.23,
    "c": 25.18,
    "f": 10.07,
    "g": 139.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 139.0,
      "k": 335.0,
      "p": 17.0,
      "c": 35.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Side Salad",
    "k": 14.58,
    "p": 1.15,
    "c": 1.77,
    "f": 0.0,
    "g": 96.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 96.0,
      "k": 14.0,
      "p": 1.1,
      "c": 1.7,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Simply Creamy Porridge",
    "k": 109.21,
    "p": 3.29,
    "c": 18.86,
    "f": 1.8,
    "g": 228.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 228.0,
      "k": 249.0,
      "p": 7.5,
      "c": 43.0,
      "f": 4.1
    }
  },
  {
    "n": "Greggs Smoky BBQ Dip",
    "k": 187.5,
    "p": 1.5,
    "c": 45.0,
    "f": 0.0,
    "g": 40.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 40.0,
      "k": 75.0,
      "p": 0.6,
      "c": 18.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Southern Fried Chicken Baguette",
    "k": 249.02,
    "p": 11.18,
    "c": 37.11,
    "f": 5.81,
    "g": 223.68,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 223.68,
      "k": 557.0,
      "p": 25.0,
      "c": 83.0,
      "f": 13.0
    }
  },
  {
    "n": "Greggs Southern Fried Chicken Goujons",
    "k": 250.0,
    "p": 16.88,
    "c": 20.0,
    "f": 11.25,
    "g": 160.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 160.0,
      "k": 400.0,
      "p": 27.0,
      "c": 32.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs Southern Fried Potato Wedges",
    "k": 160.0,
    "p": 2.4,
    "c": 25.33,
    "f": 5.13,
    "g": 150.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 150.0,
      "k": 240.0,
      "p": 3.6,
      "c": 38.0,
      "f": 7.7
    }
  },
  {
    "n": "Greggs Sparkling Raspberry Lemonade",
    "k": 3.0,
    "p": 0.0,
    "c": 0.1,
    "f": 0.0,
    "g": 500.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 500.0,
      "k": 15.0,
      "p": 0.0,
      "c": 0.5,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Spicy BBQ Chicken Bites",
    "k": 275.0,
    "p": 18.27,
    "c": 21.15,
    "f": 13.46,
    "g": 104.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 104.0,
      "k": 286.0,
      "p": 19.0,
      "c": 22.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Spicy Chicken Pizza",
    "k": 310.77,
    "p": 11.79,
    "c": 32.82,
    "f": 13.85,
    "g": 195.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 195.0,
      "k": 606.0,
      "p": 23.0,
      "c": 64.0,
      "f": 27.0
    }
  },
  {
    "n": "Greggs Spread (sandwich add-on)",
    "k": 270.0,
    "p": 0.0,
    "c": 0.0,
    "f": 30.0,
    "g": 10.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 10.0,
      "k": 27.0,
      "p": 0.0,
      "c": 0.0,
      "f": 3.0
    }
  },
  {
    "n": "Greggs Star Biscuit",
    "k": 481.77,
    "p": 6.25,
    "c": 57.29,
    "f": 22.92,
    "g": 38.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 38.4,
      "k": 185.0,
      "p": 2.4,
      "c": 22.0,
      "f": 8.8
    }
  },
  {
    "n": "Greggs Steak & Stilton® Bake",
    "k": 305.92,
    "p": 11.18,
    "c": 19.74,
    "f": 19.74,
    "g": 152.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 152.0,
      "k": 465.0,
      "p": 17.0,
      "c": 30.0,
      "f": 30.0
    }
  },
  {
    "n": "Greggs Stottie",
    "k": 244.29,
    "p": 8.71,
    "c": 47.14,
    "f": 1.71,
    "g": 70.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 70.0,
      "k": 171.0,
      "p": 6.1,
      "c": 33.0,
      "f": 1.2
    }
  },
  {
    "n": "Greggs Strawberry Iced Matcha Latte",
    "k": 30.98,
    "p": 1.39,
    "c": 4.78,
    "f": 0.71,
    "g": 481.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 481.0,
      "k": 149.0,
      "p": 6.7,
      "c": 23.0,
      "f": 3.4
    }
  },
  {
    "n": "Greggs Strawberry Lemonade",
    "k": 17.0,
    "p": 0.0,
    "c": 4.19,
    "f": 0.0,
    "g": 406.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 406.0,
      "k": 69.0,
      "p": 0.0,
      "c": 17.0,
      "f": 0.0
    }
  },
  {
    "n": "Greggs Sugar Strand Doughnut",
    "k": 379.66,
    "p": 5.76,
    "c": 50.85,
    "f": 16.95,
    "g": 59.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 59.0,
      "k": 224.0,
      "p": 3.4,
      "c": 30.0,
      "f": 10.0
    }
  },
  {
    "n": "Greggs Tandoori Chicken",
    "k": 208.96,
    "p": 10.75,
    "c": 28.06,
    "f": 5.31,
    "g": 167.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 167.5,
      "k": 350.0,
      "p": 18.0,
      "c": 47.0,
      "f": 8.9
    }
  },
  {
    "n": "Greggs Tandoori Chicken Baguette",
    "k": 205.83,
    "p": 11.21,
    "c": 29.15,
    "f": 4.93,
    "g": 223.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 223.0,
      "k": 459.0,
      "p": 25.0,
      "c": 65.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Tandoori Chicken Half Baguette",
    "k": 206.28,
    "p": 10.76,
    "c": 28.7,
    "f": 4.84,
    "g": 111.5,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 111.5,
      "k": 230.0,
      "p": 12.0,
      "c": 32.0,
      "f": 5.4
    }
  },
  {
    "n": "Greggs Tandoori Chicken Roll",
    "k": 178.06,
    "p": 10.2,
    "c": 21.94,
    "f": 5.0,
    "g": 196.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 196.0,
      "k": 349.0,
      "p": 20.0,
      "c": 43.0,
      "f": 9.8
    }
  },
  {
    "n": "Greggs Tomato and Mozzarella Pasta",
    "k": 183.16,
    "p": 5.26,
    "c": 17.89,
    "f": 9.82,
    "g": 285.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 285.0,
      "k": 522.0,
      "p": 15.0,
      "c": 51.0,
      "f": 28.0
    }
  },
  {
    "n": "Greggs Tomato Soup",
    "k": 65.0,
    "p": 1.6,
    "c": 8.33,
    "f": 2.7,
    "g": 300.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 300.0,
      "k": 195.0,
      "p": 4.8,
      "c": 25.0,
      "f": 8.1
    }
  },
  {
    "n": "Greggs Tottenham Cake",
    "k": 412.5,
    "p": 4.66,
    "c": 62.5,
    "f": 15.91,
    "g": 88.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 88.0,
      "k": 363.0,
      "p": 4.1,
      "c": 55.0,
      "f": 14.0
    }
  },
  {
    "n": "Greggs Triple Chocolate Cookies",
    "k": 475.71,
    "p": 5.86,
    "c": 51.43,
    "f": 25.71,
    "g": 70.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 70.0,
      "k": 333.0,
      "p": 4.1,
      "c": 36.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs Triple Chocolate Doughnut",
    "k": 382.35,
    "p": 5.06,
    "c": 47.06,
    "f": 18.82,
    "g": 85.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 85.0,
      "k": 325.0,
      "p": 4.3,
      "c": 40.0,
      "f": 16.0
    }
  },
  {
    "n": "Greggs Triple Chocolate Muffin",
    "k": 360.9,
    "p": 5.56,
    "c": 44.82,
    "f": 16.23,
    "g": 129.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 129.4,
      "k": 467.0,
      "p": 7.2,
      "c": 58.0,
      "f": 21.0
    }
  },
  {
    "n": "Greggs Tuna Crunch Baguette",
    "k": 175.0,
    "p": 11.02,
    "c": 27.12,
    "f": 2.2,
    "g": 236.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 236.0,
      "k": 413.0,
      "p": 26.0,
      "c": 64.0,
      "f": 5.2
    }
  },
  {
    "n": "Greggs Tuna Crunch Roll",
    "k": 170.05,
    "p": 11.23,
    "c": 22.99,
    "f": 3.21,
    "g": 187.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 187.0,
      "k": 318.0,
      "p": 21.0,
      "c": 43.0,
      "f": 6.0
    }
  },
  {
    "n": "Greggs Tuna Mayonnaise & Cucumber",
    "k": 173.89,
    "p": 11.1,
    "c": 23.26,
    "f": 3.81,
    "g": 189.2,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 189.2,
      "k": 329.0,
      "p": 21.0,
      "c": 44.0,
      "f": 7.2
    }
  },
  {
    "n": "Greggs Tuna Mayonnaise Stottie",
    "k": 190.82,
    "p": 11.88,
    "c": 26.92,
    "f": 3.48,
    "g": 252.6,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 252.6,
      "k": 482.0,
      "p": 30.0,
      "c": 68.0,
      "f": 8.8
    }
  },
  {
    "n": "Greggs Vanilla Custard Cream Doughnut",
    "k": 332.88,
    "p": 4.79,
    "c": 43.84,
    "f": 15.07,
    "g": 73.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 73.0,
      "k": 243.0,
      "p": 3.5,
      "c": 32.0,
      "f": 11.0
    }
  },
  {
    "n": "Greggs Vanilla Custard Slice",
    "k": 254.26,
    "p": 3.18,
    "c": 38.76,
    "f": 9.3,
    "g": 129.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 129.0,
      "k": 328.0,
      "p": 4.1,
      "c": 50.0,
      "f": 12.0
    }
  },
  {
    "n": "Greggs Vanilla Iced Matcha Latte",
    "k": 29.05,
    "p": 1.39,
    "c": 4.36,
    "f": 0.71,
    "g": 482.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 482.0,
      "k": 140.0,
      "p": 6.7,
      "c": 21.0,
      "f": 3.4
    }
  },
  {
    "n": "Greggs Vanilla Latte Large",
    "k": 53.89,
    "p": 2.4,
    "c": 6.71,
    "f": 1.89,
    "g": 417.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 417.5,
      "k": 225.0,
      "p": 10.0,
      "c": 28.0,
      "f": 7.9
    }
  },
  {
    "n": "Greggs Vanilla Latte Regular",
    "k": 56.12,
    "p": 2.2,
    "c": 7.15,
    "f": 2.01,
    "g": 363.5,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 363.5,
      "k": 204.0,
      "p": 8.0,
      "c": 26.0,
      "f": 7.3
    }
  },
  {
    "n": "Greggs Vegan Roll Pork-Free",
    "k": 304.95,
    "p": 10.89,
    "c": 20.79,
    "f": 18.81,
    "g": 101.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 101.0,
      "k": 308.0,
      "p": 11.0,
      "c": 21.0,
      "f": 19.0
    }
  },
  {
    "n": "Greggs Vegetable Bake",
    "k": 285.9,
    "p": 5.92,
    "c": 21.94,
    "f": 19.28,
    "g": 150.4,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 150.4,
      "k": 430.0,
      "p": 8.9,
      "c": 33.0,
      "f": 29.0
    }
  },
  {
    "n": "Greggs Veggie Feast Pizza",
    "k": 266.96,
    "p": 8.7,
    "c": 30.0,
    "f": 12.17,
    "g": 230.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 230.0,
      "k": 614.0,
      "p": 20.0,
      "c": 69.0,
      "f": 28.0
    }
  },
  {
    "n": "Greggs White & Wholemeal Loaf",
    "k": 233.33,
    "p": 10.0,
    "c": 42.86,
    "f": 1.19,
    "g": 42.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 42.0,
      "k": 98.0,
      "p": 4.2,
      "c": 18.0,
      "f": 0.5
    }
  },
  {
    "n": "Greggs White & Wholemeal Roll",
    "k": 258.82,
    "p": 11.06,
    "c": 43.53,
    "f": 3.18,
    "g": 85.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 85.0,
      "k": 220.0,
      "p": 9.4,
      "c": 37.0,
      "f": 2.7
    }
  },
  {
    "n": "Greggs White Bread made with Sourdough",
    "k": 235.48,
    "p": 9.03,
    "c": 45.16,
    "f": 1.45,
    "g": 62.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 62.0,
      "k": 146.0,
      "p": 5.6,
      "c": 28.0,
      "f": 0.9
    }
  },
  {
    "n": "Greggs White Chocolate Cookies",
    "k": 490.0,
    "p": 6.0,
    "c": 55.71,
    "f": 25.71,
    "g": 70.0,
    "cat": "fastfood",
    "src": "greggs-uk",
    "ref": {
      "g": 70.0,
      "k": 343.0,
      "p": 4.2,
      "c": 39.0,
      "f": 18.0
    }
  },
  {
    "n": "Greggs White Coffee Large",
    "k": 11.94,
    "p": 1.01,
    "c": 1.51,
    "f": 0.21,
    "g": 377.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 377.0,
      "k": 45.0,
      "p": 3.8,
      "c": 5.7,
      "f": 0.8
    }
  },
  {
    "n": "Greggs White Coffee Regular",
    "k": 11.93,
    "p": 0.91,
    "c": 1.79,
    "f": 0.0,
    "g": 285.0,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 285.0,
      "k": 34.0,
      "p": 2.6,
      "c": 5.1,
      "f": 0.0
    }
  },
  {
    "n": "Greggs White Tea Large",
    "k": 2.97,
    "p": 0.2,
    "c": 0.3,
    "f": 0.0,
    "g": 404.2,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 404.2,
      "k": 12.0,
      "p": 0.8,
      "c": 1.2,
      "f": 0.0
    }
  },
  {
    "n": "Greggs White Tea Regular",
    "k": 3.16,
    "p": 0.28,
    "c": 0.28,
    "f": 0.0,
    "g": 316.8,
    "ml": true,
    "cat": "drinks",
    "src": "greggs-uk",
    "ref": {
      "g": 316.8,
      "k": 10.0,
      "p": 0.9,
      "c": 0.9,
      "f": 0.0
    }
  }
]
