import type { Food } from '@/core/types'

/** KFC UK menu, per item as KFC publishes it (KFC gives no portion weights).
 *  GENERATED by scripts/import/kfc.py from KFC's allergen & nutrition PDF: don't edit by hand. */
export const KFC: Food[] = [
  {
    "n": "KFC Zinger Burger",
    "k": 468.0,
    "p": 23.0,
    "c": 43.0,
    "f": 22.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 468.0,
      "p": 23.0,
      "c": 43.0,
      "f": 22.0
    }
  },
  {
    "n": "KFC Original Recipe Chicken piece",
    "k": 241.0,
    "p": 22.0,
    "c": 8.6,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 241.0,
      "p": 22.0,
      "c": 8.6,
      "f": 13.0
    }
  },
  {
    "n": "KFC Fillet Burger",
    "k": 463.0,
    "p": 28.8,
    "c": 43.0,
    "f": 18.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 463.0,
      "p": 28.8,
      "c": 43.0,
      "f": 18.7
    }
  },
  {
    "n": "KFC Fillet Tower Burger",
    "k": 604.0,
    "p": 32.1,
    "c": 55.5,
    "f": 27.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 604.0,
      "p": 32.1,
      "c": 55.5,
      "f": 27.0
    }
  },
  {
    "n": "KFC BBQ Fillet Tower Burger",
    "k": 612.0,
    "p": 32.1,
    "c": 57.0,
    "f": 27.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 612.0,
      "p": 32.1,
      "c": 57.0,
      "f": 27.2
    }
  },
  {
    "n": "KFC Zinger Supercharger Tower Burger",
    "k": 652.0,
    "p": 26.2,
    "c": 53.5,
    "f": 35.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 652.0,
      "p": 26.2,
      "c": 53.5,
      "f": 35.9
    }
  },
  {
    "n": "KFC Zinger Stacker Burger",
    "k": 813.0,
    "p": 45.1,
    "c": 60.9,
    "f": 42.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 813.0,
      "p": 45.1,
      "c": 60.9,
      "f": 42.3
    }
  },
  {
    "n": "KFC Mini Burger",
    "k": 277.0,
    "p": 18.0,
    "c": 28.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 277.0,
      "p": 18.0,
      "c": 28.0,
      "f": 10.0
    }
  },
  {
    "n": "KFC Kids Burger",
    "k": 258.0,
    "p": 18.0,
    "c": 30.0,
    "f": 7.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 258.0,
      "p": 18.0,
      "c": 30.0,
      "f": 7.0
    }
  },
  {
    "n": "KFC Vegan Burger",
    "k": 396.0,
    "p": 15.0,
    "c": 41.0,
    "f": 17.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 396.0,
      "p": 15.0,
      "c": 41.0,
      "f": 17.0
    }
  },
  {
    "n": "KFC Kentucky Mayo Twister",
    "k": 520.0,
    "p": 28.4,
    "c": 46.1,
    "f": 24.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 520.0,
      "p": 28.4,
      "c": 46.1,
      "f": 24.0
    }
  },
  {
    "n": "KFC Sweet Chilli Twister",
    "k": 492.0,
    "p": 28.7,
    "c": 53.1,
    "f": 17.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 492.0,
      "p": 28.7,
      "c": 53.1,
      "f": 17.6
    }
  },
  {
    "n": "KFC Smokey BBQ Twister",
    "k": 482.0,
    "p": 28.7,
    "c": 51.2,
    "f": 17.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 482.0,
      "p": 28.7,
      "c": 51.2,
      "f": 17.4
    }
  },
  {
    "n": "KFC Supercharger Twister",
    "k": 548.0,
    "p": 29.1,
    "c": 47.8,
    "f": 26.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 548.0,
      "p": 29.1,
      "c": 47.8,
      "f": 26.0
    }
  },
  {
    "n": "KFC Flamin' Mini Wrap",
    "k": 325.0,
    "p": 17.6,
    "c": 28.5,
    "f": 15.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 325.0,
      "p": 17.6,
      "c": 28.5,
      "f": 15.3
    }
  },
  {
    "n": "KFC BBQ Mini Wrap",
    "k": 294.0,
    "p": 17.6,
    "c": 30.9,
    "f": 10.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 294.0,
      "p": 17.6,
      "c": 30.9,
      "f": 10.8
    }
  },
  {
    "n": "KFC Original Ranch Rice Bowl",
    "k": 558.0,
    "p": 28.8,
    "c": 62.8,
    "f": 19.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 558.0,
      "p": 28.8,
      "c": 62.8,
      "f": 19.7
    }
  },
  {
    "n": "KFC Zinger Ranch Rice Bowl",
    "k": 543.0,
    "p": 23.0,
    "c": 61.6,
    "f": 21.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 543.0,
      "p": 23.0,
      "c": 61.6,
      "f": 21.3
    }
  },
  {
    "n": "KFC Veggie Ranch Rice Bowl",
    "k": 371.0,
    "p": 7.5,
    "c": 59.7,
    "f": 9.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 371.0,
      "p": 7.5,
      "c": 59.7,
      "f": 9.5
    }
  },
  {
    "n": "KFC Popcorn Chicken (small)",
    "k": 142.0,
    "p": 8.3,
    "c": 8.3,
    "f": 8.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 142.0,
      "p": 8.3,
      "c": 8.3,
      "f": 8.3
    }
  },
  {
    "n": "KFC Popcorn Chicken (regular)",
    "k": 307.0,
    "p": 18.0,
    "c": 18.0,
    "f": 18.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 307.0,
      "p": 18.0,
      "c": 18.0,
      "f": 18.0
    }
  },
  {
    "n": "KFC Popcorn Chicken (large)",
    "k": 478.0,
    "p": 28.0,
    "c": 28.0,
    "f": 28.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 478.0,
      "p": 28.0,
      "c": 28.0,
      "f": 28.0
    }
  },
  {
    "n": "KFC Hot Wing",
    "k": 91.0,
    "p": 4.9,
    "c": 3.8,
    "f": 6.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 91.0,
      "p": 4.9,
      "c": 3.8,
      "f": 6.2
    }
  },
  {
    "n": "KFC Tender",
    "k": 125.0,
    "p": 13.1,
    "c": 5.8,
    "f": 5.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 125.0,
      "p": 13.1,
      "c": 5.8,
      "f": 5.4
    }
  },
  {
    "n": "KFC Sweet Chilli Drip’d Bites",
    "k": 348.0,
    "p": 19.1,
    "c": 36.8,
    "f": 13.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 348.0,
      "p": 19.1,
      "c": 36.8,
      "f": 13.5
    }
  },
  {
    "n": "KFC Kansas BBQ Drip’d Bites",
    "k": 301.0,
    "p": 15.8,
    "c": 34.7,
    "f": 10.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 301.0,
      "p": 15.8,
      "c": 34.7,
      "f": 10.8
    }
  },
  {
    "n": "KFC Signature Fries (regular)",
    "k": 261.0,
    "p": 3.1,
    "c": 38.0,
    "f": 9.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 261.0,
      "p": 3.1,
      "c": 38.0,
      "f": 9.8
    }
  },
  {
    "n": "KFC Signature Fries (large)",
    "k": 372.0,
    "p": 4.4,
    "c": 54.0,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 372.0,
      "p": 4.4,
      "c": 54.0,
      "f": 14.0
    }
  },
  {
    "n": "KFC BBQ Beans (regular)",
    "k": 93.0,
    "p": 4.7,
    "c": 15.1,
    "f": 0.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 93.0,
      "p": 4.7,
      "c": 15.1,
      "f": 0.6
    }
  },
  {
    "n": "KFC BBQ Beans (large)",
    "k": 199.0,
    "p": 10.0,
    "c": 32.0,
    "f": 1.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 199.0,
      "p": 10.0,
      "c": 32.0,
      "f": 1.4
    }
  },
  {
    "n": "KFC Coleslaw (regular)",
    "k": 150.0,
    "p": 1.1,
    "c": 6.1,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 150.0,
      "p": 1.1,
      "c": 6.1,
      "f": 13.0
    }
  },
  {
    "n": "KFC Coleslaw (large)",
    "k": 299.0,
    "p": 2.2,
    "c": 12.0,
    "f": 26.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 299.0,
      "p": 2.2,
      "c": 12.0,
      "f": 26.0
    }
  },
  {
    "n": "KFC Corn Cobette",
    "k": 57.0,
    "p": 2.2,
    "c": 8.1,
    "f": 1.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 57.0,
      "p": 2.2,
      "c": 8.1,
      "f": 1.3
    }
  },
  {
    "n": "KFC Gravy (regular)",
    "k": 73.0,
    "p": 1.7,
    "c": 8.4,
    "f": 3.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 73.0,
      "p": 1.7,
      "c": 8.4,
      "f": 3.5
    }
  },
  {
    "n": "KFC Gravy (large)",
    "k": 166.0,
    "p": 3.9,
    "c": 19.0,
    "f": 8.0,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 166.0,
      "p": 3.9,
      "c": 19.0,
      "f": 8.0
    }
  },
  {
    "n": "KFC Creamy Mash (regular)",
    "k": 124.0,
    "p": 2.4,
    "c": 20.0,
    "f": 3.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 124.0,
      "p": 2.4,
      "c": 20.0,
      "f": 3.4
    }
  },
  {
    "n": "KFC Creamy Mash (large)",
    "k": 248.0,
    "p": 4.8,
    "c": 40.0,
    "f": 6.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 248.0,
      "p": 4.8,
      "c": 40.0,
      "f": 6.8
    }
  },
  {
    "n": "KFC Cajun Dirty Rice",
    "k": 217.0,
    "p": 3.8,
    "c": 43.0,
    "f": 2.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 217.0,
      "p": 3.8,
      "c": 43.0,
      "f": 2.6
    }
  },
  {
    "n": "KFC Side Salad",
    "k": 56.0,
    "p": 0.8,
    "c": 4.7,
    "f": 3.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 56.0,
      "p": 0.8,
      "c": 4.7,
      "f": 3.6
    }
  },
  {
    "n": "KFC Dirty Loaded Fries",
    "k": 473.0,
    "p": 11.8,
    "c": 53.1,
    "f": 22.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 473.0,
      "p": 11.8,
      "c": 53.1,
      "f": 22.7
    }
  },
  {
    "n": "KFC Hash Brown",
    "k": 92.0,
    "p": 0.9,
    "c": 8.8,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 92.0,
      "p": 0.9,
      "c": 8.8,
      "f": 5.5
    }
  },
  {
    "n": "KFC Oreo Krushem Shake",
    "k": 272.0,
    "p": 4.1,
    "c": 41.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 272.0,
      "p": 4.1,
      "c": 41.0,
      "f": 10.0
    }
  },
  {
    "n": "KFC Milkybar Krushem Shake",
    "k": 315.0,
    "p": 6.4,
    "c": 43.0,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 315.0,
      "p": 6.4,
      "c": 43.0,
      "f": 13.0
    }
  },
  {
    "n": "KFC Aero Peppermint Krushem Shake",
    "k": 280.0,
    "p": 3.9,
    "c": 41.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 280.0,
      "p": 3.9,
      "c": 41.0,
      "f": 11.0
    }
  },
  {
    "n": "KFC Raspberry Ripple Krushem Shake",
    "k": 262.0,
    "p": 4.6,
    "c": 36.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 262.0,
      "p": 4.6,
      "c": 36.0,
      "f": 11.0
    }
  },
  {
    "n": "KFC Dirty Louisiana Burger",
    "k": 694.0,
    "p": 32.6,
    "c": 61.4,
    "f": 34.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 694.0,
      "p": 32.6,
      "c": 61.4,
      "f": 34.3
    }
  },
  {
    "n": "KFC Zinger Dirty Louisiana Burger",
    "k": 690.0,
    "p": 26.7,
    "c": 61.3,
    "f": 36.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 690.0,
      "p": 26.7,
      "c": 61.3,
      "f": 36.6
    }
  },
  {
    "n": "KFC Loaded Doritos",
    "k": 829.0,
    "p": 34.6,
    "c": 82.2,
    "f": 38.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 829.0,
      "p": 34.6,
      "c": 82.2,
      "f": 38.6
    }
  },
  {
    "n": "KFC Dirty Millionaire Shake",
    "k": 611.0,
    "p": 8.3,
    "c": 103.2,
    "f": 17.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 611.0,
      "p": 8.3,
      "c": 103.2,
      "f": 17.9
    }
  },
  {
    "n": "KFC Mini Chocolate Sundae",
    "k": 138.0,
    "p": 2.5,
    "c": 20.0,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 138.0,
      "p": 2.5,
      "c": 20.0,
      "f": 5.3
    }
  },
  {
    "n": "KFC Oreo Sundae",
    "k": 256.0,
    "p": 4.1,
    "c": 38.0,
    "f": 9.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 256.0,
      "p": 4.1,
      "c": 38.0,
      "f": 9.6
    }
  },
  {
    "n": "KFC Milkybar Sundae",
    "k": 296.0,
    "p": 5.7,
    "c": 39.0,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 296.0,
      "p": 5.7,
      "c": 39.0,
      "f": 13.0
    }
  },
  {
    "n": "KFC Raspberry Ripple Sundae",
    "k": 276.0,
    "p": 5.0,
    "c": 37.0,
    "f": 12.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 276.0,
      "p": 5.0,
      "c": 37.0,
      "f": 12.0
    }
  },
  {
    "n": "KFC Milk Chocolate Cookie",
    "k": 284.0,
    "p": 2.9,
    "c": 36.3,
    "f": 13.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 284.0,
      "p": 2.9,
      "c": 36.3,
      "f": 13.8
    }
  },
  {
    "n": "KFC White Chocolate Cookie",
    "k": 283.0,
    "p": 2.7,
    "c": 36.0,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 283.0,
      "p": 2.7,
      "c": 36.0,
      "f": 14.0
    }
  },
  {
    "n": "KFC Yoyo Bear Strawberry",
    "k": 58.0,
    "p": 0.5,
    "c": 13.0,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 58.0,
      "p": 0.5,
      "c": 13.0,
      "f": 0.5
    }
  },
  {
    "n": "KFC Cherry Boba Refresher",
    "k": 114.0,
    "p": 0.5,
    "c": 27.3,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 114.0,
      "p": 0.5,
      "c": 27.3,
      "f": 0.5
    }
  },
  {
    "n": "KFC Strawberry Boba Refresher",
    "k": 148.0,
    "p": 0.5,
    "c": 35.3,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 148.0,
      "p": 0.5,
      "c": 35.3,
      "f": 0.5
    }
  },
  {
    "n": "KFC Sparkling Raspberry Lemonade",
    "k": 99.0,
    "p": 0.5,
    "c": 21.9,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 99.0,
      "p": 0.5,
      "c": 21.9,
      "f": 0.5
    }
  },
  {
    "n": "KFC Sparkling Cloudy Lemonade",
    "k": 24.0,
    "p": 0.5,
    "c": 4.3,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 24.0,
      "p": 0.5,
      "c": 4.3,
      "f": 0.5
    }
  },
  {
    "n": "KFC Iced Latte",
    "k": 102.0,
    "p": 6.6,
    "c": 11.8,
    "f": 3.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 102.0,
      "p": 6.6,
      "c": 11.8,
      "f": 3.1
    }
  },
  {
    "n": "KFC Iced Tiramisu Latte",
    "k": 215.0,
    "p": 7.1,
    "c": 39.2,
    "f": 3.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 215.0,
      "p": 7.1,
      "c": 39.2,
      "f": 3.3
    }
  },
  {
    "n": "KFC Iced Caramel Latte",
    "k": 166.0,
    "p": 6.4,
    "c": 27.9,
    "f": 3.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 166.0,
      "p": 6.4,
      "c": 27.9,
      "f": 3.2
    }
  },
  {
    "n": "KFC Iced Vanilla Latte",
    "k": 111.0,
    "p": 6.4,
    "c": 14.2,
    "f": 3.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 111.0,
      "p": 6.4,
      "c": 14.2,
      "f": 3.2
    }
  },
  {
    "n": "KFC Vanilla Iced Matcha",
    "k": 87.0,
    "p": 6.3,
    "c": 9.4,
    "f": 2.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 87.0,
      "p": 6.3,
      "c": 9.4,
      "f": 2.7
    }
  },
  {
    "n": "KFC Strawberry Shortcake Iced Matcha",
    "k": 264.0,
    "p": 0.5,
    "c": 44.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 264.0,
      "p": 0.5,
      "c": 44.0,
      "f": 6.4
    }
  },
  {
    "n": "KFC Oatly Iced Latte",
    "k": 122.0,
    "p": 2.8,
    "c": 15.3,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 122.0,
      "p": 2.8,
      "c": 15.3,
      "f": 5.5
    }
  },
  {
    "n": "KFC Oatly Iced Caramel Latte",
    "k": 244.0,
    "p": 2.4,
    "c": 43.8,
    "f": 6.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 244.0,
      "p": 2.4,
      "c": 43.8,
      "f": 6.3
    }
  },
  {
    "n": "KFC Oatly Iced Tiramisu Latte",
    "k": 175.0,
    "p": 2.8,
    "c": 27.4,
    "f": 5.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 175.0,
      "p": 2.8,
      "c": 27.4,
      "f": 5.7
    }
  },
  {
    "n": "KFC Oatly Iced Vanilla Latte",
    "k": 134.0,
    "p": 2.1,
    "c": 18.3,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 134.0,
      "p": 2.1,
      "c": 18.3,
      "f": 5.5
    }
  },
  {
    "n": "KFC Oatly Vanilla Iced Matcha",
    "k": 112.0,
    "p": 2.7,
    "c": 13.5,
    "f": 4.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 112.0,
      "p": 2.7,
      "c": 13.5,
      "f": 4.9
    }
  },
  {
    "n": "KFC Oatly Strawberry Shortcake Iced Matcha",
    "k": 283.0,
    "p": 3.5,
    "c": 47.5,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 283.0,
      "p": 3.5,
      "c": 47.5,
      "f": 8.4
    }
  },
  {
    "n": "KFC Caramel Krunch Shake",
    "k": 490.0,
    "p": 6.9,
    "c": 82.9,
    "f": 14.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 490.0,
      "p": 6.9,
      "c": 82.9,
      "f": 14.3
    }
  },
  {
    "n": "KFC Chocolate Krunch Shake",
    "k": 484.0,
    "p": 6.9,
    "c": 82.4,
    "f": 13.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 484.0,
      "p": 6.9,
      "c": 82.4,
      "f": 13.8
    }
  },
  {
    "n": "KFC Strawberry Shortcake Krunch Shake",
    "k": 481.0,
    "p": 6.6,
    "c": 83.1,
    "f": 13.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 481.0,
      "p": 6.6,
      "c": 83.1,
      "f": 13.3
    }
  },
  {
    "n": "KFC Garlic Parm Dip Pot",
    "k": 193.0,
    "p": 0.5,
    "c": 3.2,
    "f": 19.7,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 193.0,
      "p": 0.5,
      "c": 3.2,
      "f": 19.7
    }
  },
  {
    "n": "KFC Honey Mustard Dip Pot",
    "k": 194.0,
    "p": 0.7,
    "c": 9.3,
    "f": 17.1,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 194.0,
      "p": 0.7,
      "c": 9.3,
      "f": 17.1
    }
  },
  {
    "n": "KFC Hot Honey Habanero Dip Pot",
    "k": 92.0,
    "p": 0.5,
    "c": 22.4,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 92.0,
      "p": 0.5,
      "c": 22.4,
      "f": 0.5
    }
  },
  {
    "n": "KFC Jalapeno Ranch Dip Pot",
    "k": 155.0,
    "p": 0.6,
    "c": 3.4,
    "f": 15.4,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 155.0,
      "p": 0.6,
      "c": 3.4,
      "f": 15.4
    }
  },
  {
    "n": "KFC Mango Masala Dip Pot",
    "k": 63.0,
    "p": 0.5,
    "c": 15.0,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 63.0,
      "p": 0.5,
      "c": 15.0,
      "f": 0.5
    }
  },
  {
    "n": "KFC Original Sauce Dip Pot",
    "k": 158.0,
    "p": 0.7,
    "c": 3.3,
    "f": 15.6,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 158.0,
      "p": 0.7,
      "c": 3.3,
      "f": 15.6
    }
  },
  {
    "n": "KFC Supercharger Dip Pot",
    "k": 189.0,
    "p": 0.6,
    "c": 3.9,
    "f": 19.0,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 189.0,
      "p": 0.6,
      "c": 3.9,
      "f": 19.0
    }
  },
  {
    "n": "KFC Sweet Teriyaki Dip Pot",
    "k": 52.0,
    "p": 0.6,
    "c": 11.4,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 52.0,
      "p": 0.6,
      "c": 11.4,
      "f": 0.5
    }
  },
  {
    "n": "KFC Texas BBQ Dip Pot",
    "k": 70.0,
    "p": 0.5,
    "c": 16.6,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 70.0,
      "p": 0.5,
      "c": 16.6,
      "f": 0.5
    }
  },
  {
    "n": "KFC Heinz Tomato Ketchup Sachet",
    "k": 10.0,
    "p": 0.5,
    "c": 2.3,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 10.0,
      "p": 0.5,
      "c": 2.3,
      "f": 0.5
    }
  },
  {
    "n": "KFC Still Water Bottle",
    "k": 0.0,
    "p": 0.5,
    "c": 0.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 0.0,
      "p": 0.5,
      "c": 0.5,
      "f": 0.5
    }
  },
  {
    "n": "KFC Fruit Shoot Robinsons Blackcurrant & Apple",
    "k": 8.0,
    "p": 0.5,
    "c": 1.6,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 8.0,
      "p": 0.5,
      "c": 1.6,
      "f": 0.5
    }
  },
  {
    "n": "KFC Fruit Shoot Robinsons Orange",
    "k": 10.0,
    "p": 0.5,
    "c": 2.4,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 10.0,
      "p": 0.5,
      "c": 2.4,
      "f": 0.5
    }
  },
  {
    "n": "KFC Pepsi Max (regular)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Pepsi Max (large)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Pepsi Max Cherry (regular)",
    "k": 2.0,
    "p": 0.5,
    "c": 0.5,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.5,
      "c": 0.5,
      "f": 0.0
    }
  },
  {
    "n": "KFC Pepsi Max Cherry (large)",
    "k": 3.0,
    "p": 0.5,
    "c": 0.5,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 3.0,
      "p": 0.5,
      "c": 0.5,
      "f": 0.0
    }
  },
  {
    "n": "KFC 7Up Free (regular)",
    "k": 6.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 6.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC 7Up Free (large)",
    "k": 9.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 9.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Robinsons Apple & Blackcurrant (regular)",
    "k": 5.0,
    "p": 0.5,
    "c": 0.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 5.0,
      "p": 0.5,
      "c": 0.5,
      "f": 0.5
    }
  },
  {
    "n": "KFC Robinsons Apple & Blackcurrant (large)",
    "k": 6.0,
    "p": 0.5,
    "c": 0.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 6.0,
      "p": 0.5,
      "c": 0.5,
      "f": 0.5
    }
  },
  {
    "n": "KFC Tango Orange Sugar Free (regular)",
    "k": 4.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 4.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Tango Orange Sugar Free (large)",
    "k": 5.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 5.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Club Orange (regular)",
    "k": 161.0,
    "p": 0.0,
    "c": 39.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 161.0,
      "p": 0.0,
      "c": 39.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Club Orange (large)",
    "k": 226.0,
    "p": 0.0,
    "c": 55.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 226.0,
      "p": 0.0,
      "c": 55.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Club Orange Zero (regular)",
    "k": 9.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 9.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Club Orange Zero (large)",
    "k": 13.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 13.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Diet Pepsi (regular)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Diet Pepsi (large)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Pepsi Max Bottle",
    "k": 0.8,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Diet Pepsi Bottle",
    "k": 0.8,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Tango Bottle",
    "k": 19.6,
    "p": 0.0,
    "c": 4.4,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 49.0,
      "p": 0.0,
      "c": 11.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC 7up Free Bottle",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 5.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Club Orange (per 250ml)",
    "k": 16.0,
    "p": 0.0,
    "c": 3.72,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 40.0,
      "p": 0.0,
      "c": 9.3,
      "f": 0.0
    }
  },
  {
    "n": "KFC Pepsi Bottle",
    "k": 19.2,
    "p": 0.0,
    "c": 4.8,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 250,
      "k": 48.0,
      "p": 0.0,
      "c": 12.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Apple Tango (regular)",
    "k": 12.0,
    "p": 0.0,
    "c": 1.5,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 12.0,
      "p": 0.0,
      "c": 1.5,
      "f": 0.0
    }
  },
  {
    "n": "KFC Apple Tango (large)",
    "k": 18.0,
    "p": 0.0,
    "c": 2.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 18.0,
      "p": 0.0,
      "c": 2.3,
      "f": 0.0
    }
  },
  {
    "n": "KFC Lipton Ice Tea (regular)",
    "k": 57.0,
    "p": 0.0,
    "c": 14.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 57.0,
      "p": 0.0,
      "c": 14.0,
      "f": 0.0
    }
  },
  {
    "n": "KFC Lipton Ice Tea (large)",
    "k": 77.0,
    "p": 0.0,
    "c": 19.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "kfc-uk",
    "ref": {
      "g": 1,
      "k": 77.0,
      "p": 0.0,
      "c": 19.0,
      "f": 0.0
    }
  }
]
