import type { Food } from '@/core/types'

/** Nando's UK menu, per item as Nando's publishes it (no portion weights given).
 *  GENERATED by scripts/import/nandos_web.py from docs/data/snapshots/nandos-2026-09-25.json: don't edit by hand. */
export const NANDOS: Food[] = [
  {
    "n": "Nando's Half Chicken (plain)",
    "k": 568,
    "p": 80.0,
    "c": 0.5,
    "f": 27.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 568,
      "p": 80.0,
      "c": 0.5,
      "f": 27.2
    }
  },
  {
    "n": "Nando's Quarter Chicken (plain)",
    "k": 284,
    "p": 40.0,
    "c": 0.3,
    "f": 13.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 284,
      "p": 40.0,
      "c": 0.3,
      "f": 13.6
    }
  },
  {
    "n": "Nando's Chicken Pitta",
    "k": 485,
    "p": 36.6,
    "c": 51.3,
    "f": 14.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 485,
      "p": 36.6,
      "c": 51.3,
      "f": 14.9
    }
  },
  {
    "n": "Nando's Peri-Peri Chips",
    "k": 452,
    "p": 6.4,
    "c": 64.9,
    "f": 19.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 452,
      "p": 6.4,
      "c": 64.9,
      "f": 19.4
    }
  },
  {
    "n": "Nando's Halloumi Sticks & Dip",
    "k": 452,
    "p": 27.1,
    "c": 14.8,
    "f": 32.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 452,
      "p": 27.1,
      "c": 14.8,
      "f": 32.0
    }
  },
  {
    "n": "Nando's Houmous with Peri-Peri Drizzle",
    "k": 815,
    "p": 25.0,
    "c": 103.8,
    "f": 32.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 815,
      "p": 25.0,
      "c": 103.8,
      "f": 32.6
    }
  },
  {
    "n": "Nando's Sweet Potato Wedges with Garlic Perinaise",
    "k": 440,
    "p": 8.1,
    "c": 51.0,
    "f": 24.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 440,
      "p": 8.1,
      "c": 51.0,
      "f": 24.1
    }
  },
  {
    "n": "Nando's Spicy Mixed Olives",
    "k": 138,
    "p": 1.2,
    "c": 4.7,
    "f": 13.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 138,
      "p": 1.2,
      "c": 4.7,
      "f": 13.5
    }
  },
  {
    "n": "Nando's Peri-Peri Nuts",
    "k": 793,
    "p": 27.3,
    "c": 14.8,
    "f": 67.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 793,
      "p": 27.3,
      "c": 14.8,
      "f": 67.4
    }
  },
  {
    "n": "Nando's Chicken Butterfly",
    "k": 332,
    "p": 59.4,
    "c": 0.2,
    "f": 10.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 332,
      "p": 59.4,
      "c": 0.2,
      "f": 10.1
    }
  },
  {
    "n": "Nando's Boneless Chicken Thighs (4 pieces)",
    "k": 578,
    "p": 70.1,
    "c": 0.2,
    "f": 30.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 578,
      "p": 70.1,
      "c": 0.2,
      "f": 30.4
    }
  },
  {
    "n": "Nando's Chicken Wings (3 pieces)",
    "k": 236,
    "p": 31.9,
    "c": 0.3,
    "f": 11.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 236,
      "p": 31.9,
      "c": 0.3,
      "f": 11.8
    }
  },
  {
    "n": "Nando's Quarter Chicken Breast",
    "k": 323,
    "p": 51.5,
    "c": 0.2,
    "f": 12.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 323,
      "p": 51.5,
      "c": 0.2,
      "f": 12.8
    }
  },
  {
    "n": "Nando's Quarter Chicken Leg",
    "k": 245,
    "p": 28.5,
    "c": 0.3,
    "f": 14.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 245,
      "p": 28.5,
      "c": 0.3,
      "f": 14.4
    }
  },
  {
    "n": "Nando's Fino Pitta",
    "k": 763,
    "p": 54.9,
    "c": 58.1,
    "f": 32.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 763,
      "p": 54.9,
      "c": 58.1,
      "f": 32.4
    }
  },
  {
    "n": "Nando's Butterfly Burger",
    "k": 632,
    "p": 66.6,
    "c": 53.0,
    "f": 16.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 632,
      "p": 66.6,
      "c": 53.0,
      "f": 16.4
    }
  },
  {
    "n": "Nando's Sunset Burger",
    "k": 619,
    "p": 46.1,
    "c": 42.1,
    "f": 27.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 619,
      "p": 46.1,
      "c": 42.1,
      "f": 27.7
    }
  },
  {
    "n": "Nando's Grilled Chicken Wrap",
    "k": 537,
    "p": 37.3,
    "c": 61.5,
    "f": 14.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 537,
      "p": 37.3,
      "c": 61.5,
      "f": 14.8
    }
  },
  {
    "n": "Nando's Double Chicken Wrap",
    "k": 674,
    "p": 65.9,
    "c": 61.6,
    "f": 17.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 674,
      "p": 65.9,
      "c": 61.6,
      "f": 17.3
    }
  },
  {
    "n": "Nando's Grilled Chicken Burger",
    "k": 438,
    "p": 35.8,
    "c": 52.9,
    "f": 8.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 438,
      "p": 35.8,
      "c": 52.9,
      "f": 8.9
    }
  },
  {
    "n": "Nando's Double Chicken Burger",
    "k": 576,
    "p": 64.4,
    "c": 53.0,
    "f": 11.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 576,
      "p": 64.4,
      "c": 53.0,
      "f": 11.5
    }
  },
  {
    "n": "Nando's Double Chicken Pitta",
    "k": 623,
    "p": 65.2,
    "c": 51.4,
    "f": 17.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 623,
      "p": 65.2,
      "c": 51.4,
      "f": 17.4
    }
  },
  {
    "n": "Nando's Rainbow Bowl",
    "k": 528,
    "p": 16.2,
    "c": 49.8,
    "f": 28.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 528,
      "p": 16.2,
      "c": 49.8,
      "f": 28.5
    }
  },
  {
    "n": "Nando's Spiced Chickpea Burger",
    "k": 534,
    "p": 15.6,
    "c": 75.8,
    "f": 19.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 534,
      "p": 15.6,
      "c": 75.8,
      "f": 19.9
    }
  },
  {
    "n": "Nando's The Great Imitator Wrap",
    "k": 560,
    "p": 24.7,
    "c": 63.8,
    "f": 22.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 560,
      "p": 24.7,
      "c": 63.8,
      "f": 22.7
    }
  },
  {
    "n": "Nando's The Great Imitator Burger",
    "k": 502,
    "p": 23.7,
    "c": 61.9,
    "f": 17.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 502,
      "p": 23.7,
      "c": 61.9,
      "f": 17.8
    }
  },
  {
    "n": "Nando's The Great Imitator Pitta",
    "k": 585,
    "p": 28.3,
    "c": 62.3,
    "f": 25.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 585,
      "p": 28.3,
      "c": 62.3,
      "f": 25.2
    }
  },
  {
    "n": "Nando's Beanie Wrap",
    "k": 660,
    "p": 22.0,
    "c": 81.0,
    "f": 24.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 660,
      "p": 22.0,
      "c": 81.0,
      "f": 24.9
    }
  },
  {
    "n": "Nando's Beanie Burger",
    "k": 562,
    "p": 20.5,
    "c": 72.4,
    "f": 19.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 562,
      "p": 20.5,
      "c": 72.4,
      "f": 19.0
    }
  },
  {
    "n": "Nando's Beanie Pitta",
    "k": 609,
    "p": 21.4,
    "c": 70.7,
    "f": 25.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 609,
      "p": 21.4,
      "c": 70.7,
      "f": 25.0
    }
  },
  {
    "n": "Nando's Chicken Burger (kids)",
    "k": 288,
    "p": 32.8,
    "c": 23.3,
    "f": 7.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 288,
      "p": 32.8,
      "c": 23.3,
      "f": 7.1
    }
  },
  {
    "n": "Nando's Chicken Breast Fillet (kids)",
    "k": 138,
    "p": 28.6,
    "c": 0.1,
    "f": 2.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 138,
      "p": 28.6,
      "c": 0.1,
      "f": 2.6
    }
  },
  {
    "n": "Nando's Beanie Burger (kids)",
    "k": 432,
    "p": 18.0,
    "c": 43.2,
    "f": 19.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 432,
      "p": 18.0,
      "c": 43.2,
      "f": 19.3
    }
  },
  {
    "n": "Nando's Beanie Patty (kids)",
    "k": 216,
    "p": 13.3,
    "c": 19.6,
    "f": 7.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 216,
      "p": 13.3,
      "c": 19.6,
      "f": 7.7
    }
  },
  {
    "n": "Nando's Spiced Grains & Butternut Squash (kids)",
    "k": 95,
    "p": 3.0,
    "c": 10.1,
    "f": 3.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 95,
      "p": 3.0,
      "c": 10.1,
      "f": 3.9
    }
  },
  {
    "n": "Nando's Spicy Rice (kids)",
    "k": 246,
    "p": 3.8,
    "c": 42.2,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 246,
      "p": 3.8,
      "c": 42.2,
      "f": 6.0
    }
  },
  {
    "n": "Nando's Corn on the Cob (kids)",
    "k": 72,
    "p": 2.9,
    "c": 11.0,
    "f": 1.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 72,
      "p": 2.9,
      "c": 11.0,
      "f": 1.4
    }
  },
  {
    "n": "Nando's Chips (kids)",
    "k": 225,
    "p": 3.2,
    "c": 32.3,
    "f": 9.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 225,
      "p": 3.2,
      "c": 32.3,
      "f": 9.7
    }
  },
  {
    "n": "Nando's Long Stem Broccoli (kids)",
    "k": 16,
    "p": 1.1,
    "c": 1.8,
    "f": 0.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 16,
      "p": 1.1,
      "c": 1.8,
      "f": 0.8
    }
  },
  {
    "n": "Nando's Little Tomatoes (kids)",
    "k": 13,
    "p": 0.7,
    "c": 2.2,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 13,
      "p": 0.7,
      "c": 2.2,
      "f": 0.3
    }
  },
  {
    "n": "Nando's Garlic Bread (kids)",
    "k": 219,
    "p": 4.0,
    "c": 20.4,
    "f": 13.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 219,
      "p": 4.0,
      "c": 20.4,
      "f": 13.6
    }
  },
  {
    "n": "Nando's Chilly Billy Lolly",
    "k": 30,
    "p": 0.2,
    "c": 7.6,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 30,
      "p": 0.2,
      "c": 7.6,
      "f": 0.1
    }
  },
  {
    "n": "Nando's Bottomless Vanilla Frozen Yoghurt",
    "k": 88,
    "p": 3.2,
    "c": 19.0,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 88,
      "p": 3.2,
      "c": 19.0,
      "f": 0.1
    }
  },
  {
    "n": "Nando's Bottomless Strawberry Frozen Yoghurt",
    "k": 86,
    "p": 3.1,
    "c": 18.0,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 86,
      "p": 3.1,
      "c": 18.0,
      "f": 0.1
    }
  },
  {
    "n": "Nando's Bottomless Chocolate Frozen Yoghurt",
    "k": 96,
    "p": 4.0,
    "c": 19.0,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 96,
      "p": 4.0,
      "c": 19.0,
      "f": 0.3
    }
  },
  {
    "n": "Nando's Bottomless Mango Frozen Yoghurt",
    "k": 87,
    "p": 3.1,
    "c": 18.0,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 87,
      "p": 3.1,
      "c": 18.0,
      "f": 0.1
    }
  },
  {
    "n": "Nando's Scoop of Vanilla Gelado",
    "k": 153,
    "p": 2.3,
    "c": 16.8,
    "f": 8.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 153,
      "p": 2.3,
      "c": 16.8,
      "f": 8.7
    }
  },
  {
    "n": "Nando's Cawston Press Apple & Pear (kids)",
    "k": 54,
    "p": 0.2,
    "c": 12.8,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 54,
      "p": 0.2,
      "c": 12.8,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Cawston Press Summer Berry (kids)",
    "k": 50,
    "p": 0.6,
    "c": 11.6,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 50,
      "p": 0.6,
      "c": 11.6,
      "f": 0.2
    }
  },
  {
    "n": "Nando's Bottle Green Apple Cordial",
    "k": 25,
    "p": 0.0,
    "c": 6.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 25,
      "p": 0.0,
      "c": 6.3,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottle Green Strawberry Cordial",
    "k": 25,
    "p": 0.0,
    "c": 6.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 25,
      "p": 0.0,
      "c": 6.3,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Peri-Salted Chips (large)",
    "k": 1128,
    "p": 15.9,
    "c": 162.1,
    "f": 48.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 1128,
      "p": 15.9,
      "c": 162.1,
      "f": 48.6
    }
  },
  {
    "n": "Nando's Garlic Bread (regular)",
    "k": 362,
    "p": 6.9,
    "c": 47.9,
    "f": 15.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 362,
      "p": 6.9,
      "c": 47.9,
      "f": 15.5
    }
  },
  {
    "n": "Nando's Garlic Bread (large)",
    "k": 723,
    "p": 13.8,
    "c": 95.9,
    "f": 30.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 723,
      "p": 13.8,
      "c": 95.9,
      "f": 30.9
    }
  },
  {
    "n": "Nando's Chips (regular)",
    "k": 450,
    "p": 6.3,
    "c": 64.6,
    "f": 19.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 450,
      "p": 6.3,
      "c": 64.6,
      "f": 19.4
    }
  },
  {
    "n": "Nando's Chips (large)",
    "k": 1125,
    "p": 15.8,
    "c": 161.5,
    "f": 48.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 1125,
      "p": 15.8,
      "c": 161.5,
      "f": 48.5
    }
  },
  {
    "n": "Nando's Spicy Rice (regular)",
    "k": 246,
    "p": 3.8,
    "c": 42.2,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 246,
      "p": 3.8,
      "c": 42.2,
      "f": 6.0
    }
  },
  {
    "n": "Nando's Spicy Rice (large)",
    "k": 492,
    "p": 7.5,
    "c": 84.3,
    "f": 12.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 492,
      "p": 7.5,
      "c": 84.3,
      "f": 12.0
    }
  },
  {
    "n": "Nando's Corn on the Cob (regular)",
    "k": 144,
    "p": 5.7,
    "c": 22.0,
    "f": 2.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 144,
      "p": 5.7,
      "c": 22.0,
      "f": 2.7
    }
  },
  {
    "n": "Nando's Corn on the Cob (large)",
    "k": 288,
    "p": 11.4,
    "c": 44.0,
    "f": 5.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 288,
      "p": 11.4,
      "c": 44.0,
      "f": 5.4
    }
  },
  {
    "n": "Nando's Rainbow Slaw (regular)",
    "k": 99,
    "p": 1.9,
    "c": 11.3,
    "f": 5.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 99,
      "p": 1.9,
      "c": 11.3,
      "f": 5.8
    }
  },
  {
    "n": "Nando's Rainbow Slaw (large)",
    "k": 177,
    "p": 2.9,
    "c": 21.7,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 177,
      "p": 2.9,
      "c": 21.7,
      "f": 10.0
    }
  },
  {
    "n": "Nando's Spiced Grains & Butternut Squash (regular)",
    "k": 232,
    "p": 8.4,
    "c": 20.5,
    "f": 11.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 232,
      "p": 8.4,
      "c": 20.5,
      "f": 11.4
    }
  },
  {
    "n": "Nando's Spiced Grains & Butternut Squash (large)",
    "k": 421,
    "p": 14.5,
    "c": 40.7,
    "f": 19.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 421,
      "p": 14.5,
      "c": 40.7,
      "f": 19.2
    }
  },
  {
    "n": "Nando's Creamy Mash (regular)",
    "k": 276,
    "p": 3.2,
    "c": 32.8,
    "f": 15.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 276,
      "p": 3.2,
      "c": 32.8,
      "f": 15.2
    }
  },
  {
    "n": "Nando's Creamy Mash (large)",
    "k": 552,
    "p": 6.4,
    "c": 65.6,
    "f": 30.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 552,
      "p": 6.4,
      "c": 65.6,
      "f": 30.4
    }
  },
  {
    "n": "Nando's Coleslaw (regular)",
    "k": 263,
    "p": 1.3,
    "c": 11.4,
    "f": 23.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 263,
      "p": 1.3,
      "c": 11.4,
      "f": 23.7
    }
  },
  {
    "n": "Nando's Coleslaw (large)",
    "k": 526,
    "p": 2.7,
    "c": 22.9,
    "f": 47.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 526,
      "p": 2.7,
      "c": 22.9,
      "f": 47.4
    }
  },
  {
    "n": "Nando's Macho Peas (regular)",
    "k": 141,
    "p": 7.7,
    "c": 17.5,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 141,
      "p": 7.7,
      "c": 17.5,
      "f": 6.4
    }
  },
  {
    "n": "Nando's Macho Peas (large)",
    "k": 283,
    "p": 15.4,
    "c": 35.0,
    "f": 12.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 283,
      "p": 15.4,
      "c": 35.0,
      "f": 12.9
    }
  },
  {
    "n": "Nando's Long Stem Broccoli (regular)",
    "k": 32,
    "p": 2.1,
    "c": 3.7,
    "f": 1.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 32,
      "p": 2.1,
      "c": 3.7,
      "f": 1.5
    }
  },
  {
    "n": "Nando's Long Stem Broccoli (large)",
    "k": 65,
    "p": 4.3,
    "c": 7.3,
    "f": 3.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 65,
      "p": 4.3,
      "c": 7.3,
      "f": 3.1
    }
  },
  {
    "n": "Nando's Mixed Leaf Salad (regular)",
    "k": 13,
    "p": 0.9,
    "c": 1.6,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 13,
      "p": 0.9,
      "c": 1.6,
      "f": 0.2
    }
  },
  {
    "n": "Nando's Mixed Leaf Salad (large)",
    "k": 27,
    "p": 1.8,
    "c": 3.2,
    "f": 0.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 27,
      "p": 1.8,
      "c": 3.2,
      "f": 0.4
    }
  },
  {
    "n": "Nando's Peri-Peri Chicken Gravy",
    "k": 54,
    "p": 3.2,
    "c": 4.5,
    "f": 2.4,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 54,
      "p": 3.2,
      "c": 4.5,
      "f": 2.4
    }
  },
  {
    "n": "Nando's Perinaise",
    "k": 159,
    "p": 0.3,
    "c": 7.0,
    "f": 14.3,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 159,
      "p": 0.3,
      "c": 7.0,
      "f": 14.3
    }
  },
  {
    "n": "Nando's Garlic Perinaise",
    "k": 176,
    "p": 4.2,
    "c": 4.4,
    "f": 15.8,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 176,
      "p": 4.2,
      "c": 4.4,
      "f": 15.8
    }
  },
  {
    "n": "Nando's Chilli Jam",
    "k": 164,
    "p": 0.5,
    "c": 40.7,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 164,
      "p": 0.5,
      "c": 40.7,
      "f": 0.1
    }
  },
  {
    "n": "Nando's Peri-BBQ",
    "k": 61,
    "p": 0.6,
    "c": 11.9,
    "f": 1.4,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 61,
      "p": 0.6,
      "c": 11.9,
      "f": 1.4
    }
  },
  {
    "n": "Nando's Mayonnaise",
    "k": 73,
    "p": 0.2,
    "c": 4.5,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 73,
      "p": 0.2,
      "c": 4.5,
      "f": 6.0
    }
  },
  {
    "n": "Nando's Perinaise Mild",
    "k": 46,
    "p": 0.0,
    "c": 2.0,
    "f": 4.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 46,
      "p": 0.0,
      "c": 2.0,
      "f": 4.2
    }
  },
  {
    "n": "Nando's Medium Peri-Peri Sauce",
    "k": 9,
    "p": 0.1,
    "c": 0.2,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 9,
      "p": 0.1,
      "c": 0.2,
      "f": 0.7
    }
  },
  {
    "n": "Nando's Garlic Peri-Peri Sauce",
    "k": 10,
    "p": 0.2,
    "c": 0.8,
    "f": 0.6,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 10,
      "p": 0.2,
      "c": 0.8,
      "f": 0.6
    }
  },
  {
    "n": "Nando's Lemon & Herb Peri-Peri Sauce",
    "k": 8,
    "p": 0.1,
    "c": 0.2,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 8,
      "p": 0.1,
      "c": 0.2,
      "f": 0.7
    }
  },
  {
    "n": "Nando's Hot Peri-Peri Sauce",
    "k": 9,
    "p": 0.2,
    "c": 0.5,
    "f": 0.6,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 9,
      "p": 0.2,
      "c": 0.5,
      "f": 0.6
    }
  },
  {
    "n": "Nando's Vusa Peri-Peri Sauce",
    "k": 35,
    "p": 0.4,
    "c": 1.0,
    "f": 3.1,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 35,
      "p": 0.4,
      "c": 1.0,
      "f": 3.1
    }
  },
  {
    "n": "Nando's Extra Hot Peri-Peri Sauce",
    "k": 9,
    "p": 0.3,
    "c": 1.1,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 9,
      "p": 0.3,
      "c": 1.1,
      "f": 0.2
    }
  },
  {
    "n": "Nando's Peri-Peri Drizzle",
    "k": 97,
    "p": 0.3,
    "c": 0.9,
    "f": 10.3,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 97,
      "p": 0.3,
      "c": 0.9,
      "f": 10.3
    }
  },
  {
    "n": "Nando's Houmous",
    "k": 202,
    "p": 6.7,
    "c": 13.6,
    "f": 13.4,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 202,
      "p": 6.7,
      "c": 13.6,
      "f": 13.4
    }
  },
  {
    "n": "Nando's Choc-A-Lot Cake",
    "k": 582,
    "p": 8.1,
    "c": 67.4,
    "f": 31.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 582,
      "p": 8.1,
      "c": 67.4,
      "f": 31.7
    }
  },
  {
    "n": "Nando's Gooey Caramel Cheesecake",
    "k": 415,
    "p": 7.8,
    "c": 38.9,
    "f": 25.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 415,
      "p": 7.8,
      "c": 38.9,
      "f": 25.3
    }
  },
  {
    "n": "Nando's Salted Caramel Brownie",
    "k": 389,
    "p": 4.2,
    "c": 42.9,
    "f": 21.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 389,
      "p": 4.2,
      "c": 42.9,
      "f": 21.7
    }
  },
  {
    "n": "Nando's Naughty Nata",
    "k": 169,
    "p": 2.8,
    "c": 22.6,
    "f": 7.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 169,
      "p": 2.8,
      "c": 22.6,
      "f": 7.2
    }
  },
  {
    "n": "Nando's Vanilla Gelado",
    "k": 161,
    "p": 2.5,
    "c": 19.5,
    "f": 8.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 161,
      "p": 2.5,
      "c": 19.5,
      "f": 8.3
    }
  },
  {
    "n": "Nando's Mango Gelado",
    "k": 99,
    "p": 0.4,
    "c": 24.0,
    "f": 0.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 99,
      "p": 0.4,
      "c": 24.0,
      "f": 0.4
    }
  },
  {
    "n": "Nando's Chocolate Gelado",
    "k": 145,
    "p": 1.6,
    "c": 18.0,
    "f": 7.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 145,
      "p": 1.6,
      "c": 18.0,
      "f": 7.5
    }
  },
  {
    "n": "Nando's Coconut Gelado",
    "k": 157,
    "p": 2.0,
    "c": 20.3,
    "f": 7.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 157,
      "p": 2.0,
      "c": 20.3,
      "f": 7.5
    }
  },
  {
    "n": "Nando's Irn-Bru",
    "k": 138,
    "p": 0.0,
    "c": 34.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 138,
      "p": 0.0,
      "c": 34.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottomless Coca-Cola",
    "k": 126,
    "p": 0.0,
    "c": 31.8,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 126,
      "p": 0.0,
      "c": 31.8,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottomless Coke Zero",
    "k": 2,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 2,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottomless Diet Coke",
    "k": 1,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 1,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottomless Fanta",
    "k": 57,
    "p": 0.0,
    "c": 13.5,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 57,
      "p": 0.0,
      "c": 13.5,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Bottomless Sprite Zero",
    "k": 3,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 3,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Coca-Cola",
    "k": 139,
    "p": 0.0,
    "c": 35.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 139,
      "p": 0.0,
      "c": 35.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Coke Zero",
    "k": 1,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 1,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Diet Coke",
    "k": 1,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 1,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Fanta",
    "k": 63,
    "p": 0.0,
    "c": 14.9,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 63,
      "p": 0.0,
      "c": 14.9,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Sprite Zero",
    "k": 3,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 3,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Karma Drinks Gingerella",
    "k": 105,
    "p": 0.0,
    "c": 24.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 105,
      "p": 0.0,
      "c": 24.0,
      "f": 0.0
    }
  },
  {
    "n": "Nando's REAL Kombucha Royal Flush",
    "k": 44,
    "p": 0.0,
    "c": 8.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 44,
      "p": 0.0,
      "c": 8.3,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Big Drop Brewing Co. Pale Ale",
    "k": 63,
    "p": 1.0,
    "c": 11.9,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 63,
      "p": 1.0,
      "c": 11.9,
      "f": 0.7
    }
  },
  {
    "n": "Nando's Sagres",
    "k": 129,
    "p": 0.7,
    "c": 10.2,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 129,
      "p": 0.7,
      "c": 10.2,
      "f": 0.3
    }
  },
  {
    "n": "Nando's Sxollie Cider",
    "k": 289,
    "p": 0.0,
    "c": 30.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 289,
      "p": 0.0,
      "c": 30.3,
      "f": 0.0
    }
  },
  {
    "n": "Nando's Freedom Pils",
    "k": 119,
    "p": 1.3,
    "c": 8.6,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 119,
      "p": 1.3,
      "c": 8.6,
      "f": 0.3
    }
  },
  {
    "n": "Nando's Five Points XPA",
    "k": 56,
    "p": 1.0,
    "c": 11.9,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 56,
      "p": 1.0,
      "c": 11.9,
      "f": 0.3
    }
  },
  {
    "n": "Nando's Organic Everyday Tea",
    "k": 23,
    "p": 1.7,
    "c": 2.3,
    "f": 0.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "nandos-uk",
    "ref": {
      "g": 1,
      "k": 23,
      "p": 1.7,
      "c": 2.3,
      "f": 0.8
    }
  }
]
