import type { Food } from '@/core/types'

/** PizzaExpress "ZA" menu, per item (slice, wrap or whole 14" pizza) as published; no weights given.
 *  GENERATED by scripts/import/pizzaexpress_za.py from PizzaExpress' ZA nutrition PDF: don't edit by hand. */
export const PIZZAEXPRESS_ZA: Food[] = [
  {
    "n": "PizzaExpress ZA Margherita slice",
    "k": 306.0,
    "p": 16.2,
    "c": 34.1,
    "f": 11.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 306.0,
      "p": 16.2,
      "c": 34.1,
      "f": 11.8
    }
  },
  {
    "n": "PizzaExpress ZA American slice",
    "k": 337.0,
    "p": 16.0,
    "c": 36.3,
    "f": 13.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 337.0,
      "p": 16.0,
      "c": 36.3,
      "f": 13.9
    }
  },
  {
    "n": "PizzaExpress ZA Pollo ad Astra slice",
    "k": 346.0,
    "p": 19.3,
    "c": 38.2,
    "f": 12.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 346.0,
      "p": 19.3,
      "c": 38.2,
      "f": 12.6
    }
  },
  {
    "n": "PizzaExpress ZA American Hot slice",
    "k": 333.0,
    "p": 15.8,
    "c": 35.5,
    "f": 13.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 333.0,
      "p": 15.8,
      "c": 35.5,
      "f": 13.8
    }
  },
  {
    "n": "PizzaExpress ZA Padana slice",
    "k": 280.0,
    "p": 8.7,
    "c": 42.1,
    "f": 8.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 280.0,
      "p": 8.7,
      "c": 42.1,
      "f": 8.2
    }
  },
  {
    "n": "PizzaExpress ZA La Reine slice",
    "k": 315.0,
    "p": 16.1,
    "c": 35.3,
    "f": 11.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 315.0,
      "p": 16.1,
      "c": 35.3,
      "f": 11.7
    }
  },
  {
    "n": "PizzaExpress ZA Cajun-spiced Chicken wrap",
    "k": 546.0,
    "p": 35.1,
    "c": 55.6,
    "f": 20.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 546.0,
      "p": 35.1,
      "c": 55.6,
      "f": 20.1
    }
  },
  {
    "n": "PizzaExpress ZA American Hot wrap",
    "k": 536.0,
    "p": 25.6,
    "c": 49.4,
    "f": 25.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 536.0,
      "p": 25.6,
      "c": 49.4,
      "f": 25.7
    }
  },
  {
    "n": "PizzaExpress ZA Goat’s Cheese & Caramelised Onion",
    "k": 587.0,
    "p": 24.3,
    "c": 66.2,
    "f": 24.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 587.0,
      "p": 24.3,
      "c": 66.2,
      "f": 24.4
    }
  },
  {
    "n": "PizzaExpress ZA Margherita 14\" pizza",
    "k": 1671.0,
    "p": 69.9,
    "c": 267.3,
    "f": 33.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 1671.0,
      "p": 69.9,
      "c": 267.3,
      "f": 33.2
    }
  },
  {
    "n": "PizzaExpress ZA American 14\" pizza",
    "k": 1818.0,
    "p": 77.2,
    "c": 267.5,
    "f": 46.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 1818.0,
      "p": 77.2,
      "c": 267.5,
      "f": 46.4
    }
  },
  {
    "n": "PizzaExpress ZA American Hot 14\" pizza",
    "k": 1812.0,
    "p": 76.4,
    "c": 268.1,
    "f": 45.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 1812.0,
      "p": 76.4,
      "c": 268.1,
      "f": 45.4
    }
  },
  {
    "n": "PizzaExpress ZA Padana 14\" pizza",
    "k": 1758.0,
    "p": 66.6,
    "c": 289.0,
    "f": 34.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 1758.0,
      "p": 66.6,
      "c": 289.0,
      "f": 34.1
    }
  },
  {
    "n": "PizzaExpress ZA La Reine 14\" pizza",
    "k": 1748.0,
    "p": 78.1,
    "c": 267.8,
    "f": 37.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzaexpress-za",
    "ref": {
      "g": 1,
      "k": 1748.0,
      "p": 78.1,
      "c": 267.8,
      "f": 37.9
    }
  }
]
