import type { Food } from '@/core/types'

/** Pizza Hut Restaurants UK (dine-in) menu: pizzas per slice as published (`each`); everything
 *  else per 100 g with `g` = Pizza Hut's own portion weight.
 *  GENERATED by scripts/import/pizzahut.py from Pizza Hut's dine-in booklet: don't edit by hand. */
export const PIZZAHUT: Food[] = [
  {
    "n": "Pizza Hut Fries",
    "k": 166.96,
    "p": 2.22,
    "c": 22.17,
    "f": 7.39,
    "g": 230.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 384.0,
      "p": 5.1,
      "c": 51.0,
      "f": 17.0
    }
  },
  {
    "n": "Pizza Hut Onion Rings",
    "k": 213.92,
    "p": 3.48,
    "c": 29.75,
    "f": 9.49,
    "g": 158.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 158.0,
      "k": 338.0,
      "p": 5.5,
      "c": 47.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Garlic Bread",
    "k": 300.0,
    "p": 7.5,
    "c": 39.17,
    "f": 11.67,
    "g": 120.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 120.0,
      "k": 360.0,
      "p": 9.0,
      "c": 47.0,
      "f": 14.0
    }
  },
  {
    "n": "Pizza Hut Garlic Bread with Cheese",
    "k": 292.82,
    "p": 11.05,
    "c": 27.07,
    "f": 14.92,
    "g": 181.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 181.0,
      "k": 530.0,
      "p": 20.0,
      "c": 49.0,
      "f": 27.0
    }
  },
  {
    "n": "Pizza Hut Halloumi Fries",
    "k": 323.53,
    "p": 16.47,
    "c": 12.94,
    "f": 23.53,
    "g": 85.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 85.0,
      "k": 275.0,
      "p": 14.0,
      "c": 11.0,
      "f": 20.0
    }
  },
  {
    "n": "Pizza Hut Cheesy Bite Bites",
    "k": 222.5,
    "p": 10.0,
    "c": 31.25,
    "f": 6.25,
    "g": 240.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 240.0,
      "k": 534.0,
      "p": 24.0,
      "c": 75.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Loaded Bacon Cheesy Bite Bites",
    "k": 239.39,
    "p": 11.45,
    "c": 25.93,
    "f": 9.76,
    "g": 297.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 297.0,
      "k": 711.0,
      "p": 34.0,
      "c": 77.0,
      "f": 29.0
    }
  },
  {
    "n": "Pizza Hut BBQ Chicken Wings",
    "k": 204.13,
    "p": 19.83,
    "c": 5.54,
    "f": 11.57,
    "g": 121.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 121.0,
      "k": 247.0,
      "p": 24.0,
      "c": 6.7,
      "f": 14.0
    }
  },
  {
    "n": "Pizza Hut Breaded Chicken Tenders",
    "k": 202.0,
    "p": 16.0,
    "c": 17.0,
    "f": 7.5,
    "g": 200.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 200.0,
      "k": 404.0,
      "p": 32.0,
      "c": 34.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Marinated Breaded Chicken Tenders",
    "k": 210.09,
    "p": 15.14,
    "c": 20.64,
    "f": 6.88,
    "g": 218.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 218.0,
      "k": 458.0,
      "p": 33.0,
      "c": 45.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Takeaway Macaroni Cheese",
    "k": 172.17,
    "p": 7.39,
    "c": 18.26,
    "f": 8.26,
    "g": 230.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 396.0,
      "p": 17.0,
      "c": 42.0,
      "f": 19.0
    }
  },
  {
    "n": "Pizza Hut Sour Cream Dip Pot",
    "k": 591.11,
    "p": 1.42,
    "c": 8.0,
    "f": 61.56,
    "g": 45.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 45.0,
      "k": 266.0,
      "p": 0.64,
      "c": 3.6,
      "f": 27.7
    }
  },
  {
    "n": "Pizza Hut Hot Honey Dip Pot (60ml)",
    "k": 329.07,
    "p": 0.5,
    "c": 81.98,
    "f": 0.5,
    "g": 86.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 86.0,
      "k": 283.0,
      "p": 0.43,
      "c": 70.5,
      "f": 0.43
    }
  },
  {
    "n": "Pizza Hut Sweet Chilli Dip Pot (50ml)",
    "k": 173.33,
    "p": 0.3,
    "c": 42.0,
    "f": 0.2,
    "g": 60.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 60.0,
      "k": 104.0,
      "p": 0.18,
      "c": 25.2,
      "f": 0.12
    }
  },
  {
    "n": "Pizza Hut Sweet Chilli Dip Pot (takeaway, 30ml)",
    "k": 182.86,
    "p": 0.4,
    "c": 42.86,
    "f": 1.2,
    "g": 35.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 35.0,
      "k": 64.0,
      "p": 0.14,
      "c": 15.0,
      "f": 0.42
    }
  },
  {
    "n": "Pizza Hut Garlic Buttermilk Mayo Pot (takeaway, 30ml)",
    "k": 365.71,
    "p": 0.71,
    "c": 13.71,
    "f": 34.29,
    "g": 35.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 35.0,
      "k": 128.0,
      "p": 0.25,
      "c": 4.8,
      "f": 12.0
    }
  },
  {
    "n": "Pizza Hut BBQ Dip Pot (takeaway, 30ml)",
    "k": 145.71,
    "p": 1.0,
    "c": 34.29,
    "f": 0.6,
    "g": 35.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 35.0,
      "k": 51.0,
      "p": 0.35,
      "c": 12.0,
      "f": 0.21
    }
  },
  {
    "n": "Pizza Hut Ketchup Pot (takeaway, 30ml)",
    "k": 111.43,
    "p": 1.31,
    "c": 25.43,
    "f": 0.11,
    "g": 35.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 35.0,
      "k": 39.0,
      "p": 0.46,
      "c": 8.9,
      "f": 0.04
    }
  },
  {
    "n": "Pizza Hut Potato Salad",
    "k": 161.9,
    "p": 1.27,
    "c": 14.44,
    "f": 10.63,
    "g": 63.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 63.0,
      "k": 102.0,
      "p": 0.8,
      "c": 9.1,
      "f": 6.7
    }
  },
  {
    "n": "Pizza Hut Coleslaw",
    "k": 136.0,
    "p": 0.8,
    "c": 6.2,
    "f": 11.8,
    "g": 50.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 50.0,
      "k": 68.0,
      "p": 0.4,
      "c": 3.1,
      "f": 5.9
    }
  },
  {
    "n": "Pizza Hut Sweetcorn",
    "k": 76.92,
    "p": 2.69,
    "c": 13.46,
    "f": 1.54,
    "g": 26.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 26.0,
      "k": 20.0,
      "p": 0.7,
      "c": 3.5,
      "f": 0.4
    }
  },
  {
    "n": "Pizza Hut Diced Beetroot",
    "k": 50.0,
    "p": 4.17,
    "c": 6.67,
    "f": 0.42,
    "g": 24.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 24.0,
      "k": 12.0,
      "p": 1.0,
      "c": 1.6,
      "f": 0.1
    }
  },
  {
    "n": "Pizza Hut Jalapenos",
    "k": 6.25,
    "p": 0.44,
    "c": 0.44,
    "f": 0.62,
    "g": 16.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 16.0,
      "k": 1.0,
      "p": 0.07,
      "c": 0.07,
      "f": 0.1
    }
  },
  {
    "n": "Pizza Hut Roquito® Chilli Peppers",
    "k": 87.5,
    "p": 0.69,
    "c": 20.88,
    "f": 0.0,
    "g": 16.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 16.0,
      "k": 14.0,
      "p": 0.11,
      "c": 3.34,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Black Olives",
    "k": 140.0,
    "p": 0.93,
    "c": 0.73,
    "f": 14.0,
    "g": 15.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 15.0,
      "k": 21.0,
      "p": 0.14,
      "c": 0.11,
      "f": 2.1
    }
  },
  {
    "n": "Pizza Hut Bacon Bits",
    "k": 538.46,
    "p": 9.23,
    "c": 59.23,
    "f": 29.23,
    "g": 13.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 13.0,
      "k": 70.0,
      "p": 1.2,
      "c": 7.7,
      "f": 3.8
    }
  },
  {
    "n": "Pizza Hut Croutons",
    "k": 471.43,
    "p": 11.0,
    "c": 71.43,
    "f": 15.71,
    "g": 7.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 7.0,
      "k": 33.0,
      "p": 0.77,
      "c": 5.0,
      "f": 1.1
    }
  },
  {
    "n": "Pizza Hut Tortilla Chips",
    "k": 492.31,
    "p": 6.15,
    "c": 63.08,
    "f": 20.77,
    "g": 13.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 13.0,
      "k": 64.0,
      "p": 0.8,
      "c": 8.2,
      "f": 2.7
    }
  },
  {
    "n": "Pizza Hut Crispy Onions",
    "k": 583.33,
    "p": 6.67,
    "c": 40.0,
    "f": 43.33,
    "g": 6.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 6.0,
      "k": 35.0,
      "p": 0.4,
      "c": 2.4,
      "f": 2.6
    }
  },
  {
    "n": "Pizza Hut Sultanas",
    "k": 268.75,
    "p": 2.5,
    "c": 68.75,
    "f": 0.0,
    "g": 16.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 16.0,
      "k": 43.0,
      "p": 0.4,
      "c": 11.0,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Thousand Island Dressing",
    "k": 266.67,
    "p": 0.7,
    "c": 11.33,
    "f": 24.0,
    "g": 30.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 30.0,
      "k": 80.0,
      "p": 0.21,
      "c": 3.4,
      "f": 7.2
    }
  },
  {
    "n": "Pizza Hut Blue Cheese Dressing",
    "k": 462.96,
    "p": 1.3,
    "c": 19.26,
    "f": 40.74,
    "g": 27.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 27.0,
      "k": 125.0,
      "p": 0.35,
      "c": 5.2,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut Garlic Mayonnaise",
    "k": 437.93,
    "p": 2.0,
    "c": 4.14,
    "f": 44.83,
    "g": 29.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 29.0,
      "k": 127.0,
      "p": 0.58,
      "c": 1.2,
      "f": 13.0
    }
  },
  {
    "n": "Pizza Hut Light Mayonnaise",
    "k": 405.88,
    "p": 0.71,
    "c": 12.65,
    "f": 38.24,
    "g": 34.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 34.0,
      "k": 138.0,
      "p": 0.24,
      "c": 4.3,
      "f": 13.0
    }
  },
  {
    "n": "Pizza Hut Ranch Dressing",
    "k": 467.74,
    "p": 2.39,
    "c": 6.45,
    "f": 48.39,
    "g": 31.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 31.0,
      "k": 145.0,
      "p": 0.74,
      "c": 2.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Low Fat French Dressing",
    "k": 81.82,
    "p": 0.82,
    "c": 14.09,
    "f": 2.73,
    "g": 22.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 22.0,
      "k": 18.0,
      "p": 0.18,
      "c": 3.1,
      "f": 0.6
    }
  },
  {
    "n": "Pizza Hut Salsa",
    "k": 60.61,
    "p": 1.09,
    "c": 13.03,
    "f": 0.0,
    "g": 33.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 33.0,
      "k": 20.0,
      "p": 0.36,
      "c": 4.3,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Sour Cream (salad bar)",
    "k": 590.0,
    "p": 1.43,
    "c": 8.0,
    "f": 60.0,
    "g": 30.0,
    "cat": "sauces",
    "src": "pizzahut-uk",
    "ref": {
      "g": 30.0,
      "k": 177.0,
      "p": 0.43,
      "c": 2.4,
      "f": 18.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Individual Pan (9\") slice",
    "k": 178.0,
    "p": 7.0,
    "c": 18.0,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 178.0,
      "p": 7.0,
      "c": 18.0,
      "f": 8.8
    }
  },
  {
    "n": "Pizza Hut Pepperoni Sharing Pan (13\") slice",
    "k": 263.0,
    "p": 10.3,
    "c": 28.0,
    "f": 12.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 263.0,
      "p": 10.3,
      "c": 28.0,
      "f": 12.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Individual Handcrafted (11\") slice",
    "k": 157.0,
    "p": 6.8,
    "c": 18.0,
    "f": 6.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 157.0,
      "p": 6.8,
      "c": 18.0,
      "f": 6.5
    }
  },
  {
    "n": "Pizza Hut Pepperoni Sharing Handcrafted (14\") slice",
    "k": 205.0,
    "p": 8.9,
    "c": 23.0,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 205.0,
      "p": 8.9,
      "c": 23.0,
      "f": 8.4
    }
  },
  {
    "n": "Pizza Hut Pepperoni Individual Stuffed Crust (11\") slice",
    "k": 240.0,
    "p": 11.0,
    "c": 24.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 240.0,
      "p": 11.0,
      "c": 24.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Sharing Stuffed Crust (14\") slice",
    "k": 298.0,
    "p": 14.0,
    "c": 30.0,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 298.0,
      "p": 14.0,
      "c": 30.0,
      "f": 13.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Cheesy Bites (14\") slice",
    "k": 298.0,
    "p": 14.0,
    "c": 30.0,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 298.0,
      "p": 14.0,
      "c": 30.0,
      "f": 13.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Gluten Free (9\" Square) slice",
    "k": 163.0,
    "p": 4.0,
    "c": 20.0,
    "f": 7.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 163.0,
      "p": 4.0,
      "c": 20.0,
      "f": 7.3
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Individual Pan (9\") slice",
    "k": 195.0,
    "p": 7.7,
    "c": 18.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 195.0,
      "p": 7.7,
      "c": 18.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Sharing Pan (13\") slice",
    "k": 288.0,
    "p": 11.0,
    "c": 28.0,
    "f": 15.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 288.0,
      "p": 11.0,
      "c": 28.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Individual Handcrafted (11\") slice",
    "k": 174.0,
    "p": 7.5,
    "c": 18.0,
    "f": 8.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 174.0,
      "p": 7.5,
      "c": 18.0,
      "f": 8.1
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Sharing Handcrafted (14\") slice",
    "k": 231.0,
    "p": 9.9,
    "c": 23.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 231.0,
      "p": 9.9,
      "c": 23.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Individual Stuffed Crust (11\") slice",
    "k": 257.0,
    "p": 12.0,
    "c": 24.0,
    "f": 12.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 257.0,
      "p": 12.0,
      "c": 24.0,
      "f": 12.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Sharing Stuffed Crust (14\") slice",
    "k": 324.0,
    "p": 15.0,
    "c": 30.0,
    "f": 16.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 324.0,
      "p": 15.0,
      "c": 30.0,
      "f": 16.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Cheesy Bites (14\") slice",
    "k": 324.0,
    "p": 15.0,
    "c": 30.0,
    "f": 16.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 324.0,
      "p": 15.0,
      "c": 30.0,
      "f": 16.0
    }
  },
  {
    "n": "Pizza Hut Pepperoni Feast Gluten Free (9\" Square) slice",
    "k": 180.0,
    "p": 5.1,
    "c": 20.0,
    "f": 8.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 180.0,
      "p": 5.1,
      "c": 20.0,
      "f": 8.9
    }
  },
  {
    "n": "Pizza Hut Hawaiian Individual Pan (9\") slice",
    "k": 166.0,
    "p": 7.6,
    "c": 19.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 166.0,
      "p": 7.6,
      "c": 19.0,
      "f": 6.4
    }
  },
  {
    "n": "Pizza Hut Hawaiian Sharing Pan (13\") slice",
    "k": 249.0,
    "p": 11.0,
    "c": 30.0,
    "f": 9.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 249.0,
      "p": 11.0,
      "c": 30.0,
      "f": 9.0
    }
  },
  {
    "n": "Pizza Hut Hawaiian Individual Handcrafted (11\") slice",
    "k": 158.0,
    "p": 7.6,
    "c": 21.0,
    "f": 4.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 158.0,
      "p": 7.6,
      "c": 21.0,
      "f": 4.6
    }
  },
  {
    "n": "Pizza Hut Hawaiian Sharing Handcrafted (14\") slice",
    "k": 211.0,
    "p": 10.0,
    "c": 28.0,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 211.0,
      "p": 10.0,
      "c": 28.0,
      "f": 6.0
    }
  },
  {
    "n": "Pizza Hut Hawaiian Individual Stuffed Crust (11\") slice",
    "k": 222.0,
    "p": 12.0,
    "c": 24.0,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 222.0,
      "p": 12.0,
      "c": 24.0,
      "f": 8.4
    }
  },
  {
    "n": "Pizza Hut Hawaiian Sharing Stuffed Crust (14\") slice",
    "k": 268.0,
    "p": 15.0,
    "c": 31.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 268.0,
      "p": 15.0,
      "c": 31.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Hawaiian Cheesy Bites (14\") slice",
    "k": 268.0,
    "p": 15.0,
    "c": 31.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 268.0,
      "p": 15.0,
      "c": 31.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Hawaiian Gluten Free (9\" Square) slice",
    "k": 149.0,
    "p": 4.9,
    "c": 20.0,
    "f": 4.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 149.0,
      "p": 4.9,
      "c": 20.0,
      "f": 4.8
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Individual Pan (9\") slice",
    "k": 168.0,
    "p": 8.7,
    "c": 19.0,
    "f": 6.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 168.0,
      "p": 8.7,
      "c": 19.0,
      "f": 6.3
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Sharing Pan (13\") slice",
    "k": 256.0,
    "p": 14.0,
    "c": 29.0,
    "f": 8.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 256.0,
      "p": 14.0,
      "c": 29.0,
      "f": 8.9
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Individual Handcrafted (11\") slice",
    "k": 148.0,
    "p": 8.4,
    "c": 19.0,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 148.0,
      "p": 8.4,
      "c": 19.0,
      "f": 4.1
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Sharing Handcrafted (14\") slice",
    "k": 197.0,
    "p": 12.0,
    "c": 24.0,
    "f": 5.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 197.0,
      "p": 12.0,
      "c": 24.0,
      "f": 5.2
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Individual Stuffed Crust (11\") slice",
    "k": 224.0,
    "p": 13.0,
    "c": 23.0,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 224.0,
      "p": 13.0,
      "c": 23.0,
      "f": 8.4
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Sharing Stuffed Crust (14\") slice",
    "k": 275.0,
    "p": 17.0,
    "c": 30.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 275.0,
      "p": 17.0,
      "c": 30.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Cheesy Bites (14\") slice",
    "k": 275.0,
    "p": 17.0,
    "c": 30.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 275.0,
      "p": 17.0,
      "c": 30.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Chicken Supreme Gluten Free (9\" Square) slice",
    "k": 151.0,
    "p": 6.0,
    "c": 20.0,
    "f": 4.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 151.0,
      "p": 6.0,
      "c": 20.0,
      "f": 4.7
    }
  },
  {
    "n": "Pizza Hut Meat Feast Individual Pan (9\") slice",
    "k": 194.0,
    "p": 9.1,
    "c": 18.0,
    "f": 9.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 194.0,
      "p": 9.1,
      "c": 18.0,
      "f": 9.3
    }
  },
  {
    "n": "Pizza Hut Meat Feast Sharing Pan (13\") slice",
    "k": 299.0,
    "p": 14.0,
    "c": 29.0,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 299.0,
      "p": 14.0,
      "c": 29.0,
      "f": 14.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Individual Handcrafted (11\") slice",
    "k": 173.0,
    "p": 8.9,
    "c": 18.0,
    "f": 7.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 173.0,
      "p": 8.9,
      "c": 18.0,
      "f": 7.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Sharing Handcrafted (14\") slice",
    "k": 241.0,
    "p": 13.0,
    "c": 24.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 241.0,
      "p": 13.0,
      "c": 24.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Individual Stuffed Crust (11\") slice",
    "k": 256.0,
    "p": 14.0,
    "c": 25.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 256.0,
      "p": 14.0,
      "c": 25.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Sharing Stuffed Crust (14\") slice",
    "k": 335.0,
    "p": 18.0,
    "c": 30.0,
    "f": 16.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 335.0,
      "p": 18.0,
      "c": 30.0,
      "f": 16.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Cheesy Bites (14\") slice",
    "k": 335.0,
    "p": 18.0,
    "c": 30.0,
    "f": 16.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 335.0,
      "p": 18.0,
      "c": 30.0,
      "f": 16.0
    }
  },
  {
    "n": "Pizza Hut Meat Feast Gluten Free (9\" Square) slice",
    "k": 179.0,
    "p": 6.5,
    "c": 20.0,
    "f": 7.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 179.0,
      "p": 6.5,
      "c": 20.0,
      "f": 7.8
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Individual Pan (9\") slice",
    "k": 191.0,
    "p": 9.4,
    "c": 21.0,
    "f": 7.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 191.0,
      "p": 9.4,
      "c": 21.0,
      "f": 7.5
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Sharing Pan (13\") slice",
    "k": 289.0,
    "p": 15.0,
    "c": 33.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 289.0,
      "p": 15.0,
      "c": 33.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Individual Handcrafted (11\") slice",
    "k": 168.0,
    "p": 9.6,
    "c": 21.0,
    "f": 4.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 168.0,
      "p": 9.6,
      "c": 21.0,
      "f": 4.8
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Sharing Handcrafted (14\") slice",
    "k": 233.0,
    "p": 14.0,
    "c": 28.0,
    "f": 6.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 233.0,
      "p": 14.0,
      "c": 28.0,
      "f": 6.6
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Individual Stuffed Crust (11\") slice",
    "k": 245.0,
    "p": 14.0,
    "c": 26.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 245.0,
      "p": 14.0,
      "c": 26.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Sharing Stuffed Crust (14\") slice",
    "k": 311.0,
    "p": 19.0,
    "c": 34.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 311.0,
      "p": 19.0,
      "c": 34.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Cheesy Bites (14\") slice",
    "k": 311.0,
    "p": 19.0,
    "c": 34.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 311.0,
      "p": 19.0,
      "c": 34.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut BBQ Americano Gluten Free (9\" Square) slice",
    "k": 175.0,
    "p": 6.6,
    "c": 23.0,
    "f": 5.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 175.0,
      "p": 6.6,
      "c": 23.0,
      "f": 5.9
    }
  },
  {
    "n": "Pizza Hut Margherita Individual Pan (9\") slice",
    "k": 169.0,
    "p": 7.0,
    "c": 18.0,
    "f": 7.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 169.0,
      "p": 7.0,
      "c": 18.0,
      "f": 7.4
    }
  },
  {
    "n": "Pizza Hut Margherita Sharing Pan (13\") slice",
    "k": 250.0,
    "p": 10.0,
    "c": 29.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 250.0,
      "p": 10.0,
      "c": 29.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Margherita Individual Handcrafted (11\") slice",
    "k": 149.0,
    "p": 6.8,
    "c": 18.0,
    "f": 5.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 149.0,
      "p": 6.8,
      "c": 18.0,
      "f": 5.1
    }
  },
  {
    "n": "Pizza Hut Margherita Sharing Handcrafted (14\") slice",
    "k": 191.0,
    "p": 8.7,
    "c": 24.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 191.0,
      "p": 8.7,
      "c": 24.0,
      "f": 6.4
    }
  },
  {
    "n": "Pizza Hut Margherita Individual Stuffed Crust (11\") slice",
    "k": 225.0,
    "p": 11.0,
    "c": 23.0,
    "f": 9.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 225.0,
      "p": 11.0,
      "c": 23.0,
      "f": 9.4
    }
  },
  {
    "n": "Pizza Hut Margherita Sharing Stuffed Crust (14\") slice",
    "k": 269.0,
    "p": 13.0,
    "c": 30.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 269.0,
      "p": 13.0,
      "c": 30.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Margherita Cheesy Bites (14\") slice",
    "k": 269.0,
    "p": 13.0,
    "c": 30.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 269.0,
      "p": 13.0,
      "c": 30.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Margherita Gluten Free (9\" Square) slice",
    "k": 114.0,
    "p": 3.2,
    "c": 15.0,
    "f": 4.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 114.0,
      "p": 3.2,
      "c": 15.0,
      "f": 4.3
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Individual Pan (9\") slice",
    "k": 162.0,
    "p": 6.2,
    "c": 19.0,
    "f": 6.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 162.0,
      "p": 6.2,
      "c": 19.0,
      "f": 6.8
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Sharing Pan (13\") slice",
    "k": 241.0,
    "p": 9.0,
    "c": 30.0,
    "f": 9.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 241.0,
      "p": 9.0,
      "c": 30.0,
      "f": 9.0
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Individual Handcrafted (11\") slice",
    "k": 142.0,
    "p": 5.9,
    "c": 19.0,
    "f": 4.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 142.0,
      "p": 5.9,
      "c": 19.0,
      "f": 4.5
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Sharing Handcrafted (14\") slice",
    "k": 182.0,
    "p": 8.0,
    "c": 25.0,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 182.0,
      "p": 8.0,
      "c": 25.0,
      "f": 6.0
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Individual Stuffed Crust (11\") slice",
    "k": 219.0,
    "p": 11.0,
    "c": 24.0,
    "f": 9.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 219.0,
      "p": 11.0,
      "c": 24.0,
      "f": 9.0
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Sharing Stuffed Crust (14\") slice",
    "k": 260.0,
    "p": 12.0,
    "c": 31.0,
    "f": 9.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 260.0,
      "p": 12.0,
      "c": 31.0,
      "f": 9.0
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Cheesy Bites (14\") slice",
    "k": 260.0,
    "p": 12.0,
    "c": 31.0,
    "f": 9.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 260.0,
      "p": 12.0,
      "c": 31.0,
      "f": 9.0
    }
  },
  {
    "n": "Pizza Hut Veggie Supreme Gluten Free (9\" Square) slice",
    "k": 145.0,
    "p": 3.4,
    "c": 20.0,
    "f": 5.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 145.0,
      "p": 3.4,
      "c": 20.0,
      "f": 5.2
    }
  },
  {
    "n": "Pizza Hut Farmhouse Individual Pan (9\") slice",
    "k": 162.0,
    "p": 7.6,
    "c": 18.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 162.0,
      "p": 7.6,
      "c": 18.0,
      "f": 6.4
    }
  },
  {
    "n": "Pizza Hut Farmhouse Sharing Pan (13\") slice",
    "k": 242.0,
    "p": 11.0,
    "c": 29.0,
    "f": 8.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 242.0,
      "p": 11.0,
      "c": 29.0,
      "f": 8.9
    }
  },
  {
    "n": "Pizza Hut Farmhouse Individual Handcrafted (11\") slice",
    "k": 142.0,
    "p": 7.4,
    "c": 18.0,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 142.0,
      "p": 7.4,
      "c": 18.0,
      "f": 4.1
    }
  },
  {
    "n": "Pizza Hut Farmhouse Sharing Handcrafted (14\") slice",
    "k": 183.0,
    "p": 9.6,
    "c": 24.0,
    "f": 5.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 183.0,
      "p": 9.6,
      "c": 24.0,
      "f": 5.2
    }
  },
  {
    "n": "Pizza Hut Farmhouse Individual Stuffed Crust (11\") slice",
    "k": 219.0,
    "p": 12.0,
    "c": 23.0,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 219.0,
      "p": 12.0,
      "c": 23.0,
      "f": 8.4
    }
  },
  {
    "n": "Pizza Hut Farmhouse Sharing Stuffed Crust (14\") slice",
    "k": 261.0,
    "p": 14.0,
    "c": 30.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 261.0,
      "p": 14.0,
      "c": 30.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Farmhouse Cheesy Bites (14\") slice",
    "k": 261.0,
    "p": 14.0,
    "c": 30.0,
    "f": 9.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 261.0,
      "p": 14.0,
      "c": 30.0,
      "f": 9.1
    }
  },
  {
    "n": "Pizza Hut Farmhouse Gluten Free (9\" Square) slice",
    "k": 145.0,
    "p": 4.9,
    "c": 20.0,
    "f": 4.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 145.0,
      "p": 4.9,
      "c": 20.0,
      "f": 4.8
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Individual Pan (9\") slice",
    "k": 178.0,
    "p": 7.7,
    "c": 19.0,
    "f": 7.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 178.0,
      "p": 7.7,
      "c": 19.0,
      "f": 7.6
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Sharing Pan (13\") slice",
    "k": 264.0,
    "p": 12.0,
    "c": 30.0,
    "f": 11.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 264.0,
      "p": 12.0,
      "c": 30.0,
      "f": 11.0
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Individual Handcrafted (11\") slice",
    "k": 157.0,
    "p": 7.6,
    "c": 19.0,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 157.0,
      "p": 7.6,
      "c": 19.0,
      "f": 5.3
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Sharing Handcrafted (14\") slice",
    "k": 206.0,
    "p": 10.4,
    "c": 25.0,
    "f": 6.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 206.0,
      "p": 10.4,
      "c": 25.0,
      "f": 6.8
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Individual Stuffed Crust (11\") slice",
    "k": 240.0,
    "p": 12.0,
    "c": 26.0,
    "f": 9.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 240.0,
      "p": 12.0,
      "c": 26.0,
      "f": 9.6
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Sharing Stuffed Crust (14\") slice",
    "k": 299.0,
    "p": 16.0,
    "c": 31.0,
    "f": 11.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 299.0,
      "p": 16.0,
      "c": 31.0,
      "f": 11.9
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Cheesy Bites (14\") slice",
    "k": 299.0,
    "p": 16.0,
    "c": 31.0,
    "f": 11.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 299.0,
      "p": 16.0,
      "c": 31.0,
      "f": 11.9
    }
  },
  {
    "n": "Pizza Hut Hot Honey Sriracha Chicken & Pepperoni Gluten Free (9\" Square) slice",
    "k": 163.0,
    "p": 5.1,
    "c": 21.0,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 163.0,
      "p": 5.1,
      "c": 21.0,
      "f": 6.0
    }
  },
  {
    "n": "Pizza Hut Vegan Margherita Individual Pan (9\") slice",
    "k": 163.0,
    "p": 4.0,
    "c": 20.0,
    "f": 7.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 163.0,
      "p": 4.0,
      "c": 20.0,
      "f": 7.1
    }
  },
  {
    "n": "Pizza Hut Vegan Margherita Sharing Pan (13\") slice",
    "k": 231.0,
    "p": 6.3,
    "c": 31.0,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 231.0,
      "p": 6.3,
      "c": 31.0,
      "f": 8.8
    }
  },
  {
    "n": "Pizza Hut Vegan Margherita Individual Handcrafted (11\") slice",
    "k": 140.0,
    "p": 3.7,
    "c": 20.0,
    "f": 4.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 140.0,
      "p": 3.7,
      "c": 20.0,
      "f": 4.7
    }
  },
  {
    "n": "Pizza Hut Vegan Margherita Sharing Handcrafted (14\") slice",
    "k": 169.0,
    "p": 4.8,
    "c": 25.0,
    "f": 5.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 169.0,
      "p": 4.8,
      "c": 25.0,
      "f": 5.0
    }
  },
  {
    "n": "Pizza Hut Vegan Margherita Gluten Free (9\" Square) slice",
    "k": 146.0,
    "p": 1.3,
    "c": 22.0,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 146.0,
      "p": 1.3,
      "c": 22.0,
      "f": 5.5
    }
  },
  {
    "n": "Pizza Hut Vegan Veggie Supreme Individual Pan (9\") slice",
    "k": 157.0,
    "p": 4.2,
    "c": 20.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 157.0,
      "p": 4.2,
      "c": 20.0,
      "f": 6.4
    }
  },
  {
    "n": "Pizza Hut Vegan Veggie Supreme Sharing Pan (13\") slice",
    "k": 240.0,
    "p": 6.7,
    "c": 32.0,
    "f": 9.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 240.0,
      "p": 6.7,
      "c": 32.0,
      "f": 9.2
    }
  },
  {
    "n": "Pizza Hut Vegan Veggie Supreme Individual Handcrafted (11\") slice",
    "k": 134.0,
    "p": 3.9,
    "c": 20.0,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 134.0,
      "p": 3.9,
      "c": 20.0,
      "f": 4.1
    }
  },
  {
    "n": "Pizza Hut Vegan Veggie Supreme Sharing Handcrafted (14\") slice",
    "k": 178.0,
    "p": 5.1,
    "c": 27.0,
    "f": 5.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 178.0,
      "p": 5.1,
      "c": 27.0,
      "f": 5.4
    }
  },
  {
    "n": "Pizza Hut Vegan Veggie Supreme Gluten Free (9\" Square) slice",
    "k": 140.0,
    "p": 1.5,
    "c": 22.0,
    "f": 4.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 140.0,
      "p": 1.5,
      "c": 22.0,
      "f": 4.8
    }
  },
  {
    "n": "Pizza Hut Chicken Delight Flatbread",
    "k": 172.66,
    "p": 9.34,
    "c": 20.76,
    "f": 6.57,
    "g": 289.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 289.0,
      "k": 499.0,
      "p": 27.0,
      "c": 60.0,
      "f": 19.0
    }
  },
  {
    "n": "Pizza Hut Virtuous Veg Flatbread",
    "k": 145.85,
    "p": 6.64,
    "c": 19.93,
    "f": 3.99,
    "g": 301.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 301.0,
      "k": 439.0,
      "p": 20.0,
      "c": 60.0,
      "f": 12.0
    }
  },
  {
    "n": "Pizza Hut Vegan Virtuous Veg Flatbread",
    "k": 138.75,
    "p": 4.5,
    "c": 22.49,
    "f": 3.08,
    "g": 289.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 289.0,
      "k": 401.0,
      "p": 13.0,
      "c": 65.0,
      "f": 8.9
    }
  },
  {
    "n": "Pizza Hut Lasagne",
    "k": 132.69,
    "p": 6.97,
    "c": 10.34,
    "f": 6.97,
    "g": 416.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 416.0,
      "k": 552.0,
      "p": 29.0,
      "c": 43.0,
      "f": 29.0
    }
  },
  {
    "n": "Pizza Hut Classic Mac 'N' Cheese",
    "k": 176.3,
    "p": 8.26,
    "c": 18.7,
    "f": 8.26,
    "g": 460.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 460.0,
      "k": 811.0,
      "p": 38.0,
      "c": 86.0,
      "f": 38.0
    }
  },
  {
    "n": "Pizza Hut Buffet Veggie Individual Pan (9\") slice",
    "k": 162.0,
    "p": 6.4,
    "c": 19.0,
    "f": 6.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 162.0,
      "p": 6.4,
      "c": 19.0,
      "f": 6.3
    }
  },
  {
    "n": "Pizza Hut Buffet Veggie Sharing Pan (13\") slice",
    "k": 275.0,
    "p": 10.7,
    "c": 35.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 275.0,
      "p": 10.7,
      "c": 35.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Buffet Veggie Individual Handcrafted (11\") slice",
    "k": 141.0,
    "p": 6.1,
    "c": 19.0,
    "f": 4.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 141.0,
      "p": 6.1,
      "c": 19.0,
      "f": 4.0
    }
  },
  {
    "n": "Pizza Hut Buffet Spicy Chicken Individual Pan (9\") slice",
    "k": 161.0,
    "p": 7.2,
    "c": 19.0,
    "f": 6.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 161.0,
      "p": 7.2,
      "c": 19.0,
      "f": 6.3
    }
  },
  {
    "n": "Pizza Hut Buffet Spicy Chicken Sharing Pan (13\") slice",
    "k": 242.0,
    "p": 10.8,
    "c": 29.0,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 242.0,
      "p": 10.8,
      "c": 29.0,
      "f": 8.8
    }
  },
  {
    "n": "Pizza Hut Buffet Spicy Chicken Individual Handcrafted (11\") slice",
    "k": 142.0,
    "p": 7.2,
    "c": 20.0,
    "f": 3.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 142.0,
      "p": 7.2,
      "c": 20.0,
      "f": 3.6
    }
  },
  {
    "n": "Pizza Hut Buffet BBQ Beef & Onion Individual Pan (9\") slice",
    "k": 172.0,
    "p": 6.7,
    "c": 20.0,
    "f": 7.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 172.0,
      "p": 6.7,
      "c": 20.0,
      "f": 7.1
    }
  },
  {
    "n": "Pizza Hut Buffet BBQ Beef & Onion Sharing Pan (13\") slice",
    "k": 258.0,
    "p": 10.0,
    "c": 31.0,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 258.0,
      "p": 10.0,
      "c": 31.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Buffet BBQ Beef & Onion Individual Handcrafted (11\") slice",
    "k": 147.0,
    "p": 6.6,
    "c": 19.0,
    "f": 4.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 147.0,
      "p": 6.6,
      "c": 19.0,
      "f": 4.8
    }
  },
  {
    "n": "Pizza Hut Buffet Chicken Fajita Individual Pan (9\") slice",
    "k": 216.0,
    "p": 8.6,
    "c": 20.0,
    "f": 11.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 216.0,
      "p": 8.6,
      "c": 20.0,
      "f": 11.1
    }
  },
  {
    "n": "Pizza Hut Buffet Chicken Fajita Sharing Pan (13\") slice",
    "k": 316.0,
    "p": 13.0,
    "c": 32.0,
    "f": 15.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 316.0,
      "p": 13.0,
      "c": 32.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Buffet Chicken Fajita Individual Handcrafted (11\") slice",
    "k": 196.0,
    "p": 8.4,
    "c": 20.0,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 196.0,
      "p": 8.4,
      "c": 20.0,
      "f": 8.8
    }
  },
  {
    "n": "Pizza Hut Buffet Creamy Garlic Individual Pan (9\") slice",
    "k": 208.0,
    "p": 9.0,
    "c": 19.0,
    "f": 10.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 208.0,
      "p": 9.0,
      "c": 19.0,
      "f": 10.6
    }
  },
  {
    "n": "Pizza Hut Buffet Creamy Garlic Sharing Pan (13\") slice",
    "k": 301.0,
    "p": 12.0,
    "c": 30.0,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 301.0,
      "p": 12.0,
      "c": 30.0,
      "f": 14.0
    }
  },
  {
    "n": "Pizza Hut Buffet Creamy Garlic Individual Handcrafted (11\") slice",
    "k": 186.0,
    "p": 8.0,
    "c": 19.0,
    "f": 8.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 186.0,
      "p": 8.0,
      "c": 19.0,
      "f": 8.2
    }
  },
  {
    "n": "Pizza Hut Buffet Garlic Chicken & Mushrooms Individual Pan (9\") slice",
    "k": 194.0,
    "p": 8.0,
    "c": 19.0,
    "f": 9.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 194.0,
      "p": 8.0,
      "c": 19.0,
      "f": 9.2
    }
  },
  {
    "n": "Pizza Hut Buffet Garlic Chicken & Mushrooms Sharing Pan (13\") slice",
    "k": 288.0,
    "p": 13.0,
    "c": 30.0,
    "f": 13.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 288.0,
      "p": 13.0,
      "c": 30.0,
      "f": 13.0
    }
  },
  {
    "n": "Pizza Hut Buffet Garlic Chicken & Mushrooms Individual Handcrafted (11\") slice",
    "k": 173.0,
    "p": 8.0,
    "c": 19.0,
    "f": 6.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 1,
      "k": 173.0,
      "p": 8.0,
      "c": 19.0,
      "f": 6.8
    }
  },
  {
    "n": "Pizza Hut Buffet Tomato Sauce Pasta",
    "k": 94.0,
    "p": 3.8,
    "c": 18.0,
    "f": 0.83,
    "g": 100,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 100.0,
      "k": 94.0,
      "p": 3.8,
      "c": 18.0,
      "f": 0.83
    }
  },
  {
    "n": "Pizza Hut Garlic Breadstick (large)",
    "k": 283.58,
    "p": 8.46,
    "c": 37.81,
    "f": 10.45,
    "g": 20.1,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 20.1,
      "k": 57.0,
      "p": 1.7,
      "c": 7.6,
      "f": 2.1
    }
  },
  {
    "n": "Pizza Hut Garlic Breadstick (small)",
    "k": 274.19,
    "p": 9.14,
    "c": 39.25,
    "f": 8.6,
    "g": 18.6,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 18.6,
      "k": 51.0,
      "p": 1.7,
      "c": 7.3,
      "f": 1.6
    }
  },
  {
    "n": "Pizza Hut Cheesy Garlic Breadstick (large)",
    "k": 303.92,
    "p": 12.09,
    "c": 26.14,
    "f": 16.67,
    "g": 30.6,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 30.6,
      "k": 93.0,
      "p": 3.7,
      "c": 8.0,
      "f": 5.1
    }
  },
  {
    "n": "Pizza Hut Cheesy Garlic Breadstick (small)",
    "k": 294.55,
    "p": 11.64,
    "c": 27.64,
    "f": 15.27,
    "g": 27.5,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 27.5,
      "k": 81.0,
      "p": 3.2,
      "c": 7.6,
      "f": 4.2
    }
  },
  {
    "n": "Pizza Hut Ice Cream Factory Ice Cream",
    "k": 117.0,
    "p": 3.3,
    "c": 14.0,
    "f": 5.1,
    "g": 100,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 100.0,
      "k": 117.0,
      "p": 3.3,
      "c": 14.0,
      "f": 5.1
    }
  },
  {
    "n": "Pizza Hut White Chocolate & Caramel Cookie Dough",
    "k": 310.71,
    "p": 3.42,
    "c": 45.41,
    "f": 12.76,
    "g": 196.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 196.0,
      "k": 609.0,
      "p": 6.7,
      "c": 89.0,
      "f": 25.0
    }
  },
  {
    "n": "Pizza Hut Chocolate Chip Cookie Dough",
    "k": 320.41,
    "p": 4.03,
    "c": 44.9,
    "f": 13.78,
    "g": 196.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 196.0,
      "k": 628.0,
      "p": 7.9,
      "c": 88.0,
      "f": 27.0
    }
  },
  {
    "n": "Pizza Hut White Chocolate & Caramel Cookie Dough (takeaway)",
    "k": 334.86,
    "p": 3.89,
    "c": 47.43,
    "f": 14.29,
    "g": 175.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 175.0,
      "k": 586.0,
      "p": 6.8,
      "c": 83.0,
      "f": 25.0
    }
  },
  {
    "n": "Pizza Hut Chocolate Chip Cookie Dough (takeaway)",
    "k": 345.14,
    "p": 4.51,
    "c": 46.86,
    "f": 15.43,
    "g": 175.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 175.0,
      "k": 604.0,
      "p": 7.9,
      "c": 82.0,
      "f": 27.0
    }
  },
  {
    "n": "Pizza Hut I Can't Believe Its Not Cheesecake",
    "k": 437.38,
    "p": 2.71,
    "c": 44.86,
    "f": 28.04,
    "g": 107.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 107.0,
      "k": 468.0,
      "p": 2.9,
      "c": 48.0,
      "f": 30.0
    }
  },
  {
    "n": "Pizza Hut Hot Chocolate Brownie with Ice Cream & Sauce",
    "k": 326.98,
    "p": 4.18,
    "c": 38.1,
    "f": 16.93,
    "g": 189.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 189.0,
      "k": 618.0,
      "p": 7.9,
      "c": 72.0,
      "f": 32.0
    }
  },
  {
    "n": "Pizza Hut Hot Chocolate Brownie with Ice Cream & Sauce (takeaway)",
    "k": 354.17,
    "p": 4.7,
    "c": 39.29,
    "f": 19.64,
    "g": 168.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 168.0,
      "k": 595.0,
      "p": 7.9,
      "c": 66.0,
      "f": 33.0
    }
  },
  {
    "n": "Pizza Hut Mini Donuts with Chocolate Sauce",
    "k": 365.65,
    "p": 3.82,
    "c": 54.96,
    "f": 14.5,
    "g": 131.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 131.0,
      "k": 479.0,
      "p": 5.0,
      "c": 72.0,
      "f": 19.0
    }
  },
  {
    "n": "Pizza Hut Mini Donuts with Chocolate Sauce (takeaway)",
    "k": 396.09,
    "p": 4.77,
    "c": 51.56,
    "f": 18.75,
    "g": 128.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 128.0,
      "k": 507.0,
      "p": 6.1,
      "c": 66.0,
      "f": 24.0
    }
  },
  {
    "n": "Pizza Hut Vanilla Ice Cream Tub (100ml) (takeaway)",
    "k": 168.89,
    "p": 2.89,
    "c": 21.78,
    "f": 7.78,
    "g": 45.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 45.0,
      "k": 76.0,
      "p": 1.3,
      "c": 9.8,
      "f": 3.5
    }
  },
  {
    "n": "Pizza Hut Vanilla Ice Cream Scoop",
    "k": 163.95,
    "p": 2.91,
    "c": 22.09,
    "f": 7.56,
    "g": 86.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 86.0,
      "k": 141.0,
      "p": 2.5,
      "c": 19.0,
      "f": 6.5
    }
  },
  {
    "n": "Pizza Hut Kids Pan Pizza Margherita",
    "k": 217.48,
    "p": 9.71,
    "c": 27.67,
    "f": 7.28,
    "g": 206.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 206.0,
      "k": 448.0,
      "p": 20.0,
      "c": 57.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Kids Thin Pizza Margherita",
    "k": 217.48,
    "p": 9.71,
    "c": 27.67,
    "f": 7.28,
    "g": 206.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 206.0,
      "k": 448.0,
      "p": 20.0,
      "c": 57.0,
      "f": 15.0
    }
  },
  {
    "n": "Pizza Hut Kids Gluten Free Margherita",
    "k": 217.68,
    "p": 7.73,
    "c": 23.76,
    "f": 9.39,
    "g": 181.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 181.0,
      "k": 394.0,
      "p": 14.0,
      "c": 43.0,
      "f": 17.0
    }
  },
  {
    "n": "Pizza Hut Kids Chicken 'N' Fries",
    "k": 171.74,
    "p": 9.13,
    "c": 16.09,
    "f": 7.39,
    "g": 230.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 395.0,
      "p": 21.0,
      "c": 37.0,
      "f": 17.0
    }
  },
  {
    "n": "Pizza Hut Kids Mac 'N' Cheese",
    "k": 176.52,
    "p": 8.26,
    "c": 18.7,
    "f": 8.26,
    "g": 230.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 406.0,
      "p": 19.0,
      "c": 43.0,
      "f": 19.0
    }
  },
  {
    "n": "Pizza Hut Kids Spaghetti Bolognese",
    "k": 79.2,
    "p": 5.2,
    "c": 11.2,
    "f": 1.32,
    "g": 250.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 250.0,
      "k": 198.0,
      "p": 13.0,
      "c": 28.0,
      "f": 3.3
    }
  },
  {
    "n": "Pizza Hut Kids Fries",
    "k": 167.2,
    "p": 2.24,
    "c": 22.4,
    "f": 7.44,
    "g": 125.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 125.0,
      "k": 209.0,
      "p": 2.8,
      "c": 28.0,
      "f": 9.3
    }
  },
  {
    "n": "Pizza Hut Kids Garlic Bread",
    "k": 300.0,
    "p": 7.5,
    "c": 38.33,
    "f": 12.0,
    "g": 60.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 60.0,
      "k": 180.0,
      "p": 4.5,
      "c": 23.0,
      "f": 7.2
    }
  },
  {
    "n": "Pizza Hut Kids Onion Rings",
    "k": 213.92,
    "p": 3.54,
    "c": 29.11,
    "f": 9.37,
    "g": 79.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 79.0,
      "k": 169.0,
      "p": 2.8,
      "c": 23.0,
      "f": 7.4
    }
  },
  {
    "n": "Pizza Hut Kids Semi Skimmed Milk",
    "k": 44.89,
    "p": 3.51,
    "c": 4.44,
    "f": 1.51,
    "g": 225.0,
    "cat": "drinks",
    "src": "pizzahut-uk",
    "ref": {
      "g": 225.0,
      "k": 101.0,
      "p": 7.9,
      "c": 10.0,
      "f": 3.4
    }
  },
  {
    "n": "Pizza Hut Kids Orange Juice",
    "k": 40.87,
    "p": 0.7,
    "c": 9.13,
    "f": 0.0,
    "g": 230.0,
    "cat": "drinks",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 94.0,
      "p": 1.6,
      "c": 21.0,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Kids Apple Juice",
    "k": 45.22,
    "p": 0.0,
    "c": 10.87,
    "f": 0.0,
    "g": 230.0,
    "cat": "drinks",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 104.0,
      "p": 0.0,
      "c": 25.0,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Kids Robinsons Squash - Orange",
    "k": 0.87,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 230.0,
    "cat": "drinks",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Kids Robinsons Squash - Apple & Blackcurrant",
    "k": 2.17,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 230.0,
    "cat": "drinks",
    "src": "pizzahut-uk",
    "ref": {
      "g": 230.0,
      "k": 5.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Pizza Hut Kids Chocolate Brownie",
    "k": 278.62,
    "p": 3.72,
    "c": 34.48,
    "f": 13.79,
    "g": 145.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 145.0,
      "k": 404.0,
      "p": 5.4,
      "c": 50.0,
      "f": 20.0
    }
  },
  {
    "n": "Pizza Hut Kids Mini Donuts with Chocolate Sauce",
    "k": 340.66,
    "p": 2.97,
    "c": 57.14,
    "f": 10.99,
    "g": 91.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 91.0,
      "k": 310.0,
      "p": 2.7,
      "c": 52.0,
      "f": 10.0
    }
  },
  {
    "n": "Pizza Hut Kids Mini Donuts with Raspberry Sauce",
    "k": 323.08,
    "p": 2.53,
    "c": 56.04,
    "f": 9.89,
    "g": 91.0,
    "cat": "fastfood",
    "src": "pizzahut-uk",
    "ref": {
      "g": 91.0,
      "k": 294.0,
      "p": 2.3,
      "c": 51.0,
      "f": 9.0
    }
  }
]
