import type { Food } from '@/core/types'

/** Popeyes UK menu, per item as Popeyes publishes it (no portion weights given).
 *  GENERATED by scripts/import/popeyes.py from popeyesuk.com/nutrition: don't edit by hand. */
export const POPEYES: Food[] = [
  {
    "n": "Popeyes Hot Honey Boneless (10 pieces)",
    "k": 548.0,
    "p": 45.6,
    "c": 57.3,
    "f": 14.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 548.0,
      "p": 45.6,
      "c": 57.3,
      "f": 14.7
    }
  },
  {
    "n": "Popeyes Boneless Plain (4 pieces)",
    "k": 145.0,
    "p": 18.2,
    "c": 4.9,
    "f": 5.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 145.0,
      "p": 18.2,
      "c": 4.9,
      "f": 5.8
    }
  },
  {
    "n": "Popeyes Cajun Citrus Boneless (4 pieces)",
    "k": 152.0,
    "p": 18.3,
    "c": 6.4,
    "f": 5.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 152.0,
      "p": 18.3,
      "c": 6.4,
      "f": 5.9
    }
  },
  {
    "n": "Popeyes Garlic Parmesan Boneless (4 pieces)",
    "k": 316.0,
    "p": 19.8,
    "c": 8.0,
    "f": 22.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 316.0,
      "p": 19.8,
      "c": 8.0,
      "f": 22.6
    }
  },
  {
    "n": "Popeyes Ghost Pepper Boneless (4 pieces)",
    "k": 152.0,
    "p": 18.4,
    "c": 6.1,
    "f": 5.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 152.0,
      "p": 18.4,
      "c": 6.1,
      "f": 5.9
    }
  },
  {
    "n": "Popeyes Honey BBQ Boneless (4 pieces)",
    "k": 212.0,
    "p": 18.6,
    "c": 18.2,
    "f": 7.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 212.0,
      "p": 18.6,
      "c": 18.2,
      "f": 7.0
    }
  },
  {
    "n": "Popeyes Bacon Egg and Cheese Muffin",
    "k": 399.0,
    "p": 20.6,
    "c": 26.6,
    "f": 22.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 399.0,
      "p": 20.6,
      "c": 26.6,
      "f": 22.9
    }
  },
  {
    "n": "Popeyes Bacon Roll - Plain",
    "k": 346.0,
    "p": 18.7,
    "c": 29.4,
    "f": 16.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 346.0,
      "p": 18.7,
      "c": 29.4,
      "f": 16.5
    }
  },
  {
    "n": "Popeyes Bacon Roll with Cajun Ketchup",
    "k": 365.0,
    "p": 18.8,
    "c": 33.3,
    "f": 16.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 365.0,
      "p": 18.8,
      "c": 33.3,
      "f": 16.8
    }
  },
  {
    "n": "Popeyes Bacon Roll with Heinz Ketchup",
    "k": 356.0,
    "p": 18.8,
    "c": 31.8,
    "f": 16.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 356.0,
      "p": 18.8,
      "c": 31.8,
      "f": 16.5
    }
  },
  {
    "n": "Popeyes Bacon Roll with HP Sauce",
    "k": 358.0,
    "p": 18.8,
    "c": 32.2,
    "f": 16.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 358.0,
      "p": 18.8,
      "c": 32.2,
      "f": 16.5
    }
  },
  {
    "n": "Popeyes Big Breakfast Roll with Chicken Breakfast Patty & Heinz Ketchup",
    "k": 404.0,
    "p": 23.3,
    "c": 36.0,
    "f": 18.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 404.0,
      "p": 23.3,
      "c": 36.0,
      "f": 18.1
    }
  },
  {
    "n": "Popeyes Big Breakfast Roll with Chicken Breakfast Patty & HP Sauce",
    "k": 406.0,
    "p": 23.3,
    "c": 36.4,
    "f": 18.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 406.0,
      "p": 23.3,
      "c": 36.4,
      "f": 18.2
    }
  },
  {
    "n": "Popeyes Big Breakfast Roll with Chicken Breakfast Patty, Streaky Bacon & Heinz Ketchup",
    "k": 460.0,
    "p": 26.9,
    "c": 36.0,
    "f": 22.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 460.0,
      "p": 26.9,
      "c": 36.0,
      "f": 22.7
    }
  },
  {
    "n": "Popeyes Big Breakfast Roll with Chicken Breakfast Patty, Streaky Bacon & HP Sauce",
    "k": 462.0,
    "p": 26.8,
    "c": 36.4,
    "f": 22.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 462.0,
      "p": 26.8,
      "c": 36.4,
      "f": 22.7
    }
  },
  {
    "n": "Popeyes Big Breakfast Wrap with Chicken Breakfast Patty & Heinz Ketchup",
    "k": 703.0,
    "p": 31.5,
    "c": 50.3,
    "f": 41.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 703.0,
      "p": 31.5,
      "c": 50.3,
      "f": 41.1
    }
  },
  {
    "n": "Popeyes Big Breakfast Wrap with Chicken Breakfast Patty, Streaky Bacon & Heinz Ketchup",
    "k": 764.0,
    "p": 35.1,
    "c": 51.5,
    "f": 45.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 764.0,
      "p": 35.1,
      "c": 51.5,
      "f": 45.7
    }
  },
  {
    "n": "Popeyes Big Breakfast Wrap with Chicken Breakfast Patty, Streaky Bacon & HP Sauce",
    "k": 767.0,
    "p": 35.1,
    "c": 52.2,
    "f": 45.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 767.0,
      "p": 35.1,
      "c": 52.2,
      "f": 45.8
    }
  },
  {
    "n": "Popeyes Big Cajun Roll with Chicken Breakfast Patty",
    "k": 439.0,
    "p": 23.7,
    "c": 38.8,
    "f": 20.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 439.0,
      "p": 23.7,
      "c": 38.8,
      "f": 20.5
    }
  },
  {
    "n": "Popeyes Big Cajun Roll with Chicken Breakfast Patty & Streaky Bacon",
    "k": 715.0,
    "p": 29.5,
    "c": 56.1,
    "f": 40.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 715.0,
      "p": 29.5,
      "c": 56.1,
      "f": 40.2
    }
  },
  {
    "n": "Popeyes Big Cajun Wrap with Chicken Breakfast Patty",
    "k": 517.0,
    "p": 29.9,
    "c": 37.7,
    "f": 27.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 517.0,
      "p": 29.9,
      "c": 37.7,
      "f": 27.3
    }
  },
  {
    "n": "Popeyes Big Cajun Wrap with Chicken Breakfast Patty & Streaky Bacon",
    "k": 786.0,
    "p": 35.5,
    "c": 55.1,
    "f": 46.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 786.0,
      "p": 35.5,
      "c": 55.1,
      "f": 46.3
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty & Cajun Ketchup",
    "k": 313.0,
    "p": 13.4,
    "c": 36.7,
    "f": 11.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 313.0,
      "p": 13.4,
      "c": 36.7,
      "f": 11.9
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty & Heinz Ketchup",
    "k": 304.0,
    "p": 13.5,
    "c": 35.1,
    "f": 11.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 304.0,
      "p": 13.5,
      "c": 35.1,
      "f": 11.7
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty & HP Sauce",
    "k": 306.0,
    "p": 13.4,
    "c": 35.6,
    "f": 11.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 306.0,
      "p": 13.4,
      "c": 35.6,
      "f": 11.7
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty, Streaky Bacon & Cajun Ketchup",
    "k": 388.0,
    "p": 18.2,
    "c": 36.7,
    "f": 18.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 388.0,
      "p": 18.2,
      "c": 36.7,
      "f": 18.0
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty, Streaky Bacon & Heinz Ketchup",
    "k": 379.0,
    "p": 18.2,
    "c": 35.1,
    "f": 17.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 379.0,
      "p": 18.2,
      "c": 35.1,
      "f": 17.8
    }
  },
  {
    "n": "Popeyes Breakfast Roll with Chicken Breakfast Patty, Streaky Bacon & HP Sauce",
    "k": 381.0,
    "p": 18.2,
    "c": 35.6,
    "f": 17.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 381.0,
      "p": 18.2,
      "c": 35.6,
      "f": 17.8
    }
  },
  {
    "n": "Popeyes Cajun Hash Brown",
    "k": 115.0,
    "p": 1.6,
    "c": 12.0,
    "f": 6.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 115.0,
      "p": 1.6,
      "c": 12.0,
      "f": 6.4
    }
  },
  {
    "n": "Popeyes Chicken Breakfast Patty, Egg & Cheese Muffin",
    "k": 440.0,
    "p": 24.0,
    "c": 30.0,
    "f": 24.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 440.0,
      "p": 24.0,
      "c": 30.0,
      "f": 24.6
    }
  },
  {
    "n": "Popeyes Double Bacon, Egg and Cheese Muffin",
    "k": 464.0,
    "p": 24.8,
    "c": 26.6,
    "f": 28.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 464.0,
      "p": 24.8,
      "c": 26.6,
      "f": 28.2
    }
  },
  {
    "n": "Popeyes Double Chicken Breakfast Patty, Egg & Cheese Muffin",
    "k": 511.0,
    "p": 31.5,
    "c": 33.4,
    "f": 27.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 511.0,
      "p": 31.5,
      "c": 33.4,
      "f": 27.6
    }
  },
  {
    "n": "Popeyes Double Sausage, Egg & Cheese Roll",
    "k": 510.0,
    "p": 30.7,
    "c": 37.0,
    "f": 26.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 510.0,
      "p": 30.7,
      "c": 37.0,
      "f": 26.1
    }
  },
  {
    "n": "Popeyes Double Sausage, Egg & Cheese Roll with Brown Sauce",
    "k": 522.0,
    "p": 30.8,
    "c": 39.8,
    "f": 26.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 522.0,
      "p": 30.8,
      "c": 39.8,
      "f": 26.2
    }
  },
  {
    "n": "Popeyes Double Sausage, Egg & Cheese Roll with Ketchup",
    "k": 520.0,
    "p": 30.8,
    "c": 39.4,
    "f": 26.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 520.0,
      "p": 30.8,
      "c": 39.4,
      "f": 26.1
    }
  },
  {
    "n": "Popeyes Egg & Cheese Roll",
    "k": 314.0,
    "p": 15.7,
    "c": 30.2,
    "f": 14.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 314.0,
      "p": 15.7,
      "c": 30.2,
      "f": 14.1
    }
  },
  {
    "n": "Popeyes Egg and Cheese Muffin",
    "k": 333.0,
    "p": 16.5,
    "c": 26.6,
    "f": 17.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 333.0,
      "p": 16.5,
      "c": 26.6,
      "f": 17.6
    }
  },
  {
    "n": "Popeyes Hash Brown",
    "k": 106.0,
    "p": 1.2,
    "c": 10.7,
    "f": 6.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 106.0,
      "p": 1.2,
      "c": 10.7,
      "f": 6.2
    }
  },
  {
    "n": "Popeyes Bold BBQ Dip",
    "k": 71.0,
    "p": 0.3,
    "c": 17.4,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 71.0,
      "p": 0.3,
      "c": 17.4,
      "f": 0.2
    }
  },
  {
    "n": "Popeyes Buffalo Dip",
    "k": 8.0,
    "p": 0.1,
    "c": 0.5,
    "f": 0.6,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 8.0,
      "p": 0.1,
      "c": 0.5,
      "f": 0.6
    }
  },
  {
    "n": "Popeyes Classic Mayonnaise Dip",
    "k": 219.0,
    "p": 0.5,
    "c": 2.0,
    "f": 23.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 219.0,
      "p": 0.5,
      "c": 2.0,
      "f": 23.2
    }
  },
  {
    "n": "Popeyes Garlic Mayo Dip",
    "k": 218.0,
    "p": 0.5,
    "c": 1.9,
    "f": 23.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 218.0,
      "p": 0.5,
      "c": 1.9,
      "f": 23.2
    }
  },
  {
    "n": "Popeyes Ghost Pepper Big Dip",
    "k": 274.0,
    "p": 0.8,
    "c": 64.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 274.0,
      "p": 0.8,
      "c": 64.5,
      "f": 0.5
    }
  },
  {
    "n": "Popeyes Hot Honey Dip",
    "k": 68.0,
    "p": 0.1,
    "c": 16.6,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 68.0,
      "p": 0.1,
      "c": 16.6,
      "f": 0.2
    }
  },
  {
    "n": "Popeyes Kickback Dip Pot",
    "k": 198.0,
    "p": 0.5,
    "c": 2.5,
    "f": 20.7,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 198.0,
      "p": 0.5,
      "c": 2.5,
      "f": 20.7
    }
  },
  {
    "n": "Popeyes Louisiana Hot Dip",
    "k": 8.0,
    "p": 0.2,
    "c": 1.5,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 8.0,
      "p": 0.2,
      "c": 1.5,
      "f": 0.2
    }
  },
  {
    "n": "Popeyes Mango Habanero Dip",
    "k": 52.0,
    "p": 0.1,
    "c": 12.4,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 52.0,
      "p": 0.1,
      "c": 12.4,
      "f": 0.1
    }
  },
  {
    "n": "Popeyes Ranch Dip",
    "k": 185.0,
    "p": 0.2,
    "c": 2.2,
    "f": 19.4,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 185.0,
      "p": 0.2,
      "c": 2.2,
      "f": 19.4
    }
  },
  {
    "n": "Popeyes The Big Cheese Dip",
    "k": 187.0,
    "p": 9.0,
    "c": 13.0,
    "f": 10.9,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 187.0,
      "p": 9.0,
      "c": 13.0,
      "f": 10.9
    }
  },
  {
    "n": "Popeyes The Big Honey BBQ Dip",
    "k": 287.0,
    "p": 1.7,
    "c": 56.4,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 287.0,
      "p": 1.7,
      "c": 56.4,
      "f": 5.3
    }
  },
  {
    "n": "Popeyes The Big Kickback Dip",
    "k": 809.0,
    "p": 2.3,
    "c": 13.5,
    "f": 82.5,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 809.0,
      "p": 2.3,
      "c": 13.5,
      "f": 82.5
    }
  },
  {
    "n": "Popeyes The Big Ranch Dip",
    "k": 794.0,
    "p": 0.8,
    "c": 9.5,
    "f": 83.1,
    "g": 1,
    "each": true,
    "cat": "sauces",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 794.0,
      "p": 0.8,
      "c": 9.5,
      "f": 83.1
    }
  },
  {
    "n": "Popeyes Black Americano",
    "k": 0.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 0.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Cappuccino",
    "k": 81.0,
    "p": 5.6,
    "c": 8.3,
    "f": 2.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 81.0,
      "p": 5.6,
      "c": 8.3,
      "f": 2.8
    }
  },
  {
    "n": "Popeyes Caramel Latte",
    "k": 151.0,
    "p": 8.1,
    "c": 20.5,
    "f": 4.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 151.0,
      "p": 8.1,
      "c": 20.5,
      "f": 4.0
    }
  },
  {
    "n": "Popeyes Chocolate Shake",
    "k": 557.0,
    "p": 16.2,
    "c": 80.0,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 557.0,
      "p": 16.2,
      "c": 80.0,
      "f": 8.8
    }
  },
  {
    "n": "Popeyes Flat White",
    "k": 55.0,
    "p": 3.8,
    "c": 5.6,
    "f": 1.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 55.0,
      "p": 3.8,
      "c": 5.6,
      "f": 1.9
    }
  },
  {
    "n": "Popeyes Jimmy's Iced Coffee",
    "k": 98.0,
    "p": 5.5,
    "c": 12.3,
    "f": 2.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 98.0,
      "p": 5.5,
      "c": 12.3,
      "f": 2.8
    }
  },
  {
    "n": "Popeyes Kids Chocolate Shake",
    "k": 364.0,
    "p": 10.5,
    "c": 52.7,
    "f": 5.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 364.0,
      "p": 10.5,
      "c": 52.7,
      "f": 5.7
    }
  },
  {
    "n": "Popeyes Kids Strawberry Shake",
    "k": 353.0,
    "p": 10.3,
    "c": 50.5,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 353.0,
      "p": 10.3,
      "c": 50.5,
      "f": 5.5
    }
  },
  {
    "n": "Popeyes Kids Vanilla Shake",
    "k": 286.0,
    "p": 10.3,
    "c": 34.5,
    "f": 5.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 286.0,
      "p": 10.3,
      "c": 34.5,
      "f": 5.5
    }
  },
  {
    "n": "Popeyes Chocolate Shake (large)",
    "k": 741.0,
    "p": 22.3,
    "c": 104.0,
    "f": 12.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 741.0,
      "p": 22.3,
      "c": 104.0,
      "f": 12.1
    }
  },
  {
    "n": "Popeyes Lotus Biscoff Shake (large)",
    "k": 758.0,
    "p": 23.0,
    "c": 91.0,
    "f": 19.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 758.0,
      "p": 23.0,
      "c": 91.0,
      "f": 19.9
    }
  },
  {
    "n": "Popeyes Oreo Shake (large)",
    "k": 841.0,
    "p": 23.4,
    "c": 118.7,
    "f": 16.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 841.0,
      "p": 23.4,
      "c": 118.7,
      "f": 16.1
    }
  },
  {
    "n": "Popeyes Strawberry Shake (large)",
    "k": 726.0,
    "p": 21.9,
    "c": 101.6,
    "f": 11.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 726.0,
      "p": 21.9,
      "c": 101.6,
      "f": 11.6
    }
  },
  {
    "n": "Popeyes Vanilla Shake (large)",
    "k": 608.0,
    "p": 21.8,
    "c": 73.3,
    "f": 11.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 608.0,
      "p": 21.8,
      "c": 73.3,
      "f": 11.6
    }
  },
  {
    "n": "Popeyes Latte",
    "k": 116.0,
    "p": 8.1,
    "c": 11.9,
    "f": 4.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 116.0,
      "p": 8.1,
      "c": 11.9,
      "f": 4.0
    }
  },
  {
    "n": "Popeyes Lemonade",
    "k": 139.0,
    "p": 0.3,
    "c": 35.1,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 139.0,
      "p": 0.3,
      "c": 35.1,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Lotus Biscoff Shake",
    "k": 548.0,
    "p": 16.6,
    "c": 65.6,
    "f": 14.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 548.0,
      "p": 16.6,
      "c": 65.6,
      "f": 14.4
    }
  },
  {
    "n": "Popeyes Oasis Summer Fruits",
    "k": 85.0,
    "p": 0.0,
    "c": 19.3,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 85.0,
      "p": 0.0,
      "c": 19.3,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Oreo Shake",
    "k": 698.0,
    "p": 17.2,
    "c": 106.9,
    "f": 11.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 698.0,
      "p": 17.2,
      "c": 106.9,
      "f": 11.9
    }
  },
  {
    "n": "Popeyes Peach Lemonade",
    "k": 139.0,
    "p": 0.3,
    "c": 35.1,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 139.0,
      "p": 0.3,
      "c": 35.1,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Red Bull Citrus Zest",
    "k": 119.0,
    "p": 0.0,
    "c": 28.4,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 119.0,
      "p": 0.0,
      "c": 28.4,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Strawberry Lemonade",
    "k": 167.0,
    "p": 0.3,
    "c": 42.1,
    "f": 0.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 167.0,
      "p": 0.3,
      "c": 42.1,
      "f": 0.0
    }
  },
  {
    "n": "Popeyes Strawberry Shake",
    "k": 524.0,
    "p": 15.9,
    "c": 73.2,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 524.0,
      "p": 15.9,
      "c": 73.2,
      "f": 8.4
    }
  },
  {
    "n": "Popeyes Tea",
    "k": 3.0,
    "p": 0.2,
    "c": 0.3,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 3.0,
      "p": 0.2,
      "c": 0.3,
      "f": 0.1
    }
  },
  {
    "n": "Popeyes Vanilla Shake",
    "k": 439.0,
    "p": 15.8,
    "c": 53.0,
    "f": 8.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 439.0,
      "p": 15.8,
      "c": 53.0,
      "f": 8.4
    }
  },
  {
    "n": "Popeyes White Americano",
    "k": 3.0,
    "p": 0.2,
    "c": 0.3,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 3.0,
      "p": 0.2,
      "c": 0.3,
      "f": 0.1
    }
  },
  {
    "n": "Popeyes Hot Wings (2 pieces)",
    "k": 185.0,
    "p": 19.0,
    "c": 3.3,
    "f": 10.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 185.0,
      "p": 19.0,
      "c": 3.3,
      "f": 10.6
    }
  },
  {
    "n": "Popeyes Cajun Citrus Hot Wings (6 pieces)",
    "k": 562.0,
    "p": 57.2,
    "c": 11.4,
    "f": 31.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 562.0,
      "p": 57.2,
      "c": 11.4,
      "f": 31.8
    }
  },
  {
    "n": "Popeyes Garlic Parmesan Hot Wings (6 pieces)",
    "k": 940.0,
    "p": 60.7,
    "c": 17.0,
    "f": 69.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 940.0,
      "p": 60.7,
      "c": 17.0,
      "f": 69.6
    }
  },
  {
    "n": "Popeyes Ghost Pepper Hot Wings (6 pieces)",
    "k": 561.0,
    "p": 57.2,
    "c": 11.2,
    "f": 31.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 561.0,
      "p": 57.2,
      "c": 11.2,
      "f": 31.8
    }
  },
  {
    "n": "Popeyes Honey BBQ Hot Wings (6 pieces)",
    "k": 707.0,
    "p": 57.9,
    "c": 39.9,
    "f": 34.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 707.0,
      "p": 57.9,
      "c": 39.9,
      "f": 34.5
    }
  },
  {
    "n": "Popeyes Chicken Sandwich Classic",
    "k": 528.0,
    "p": 36.6,
    "c": 35.0,
    "f": 26.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 528.0,
      "p": 36.6,
      "c": 35.0,
      "f": 26.3
    }
  },
  {
    "n": "Popeyes Classic Deluxe Chicken Sandwich",
    "k": 608.0,
    "p": 41.3,
    "c": 36.8,
    "f": 32.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 608.0,
      "p": 41.3,
      "c": 36.8,
      "f": 32.2
    }
  },
  {
    "n": "Popeyes Ghost Pepper Sandwich",
    "k": 525.0,
    "p": 36.7,
    "c": 38.4,
    "f": 24.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 525.0,
      "p": 36.7,
      "c": 38.4,
      "f": 24.2
    }
  },
  {
    "n": "Popeyes Ghost Pepper Superstack Sandwich",
    "k": 734.0,
    "p": 41.9,
    "c": 52.0,
    "f": 38.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 734.0,
      "p": 41.9,
      "c": 52.0,
      "f": 38.6
    }
  },
  {
    "n": "Popeyes Hot Honey Sandwich",
    "k": 517.0,
    "p": 40.6,
    "c": 47.8,
    "f": 17.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 517.0,
      "p": 40.6,
      "c": 47.8,
      "f": 17.4
    }
  },
  {
    "n": "Popeyes Hot Honey Superstack Sandwich",
    "k": 708.0,
    "p": 42.2,
    "c": 61.2,
    "f": 31.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 708.0,
      "p": 42.2,
      "c": 61.2,
      "f": 31.5
    }
  },
  {
    "n": "Popeyes Kids Sandwich Ketchup",
    "k": 183.0,
    "p": 13.8,
    "c": 21.0,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 183.0,
      "p": 13.8,
      "c": 21.0,
      "f": 4.1
    }
  },
  {
    "n": "Popeyes Kids Sandwich Mayo",
    "k": 222.0,
    "p": 13.8,
    "c": 19.2,
    "f": 9.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 222.0,
      "p": 13.8,
      "c": 19.2,
      "f": 9.3
    }
  },
  {
    "n": "Popeyes Kids Sandwich Plain",
    "k": 173.0,
    "p": 13.7,
    "c": 18.7,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 173.0,
      "p": 13.7,
      "c": 18.7,
      "f": 4.1
    }
  },
  {
    "n": "Popeyes Red Bean Creole Vegan Sandwich",
    "k": 545.0,
    "p": 13.8,
    "c": 47.1,
    "f": 34.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 545.0,
      "p": 13.8,
      "c": 47.1,
      "f": 34.1
    }
  },
  {
    "n": "Popeyes Spicy Chicken Sandwich",
    "k": 529.0,
    "p": 36.7,
    "c": 35.2,
    "f": 26.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 529.0,
      "p": 36.7,
      "c": 35.2,
      "f": 26.2
    }
  },
  {
    "n": "Popeyes Spicy Deluxe Chicken Sandwich",
    "k": 610.0,
    "p": 41.3,
    "c": 37.1,
    "f": 32.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 610.0,
      "p": 41.3,
      "c": 37.1,
      "f": 32.1
    }
  },
  {
    "n": "Popeyes Spicy Superstack Sandwich",
    "k": 781.0,
    "p": 40.6,
    "c": 53.2,
    "f": 44.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 781.0,
      "p": 40.6,
      "c": 53.2,
      "f": 44.0
    }
  },
  {
    "n": "Popeyes Superstack Classic Chicken Sandwich",
    "k": 788.0,
    "p": 42.4,
    "c": 48.9,
    "f": 45.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 788.0,
      "p": 42.4,
      "c": 48.9,
      "f": 45.9
    }
  },
  {
    "n": "Popeyes Superstack Classic Deluxe Sandwich",
    "k": 799.0,
    "p": 42.9,
    "c": 50.2,
    "f": 46.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 799.0,
      "p": 42.9,
      "c": 50.2,
      "f": 46.2
    }
  },
  {
    "n": "Popeyes Superstack Spicy Chicken Sandwich",
    "k": 790.0,
    "p": 42.4,
    "c": 49.2,
    "f": 45.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 790.0,
      "p": 42.4,
      "c": 49.2,
      "f": 45.9
    }
  },
  {
    "n": "Popeyes Superstack Spicy Deluxe Sandwich",
    "k": 801.0,
    "p": 42.9,
    "c": 50.5,
    "f": 46.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 801.0,
      "p": 42.9,
      "c": 50.5,
      "f": 46.2
    }
  },
  {
    "n": "Popeyes The Chicken Cruncher",
    "k": 268.0,
    "p": 16.0,
    "c": 27.3,
    "f": 10.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 268.0,
      "p": 16.0,
      "c": 27.3,
      "f": 10.3
    }
  },
  {
    "n": "Popeyes The Double Stack",
    "k": 876.0,
    "p": 64.2,
    "c": 51.7,
    "f": 45.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 876.0,
      "p": 64.2,
      "c": 51.7,
      "f": 45.2
    }
  },
  {
    "n": "Popeyes The Mini Sandwich",
    "k": 275.0,
    "p": 17.5,
    "c": 25.5,
    "f": 11.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 275.0,
      "p": 17.5,
      "c": 25.5,
      "f": 11.2
    }
  },
  {
    "n": "Popeyes The Spicy Double Stack",
    "k": 878.0,
    "p": 64.2,
    "c": 52.0,
    "f": 45.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 878.0,
      "p": 64.2,
      "c": 52.0,
      "f": 45.2
    }
  },
  {
    "n": "Popeyes The Spicy Mini Sandwich",
    "k": 276.0,
    "p": 17.5,
    "c": 25.6,
    "f": 11.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 276.0,
      "p": 17.5,
      "c": 25.6,
      "f": 11.2
    }
  },
  {
    "n": "Popeyes Biscuit",
    "k": 217.0,
    "p": 5.8,
    "c": 22.9,
    "f": 10.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 217.0,
      "p": 5.8,
      "c": 22.9,
      "f": 10.8
    }
  },
  {
    "n": "Popeyes Biscuit & Gravy",
    "k": 274.0,
    "p": 6.8,
    "c": 33.7,
    "f": 11.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 274.0,
      "p": 6.8,
      "c": 33.7,
      "f": 11.9
    }
  },
  {
    "n": "Popeyes Biscuit & Honey",
    "k": 308.0,
    "p": 5.9,
    "c": 38.9,
    "f": 13.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 308.0,
      "p": 5.9,
      "c": 38.9,
      "f": 13.8
    }
  },
  {
    "n": "Popeyes Biscuit & Hot Honey",
    "k": 311.0,
    "p": 5.9,
    "c": 39.4,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 311.0,
      "p": 5.9,
      "c": 39.4,
      "f": 14.0
    }
  },
  {
    "n": "Popeyes Biscuit & Nutella",
    "k": 324.0,
    "p": 6.7,
    "c": 31.5,
    "f": 18.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 324.0,
      "p": 6.7,
      "c": 31.5,
      "f": 18.5
    }
  },
  {
    "n": "Popeyes Cajun Fries (large)",
    "k": 428.0,
    "p": 7.2,
    "c": 50.2,
    "f": 20.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 428.0,
      "p": 7.2,
      "c": 50.2,
      "f": 20.5
    }
  },
  {
    "n": "Popeyes Cajun Fries (regular)",
    "k": 337.0,
    "p": 5.5,
    "c": 39.4,
    "f": 16.3,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 337.0,
      "p": 5.5,
      "c": 39.4,
      "f": 16.3
    }
  },
  {
    "n": "Popeyes Cajun Gravy",
    "k": 57.0,
    "p": 1.0,
    "c": 10.9,
    "f": 1.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 57.0,
      "p": 1.0,
      "c": 10.9,
      "f": 1.0
    }
  },
  {
    "n": "Popeyes Cheesy Fries",
    "k": 628.0,
    "p": 12.0,
    "c": 69.6,
    "f": 31.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 628.0,
      "p": 12.0,
      "c": 69.6,
      "f": 31.5
    }
  },
  {
    "n": "Popeyes Double Chocolate Cookie",
    "k": 411.0,
    "p": 4.9,
    "c": 50.2,
    "f": 20.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 411.0,
      "p": 4.9,
      "c": 50.2,
      "f": 20.7
    }
  },
  {
    "n": "Popeyes Fries (large)",
    "k": 410.0,
    "p": 6.4,
    "c": 47.6,
    "f": 20.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 410.0,
      "p": 6.4,
      "c": 47.6,
      "f": 20.1
    }
  },
  {
    "n": "Popeyes Fries (regular)",
    "k": 328.0,
    "p": 5.1,
    "c": 38.1,
    "f": 16.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 328.0,
      "p": 5.1,
      "c": 38.1,
      "f": 16.1
    }
  },
  {
    "n": "Popeyes Fries (small)",
    "k": 285.0,
    "p": 4.4,
    "c": 33.2,
    "f": 14.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 285.0,
      "p": 4.4,
      "c": 33.2,
      "f": 14.0
    }
  },
  {
    "n": "Popeyes Honey BBQ Cheesy Loaded Fries",
    "k": 672.0,
    "p": 10.4,
    "c": 87.0,
    "f": 33.4,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 672.0,
      "p": 10.4,
      "c": 87.0,
      "f": 33.4
    }
  },
  {
    "n": "Popeyes Kids Side Salad",
    "k": 10.0,
    "p": 0.4,
    "c": 1.3,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 10.0,
      "p": 0.4,
      "c": 1.3,
      "f": 0.2
    }
  },
  {
    "n": "Popeyes Mac & Cheese",
    "k": 245.0,
    "p": 11.0,
    "c": 27.9,
    "f": 8.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 245.0,
      "p": 11.0,
      "c": 27.9,
      "f": 8.8
    }
  },
  {
    "n": "Popeyes Mash & Gravy",
    "k": 429.0,
    "p": 3.4,
    "c": 34.9,
    "f": 30.8,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 429.0,
      "p": 3.4,
      "c": 34.9,
      "f": 30.8
    }
  },
  {
    "n": "Popeyes Milk Chocolate Cookie",
    "k": 417.0,
    "p": 4.9,
    "c": 50.2,
    "f": 21.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 417.0,
      "p": 4.9,
      "c": 50.2,
      "f": 21.5
    }
  },
  {
    "n": "Popeyes Smoky Beans",
    "k": 136.0,
    "p": 5.1,
    "c": 21.0,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 136.0,
      "p": 5.1,
      "c": 21.0,
      "f": 4.1
    }
  },
  {
    "n": "Popeyes Signature Louisiana Chicken piece",
    "k": 237.0,
    "p": 35.0,
    "c": 1.3,
    "f": 9.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 237.0,
      "p": 35.0,
      "c": 1.3,
      "f": 9.9
    }
  },
  {
    "n": "Popeyes Classic Chicken Wrap",
    "k": 436.0,
    "p": 28.1,
    "c": 35.1,
    "f": 20.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 436.0,
      "p": 28.1,
      "c": 35.1,
      "f": 20.2
    }
  },
  {
    "n": "Popeyes Spicy Chicken Wrap",
    "k": 437.0,
    "p": 28.1,
    "c": 35.3,
    "f": 20.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 437.0,
      "p": 28.1,
      "c": 35.3,
      "f": 20.1
    }
  },
  {
    "n": "Popeyes Classic Tender",
    "k": 75.0,
    "p": 11.5,
    "c": 1.5,
    "f": 2.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 75.0,
      "p": 11.5,
      "c": 1.5,
      "f": 2.7
    }
  },
  {
    "n": "Popeyes Spicy Tender",
    "k": 76.0,
    "p": 11.7,
    "c": 1.3,
    "f": 2.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 76.0,
      "p": 11.7,
      "c": 1.3,
      "f": 2.7
    }
  },
  {
    "n": "Popeyes Biscoff Whipz",
    "k": 351.0,
    "p": 6.2,
    "c": 36.7,
    "f": 19.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 351.0,
      "p": 6.2,
      "c": 36.7,
      "f": 19.6
    }
  },
  {
    "n": "Popeyes Chocolate Whipz",
    "k": 222.0,
    "p": 5.3,
    "c": 28.7,
    "f": 8.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 222.0,
      "p": 5.3,
      "c": 28.7,
      "f": 8.9
    }
  },
  {
    "n": "Popeyes M&Ms Whipz",
    "k": 288.0,
    "p": 6.0,
    "c": 38.0,
    "f": 11.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 288.0,
      "p": 6.0,
      "c": 38.0,
      "f": 11.7
    }
  },
  {
    "n": "Popeyes Mini Whipz - Biscoff",
    "k": 186.0,
    "p": 3.5,
    "c": 19.7,
    "f": 10.2,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 186.0,
      "p": 3.5,
      "c": 19.7,
      "f": 10.2
    }
  },
  {
    "n": "Popeyes Mini Whipz - Chocolate",
    "k": 124.0,
    "p": 3.0,
    "c": 15.6,
    "f": 5.1,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 124.0,
      "p": 3.0,
      "c": 15.6,
      "f": 5.1
    }
  },
  {
    "n": "Popeyes Mini Whipz - M&Ms",
    "k": 157.0,
    "p": 3.4,
    "c": 20.3,
    "f": 6.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 157.0,
      "p": 3.4,
      "c": 20.3,
      "f": 6.5
    }
  },
  {
    "n": "Popeyes Mini Whipz - Mud Pie",
    "k": 219.0,
    "p": 3.9,
    "c": 26.7,
    "f": 10.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 219.0,
      "p": 3.9,
      "c": 26.7,
      "f": 10.0
    }
  },
  {
    "n": "Popeyes Mini Whipz - Oreo",
    "k": 157.0,
    "p": 3.4,
    "c": 20.4,
    "f": 6.5,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 157.0,
      "p": 3.4,
      "c": 20.4,
      "f": 6.5
    }
  },
  {
    "n": "Popeyes Mini Whipz - Strawberry",
    "k": 125.0,
    "p": 2.9,
    "c": 16.8,
    "f": 5.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 125.0,
      "p": 2.9,
      "c": 16.8,
      "f": 5.0
    }
  },
  {
    "n": "Popeyes Mini Whipz - Vanilla",
    "k": 105.0,
    "p": 2.9,
    "c": 11.9,
    "f": 5.0,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 105.0,
      "p": 2.9,
      "c": 11.9,
      "f": 5.0
    }
  },
  {
    "n": "Popeyes Mud Pie Whipz",
    "k": 374.0,
    "p": 6.7,
    "c": 48.0,
    "f": 15.9,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 374.0,
      "p": 6.7,
      "c": 48.0,
      "f": 15.9
    }
  },
  {
    "n": "Popeyes Oreo Whipz",
    "k": 288.0,
    "p": 6.0,
    "c": 38.2,
    "f": 11.7,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 288.0,
      "p": 6.0,
      "c": 38.2,
      "f": 11.7
    }
  },
  {
    "n": "Popeyes Strawberry Whipz",
    "k": 224.0,
    "p": 5.1,
    "c": 31.0,
    "f": 8.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 224.0,
      "p": 5.1,
      "c": 31.0,
      "f": 8.6
    }
  },
  {
    "n": "Popeyes Vanilla Whipz",
    "k": 182.0,
    "p": 5.1,
    "c": 20.5,
    "f": 8.6,
    "g": 1,
    "each": true,
    "cat": "fastfood",
    "src": "popeyes-uk",
    "ref": {
      "g": 1,
      "k": 182.0,
      "p": 5.1,
      "c": 20.5,
      "f": 8.6
    }
  }
]
