import type { Food } from '@/core/types'

/** Pret A Manger UK menu: per 100 g (per 100 ml for drinks) with `g` Pret's own serving weight;
 *  barista drinks per cup, one line per milk, as Pret publishes them (no cup weights given).
 *  GENERATED by scripts/import/pret_web.py from docs/data/snapshots/pret-2026-10-10.json: don't edit by hand. */
export const PRET: Food[] = [
  {
    "n": "Pret Americano (black)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.2
    }
  },
  {
    "n": "Pret Americano (semi-skimmed milk)",
    "k": 36.0,
    "p": 2.6,
    "c": 3.8,
    "f": 1.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 36.0,
      "p": 2.6,
      "c": 3.8,
      "f": 1.2
    }
  },
  {
    "n": "Pret Americano (skimmed milk)",
    "k": 27.0,
    "p": 2.6,
    "c": 3.8,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 27.0,
      "p": 2.6,
      "c": 3.8,
      "f": 0.2
    }
  },
  {
    "n": "Pret Americano (soya drink)",
    "k": 30.0,
    "p": 2.3,
    "c": 2.1,
    "f": 1.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 30.0,
      "p": 2.3,
      "c": 2.1,
      "f": 1.4
    }
  },
  {
    "n": "Pret Cappuccino (semi-skimmed milk)",
    "k": 116.0,
    "p": 8.2,
    "c": 11.6,
    "f": 4.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 116.0,
      "p": 8.2,
      "c": 11.6,
      "f": 4.1
    }
  },
  {
    "n": "Pret Cappuccino (soya drink)",
    "k": 92.0,
    "p": 7.3,
    "c": 5.5,
    "f": 4.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 92.0,
      "p": 7.3,
      "c": 5.5,
      "f": 4.2
    }
  },
  {
    "n": "Pret Cappuccino (oat drink)",
    "k": 116.0,
    "p": 0.6,
    "c": 24.4,
    "f": 1.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 116.0,
      "p": 0.6,
      "c": 24.4,
      "f": 1.8
    }
  },
  {
    "n": "Pret Espresso",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.2
    }
  },
  {
    "n": "Pret Filter Coffee (black)",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.2
    }
  },
  {
    "n": "Pret Filter Coffee (oat drink)",
    "k": 16.0,
    "p": 0.1,
    "c": 2.5,
    "f": 0.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 16.0,
      "p": 0.1,
      "c": 2.5,
      "f": 0.6
    }
  },
  {
    "n": "Pret Filter Coffee (skimmed milk)",
    "k": 12.0,
    "p": 1.0,
    "c": 1.5,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 12.0,
      "p": 1.0,
      "c": 1.5,
      "f": 0.3
    }
  },
  {
    "n": "Pret Filter Coffee (semi-skimmed milk)",
    "k": 16.0,
    "p": 1.1,
    "c": 1.5,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 16.0,
      "p": 1.1,
      "c": 1.5,
      "f": 0.7
    }
  },
  {
    "n": "Pret Filter Coffee (soya drink)",
    "k": 15.0,
    "p": 1.1,
    "c": 0.8,
    "f": 0.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 15.0,
      "p": 1.1,
      "c": 0.8,
      "f": 0.8
    }
  },
  {
    "n": "Pret Flat White (semi-skimmed milk)",
    "k": 98.0,
    "p": 6.8,
    "c": 10.0,
    "f": 3.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 98.0,
      "p": 6.8,
      "c": 10.0,
      "f": 3.4
    }
  },
  {
    "n": "Pret Flat White (oat drink)",
    "k": 104.0,
    "p": 0.5,
    "c": 22.0,
    "f": 1.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 104.0,
      "p": 0.5,
      "c": 22.0,
      "f": 1.6
    }
  },
  {
    "n": "Pret Flat White (soya drink)",
    "k": 77.0,
    "p": 6.3,
    "c": 4.1,
    "f": 3.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 77.0,
      "p": 6.3,
      "c": 4.1,
      "f": 3.6
    }
  },
  {
    "n": "Pret Latte (semi-skimmed milk)",
    "k": 136.0,
    "p": 9.5,
    "c": 14.0,
    "f": 4.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 136.0,
      "p": 9.5,
      "c": 14.0,
      "f": 4.6
    }
  },
  {
    "n": "Pret Latte (soya drink)",
    "k": 113.0,
    "p": 9.3,
    "c": 6.1,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 113.0,
      "p": 9.3,
      "c": 6.1,
      "f": 5.3
    }
  },
  {
    "n": "Pret Latte (oat drink)",
    "k": 167.0,
    "p": 0.8,
    "c": 35.0,
    "f": 2.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 167.0,
      "p": 0.8,
      "c": 35.0,
      "f": 2.5
    }
  },
  {
    "n": "Pret Macchiato (semi-skimmed milk)",
    "k": 7.0,
    "p": 0.4,
    "c": 0.6,
    "f": 0.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 7.0,
      "p": 0.4,
      "c": 0.6,
      "f": 0.3
    }
  },
  {
    "n": "Pret Macchiato (oat drink)",
    "k": 6.0,
    "p": 0.0,
    "c": 1.3,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 6.0,
      "p": 0.0,
      "c": 1.3,
      "f": 0.1
    }
  },
  {
    "n": "Pret Macchiato (soya drink)",
    "k": 4.0,
    "p": 0.3,
    "c": 0.3,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 4.0,
      "p": 0.3,
      "c": 0.3,
      "f": 0.2
    }
  },
  {
    "n": "Pret Mocha (semi-skimmed milk)",
    "k": 196.0,
    "p": 10.7,
    "c": 25.0,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 196.0,
      "p": 10.7,
      "c": 25.0,
      "f": 5.3
    }
  },
  {
    "n": "Pret Mocha (oat drink)",
    "k": 216.0,
    "p": 1.9,
    "c": 44.0,
    "f": 3.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 216.0,
      "p": 1.9,
      "c": 44.0,
      "f": 3.3
    }
  },
  {
    "n": "Pret Mocha (soya drink)",
    "k": 181.0,
    "p": 10.1,
    "c": 19.5,
    "f": 6.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 181.0,
      "p": 10.1,
      "c": 19.5,
      "f": 6.2
    }
  },
  {
    "n": "Pret Pumpkin Spice Latte (semi-skimmed milk)",
    "k": 183.0,
    "p": 9.3,
    "c": 25.5,
    "f": 4.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 183.0,
      "p": 9.3,
      "c": 25.5,
      "f": 4.7
    }
  },
  {
    "n": "Pret Pumpkin Spice Latte (skimmed milk)",
    "k": 148.0,
    "p": 8.8,
    "c": 25.8,
    "f": 1.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 148.0,
      "p": 8.8,
      "c": 25.8,
      "f": 1.0
    }
  },
  {
    "n": "Pret Pumpkin Spice Latte (soya drink)",
    "k": 173.0,
    "p": 9.9,
    "c": 19.4,
    "f": 5.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 173.0,
      "p": 9.9,
      "c": 19.4,
      "f": 5.8
    }
  },
  {
    "n": "Pret Pumpkin Spice Latte (oat drink)",
    "k": 179.0,
    "p": 0.9,
    "c": 34.5,
    "f": 3.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 179.0,
      "p": 0.9,
      "c": 34.5,
      "f": 3.6
    }
  },
  {
    "n": "Pret Toasted Marshmallow Hot Chocolate",
    "k": 94.24,
    "p": 2.98,
    "c": 10.13,
    "f": 4.45,
    "g": 382,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 382,
      "k": 360.0,
      "p": 11.4,
      "c": 38.7,
      "f": 17.0
    }
  },
  {
    "n": "Pret Toasted Marshmallow Latte",
    "k": 77.11,
    "p": 2.61,
    "c": 6.87,
    "f": 4.37,
    "g": 380,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 380,
      "k": 293.0,
      "p": 9.9,
      "c": 26.1,
      "f": 16.6
    }
  },
  {
    "n": "Pret Babyccino (semi-skimmed milk)",
    "k": 18.0,
    "p": 1.1,
    "c": 2.1,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 18.0,
      "p": 1.1,
      "c": 2.1,
      "f": 0.5
    }
  },
  {
    "n": "Pret Babyccino (skimmed milk)",
    "k": 14.0,
    "p": 1.1,
    "c": 2.1,
    "f": 0.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 14.0,
      "p": 1.1,
      "c": 2.1,
      "f": 0.1
    }
  },
  {
    "n": "Pret Babyccino (soya drink)",
    "k": 17.0,
    "p": 1.2,
    "c": 1.4,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 17.0,
      "p": 1.2,
      "c": 1.4,
      "f": 0.7
    }
  },
  {
    "n": "Pret Breakfast Tea (semi-skimmed milk)",
    "k": 15.0,
    "p": 1.0,
    "c": 1.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 15.0,
      "p": 1.0,
      "c": 1.5,
      "f": 0.5
    }
  },
  {
    "n": "Pret Breakfast Tea (soya drink)",
    "k": 33.0,
    "p": 2.3,
    "c": 1.8,
    "f": 1.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 33.0,
      "p": 2.3,
      "c": 1.8,
      "f": 1.6
    }
  },
  {
    "n": "Pret Chai Latte",
    "k": 61.61,
    "p": 3.33,
    "c": 8.36,
    "f": 1.64,
    "g": 336,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 336,
      "k": 207.0,
      "p": 11.2,
      "c": 28.1,
      "f": 5.5
    }
  },
  {
    "n": "Pret Earl Grey Tea (semi-skimmed milk)",
    "k": 15.0,
    "p": 1.0,
    "c": 1.5,
    "f": 0.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 15.0,
      "p": 1.0,
      "c": 1.5,
      "f": 0.5
    }
  },
  {
    "n": "Pret Earl Grey Tea (soya drink)",
    "k": 33.0,
    "p": 2.3,
    "c": 1.8,
    "f": 1.6,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 33.0,
      "p": 2.3,
      "c": 1.8,
      "f": 1.6
    }
  },
  {
    "n": "Pret Hot Chocolate (semi-skimmed milk)",
    "k": 247.0,
    "p": 11.5,
    "c": 35.3,
    "f": 5.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 247.0,
      "p": 11.5,
      "c": 35.3,
      "f": 5.4
    }
  },
  {
    "n": "Pret Hot Chocolate (oat drink)",
    "k": 287.0,
    "p": 3.0,
    "c": 57.1,
    "f": 4.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 287.0,
      "p": 3.0,
      "c": 57.1,
      "f": 4.4
    }
  },
  {
    "n": "Pret Hot Chocolate (soya drink)",
    "k": 251.0,
    "p": 11.4,
    "c": 32.4,
    "f": 7.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 251.0,
      "p": 11.4,
      "c": 32.4,
      "f": 7.4
    }
  },
  {
    "n": "Pret Matcha Latte (coconut drink)",
    "k": 86.0,
    "p": 1.2,
    "c": 15.3,
    "f": 2.1,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 86.0,
      "p": 1.2,
      "c": 15.3,
      "f": 2.1
    }
  },
  {
    "n": "Pret Matcha Latte (skimmed milk)",
    "k": 105.0,
    "p": 9.8,
    "c": 14.2,
    "f": 0.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 105.0,
      "p": 9.8,
      "c": 14.2,
      "f": 0.9
    }
  },
  {
    "n": "Pret Matcha Latte (soya drink)",
    "k": 131.0,
    "p": 11.0,
    "c": 7.5,
    "f": 6.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 131.0,
      "p": 11.0,
      "c": 7.5,
      "f": 6.0
    }
  },
  {
    "n": "Pret Matcha Latte (semi-skimmed milk)",
    "k": 141.0,
    "p": 10.4,
    "c": 13.9,
    "f": 4.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 141.0,
      "p": 10.4,
      "c": 13.9,
      "f": 4.9
    }
  },
  {
    "n": "Pret Matcha Latte (oat drink)",
    "k": 138.0,
    "p": 1.4,
    "c": 23.4,
    "f": 3.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 138.0,
      "p": 1.4,
      "c": 23.4,
      "f": 3.7
    }
  },
  {
    "n": "Pret Banana Cinnamon Porridge",
    "k": 84.54,
    "p": 2.69,
    "c": 11.74,
    "f": 2.63,
    "g": 334.75,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 334.75,
      "k": 283.0,
      "p": 9.0,
      "c": 39.3,
      "f": 8.8
    }
  },
  {
    "n": "Pret Coconut & Quinoa Porridge",
    "k": 91.67,
    "p": 2.03,
    "c": 11.47,
    "f": 4.07,
    "g": 300,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 300,
      "k": 275.0,
      "p": 6.1,
      "c": 34.4,
      "f": 12.2
    }
  },
  {
    "n": "Pret Proper Porridge",
    "k": 72.0,
    "p": 2.9,
    "c": 7.9,
    "f": 2.9,
    "g": 300,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 300,
      "k": 216.0,
      "p": 8.7,
      "c": 23.7,
      "f": 8.7
    }
  },
  {
    "n": "Pret Side Porridge",
    "k": 72.0,
    "p": 2.9,
    "c": 7.9,
    "f": 2.9,
    "g": 200,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 200,
      "k": 144.0,
      "p": 5.8,
      "c": 15.8,
      "f": 5.8
    }
  },
  {
    "n": "Pret Crispy Potato Bites",
    "k": 123.33,
    "p": 2.4,
    "c": 20.0,
    "f": 3.2,
    "g": 150,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 150,
      "k": 185.0,
      "p": 3.6,
      "c": 30.0,
      "f": 4.8
    }
  },
  {
    "n": "Pret Kale & Cauli Macaroni Cheese",
    "k": 148.61,
    "p": 7.08,
    "c": 12.64,
    "f": 7.42,
    "g": 360,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 360,
      "k": 535.0,
      "p": 25.5,
      "c": 45.5,
      "f": 26.7
    }
  },
  {
    "n": "Pret Butter Chicken Side Soup",
    "k": 98.08,
    "p": 4.44,
    "c": 6.79,
    "f": 5.42,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 179.0,
      "p": 8.1,
      "c": 12.4,
      "f": 9.9
    }
  },
  {
    "n": "Pret Butter Chicken Soup",
    "k": 98.36,
    "p": 4.44,
    "c": 6.82,
    "f": 5.42,
    "g": 365,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 365,
      "k": 359.0,
      "p": 16.2,
      "c": 24.9,
      "f": 19.8
    }
  },
  {
    "n": "Pret Chicken Laksa Side Soup",
    "k": 81.1,
    "p": 2.36,
    "c": 6.19,
    "f": 4.99,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 148.0,
      "p": 4.3,
      "c": 11.3,
      "f": 9.1
    }
  },
  {
    "n": "Pret Chicken Laksa Soup",
    "k": 81.1,
    "p": 2.38,
    "c": 6.16,
    "f": 4.96,
    "g": 365,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 365,
      "k": 296.0,
      "p": 8.7,
      "c": 22.5,
      "f": 18.1
    }
  },
  {
    "n": "Pret Creamy Roast Chicken Side Soup",
    "k": 62.47,
    "p": 2.79,
    "c": 4.88,
    "f": 3.4,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 114.0,
      "p": 5.1,
      "c": 8.9,
      "f": 6.2
    }
  },
  {
    "n": "Pret Creamy Roast Chicken Soup",
    "k": 62.74,
    "p": 2.79,
    "c": 4.88,
    "f": 3.42,
    "g": 365,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 365,
      "k": 229.0,
      "p": 10.2,
      "c": 17.8,
      "f": 12.5
    }
  },
  {
    "n": "Pret Lasagne Side Soup",
    "k": 83.84,
    "p": 3.78,
    "c": 6.68,
    "f": 4.38,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 153.0,
      "p": 6.9,
      "c": 12.2,
      "f": 8.0
    }
  },
  {
    "n": "Pret Lasagne Soup",
    "k": 83.89,
    "p": 3.81,
    "c": 6.69,
    "f": 4.39,
    "g": 360,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 360,
      "k": 302.0,
      "p": 13.7,
      "c": 24.1,
      "f": 15.8
    }
  },
  {
    "n": "Pret Mushroom Risotto",
    "k": 60.82,
    "p": 1.95,
    "c": 8.08,
    "f": 2.14,
    "g": 365,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 365,
      "k": 222.0,
      "p": 7.1,
      "c": 29.5,
      "f": 7.8
    }
  },
  {
    "n": "Pret Mushroom Risotto Side Soup",
    "k": 60.82,
    "p": 1.97,
    "c": 8.05,
    "f": 2.14,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 111.0,
      "p": 3.6,
      "c": 14.7,
      "f": 3.9
    }
  },
  {
    "n": "Pret White Baguette with Butter (for soup)",
    "k": 325.68,
    "p": 8.78,
    "c": 49.46,
    "f": 9.86,
    "g": 74,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 74,
      "k": 241.0,
      "p": 6.5,
      "c": 36.6,
      "f": 7.3
    }
  },
  {
    "n": "Pret Souper Tomato",
    "k": 38.63,
    "p": 1.64,
    "c": 4.14,
    "f": 1.42,
    "g": 365,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 365,
      "k": 141.0,
      "p": 6.0,
      "c": 15.1,
      "f": 5.2
    }
  },
  {
    "n": "Pret Souper Tomato Side Soup",
    "k": 38.9,
    "p": 1.64,
    "c": 4.11,
    "f": 1.42,
    "g": 182.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 182.5,
      "k": 71.0,
      "p": 3.0,
      "c": 7.5,
      "f": 2.6
    }
  },
  {
    "n": "Pret Classic Cheese Bloomer Toastie",
    "k": 321.41,
    "p": 13.85,
    "c": 25.89,
    "f": 17.53,
    "g": 198.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 198.5,
      "k": 638.0,
      "p": 27.5,
      "c": 51.4,
      "f": 34.8
    }
  },
  {
    "n": "Pret Falafel & Halloumi Hot Wrap",
    "k": 235.02,
    "p": 8.41,
    "c": 23.8,
    "f": 11.13,
    "g": 265.08,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 265.08,
      "k": 623.0,
      "p": 22.3,
      "c": 63.1,
      "f": 29.5
    }
  },
  {
    "n": "Pret Ham & Cheese Bloomer Toastie",
    "k": 279.25,
    "p": 15.33,
    "c": 23.96,
    "f": 13.07,
    "g": 212,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 212,
      "k": 592.0,
      "p": 32.5,
      "c": 50.8,
      "f": 27.7
    }
  },
  {
    "n": "Pret Italian Style Chicken & Basil Hot Wrap",
    "k": 223.84,
    "p": 13.07,
    "c": 19.44,
    "f": 9.88,
    "g": 247.94,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 247.94,
      "k": 555.0,
      "p": 32.4,
      "c": 48.2,
      "f": 24.5
    }
  },
  {
    "n": "Pret Swedish Meatball Hot Wrap",
    "k": 264.02,
    "p": 12.7,
    "c": 18.77,
    "f": 14.88,
    "g": 238.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 238.62,
      "k": 630.0,
      "p": 30.3,
      "c": 44.8,
      "f": 35.5
    }
  },
  {
    "n": "Pret Tuna Melt Bloomer Toastie",
    "k": 253.07,
    "p": 15.63,
    "c": 23.01,
    "f": 10.45,
    "g": 218.12,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 218.12,
      "k": 552.0,
      "p": 34.1,
      "c": 50.2,
      "f": 22.8
    }
  },
  {
    "n": "Pret Warm Beef Birria & Jalapeño Ciabatta",
    "k": 187.86,
    "p": 10.57,
    "c": 22.38,
    "f": 5.83,
    "g": 264.02,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 264.02,
      "k": 496.0,
      "p": 27.9,
      "c": 59.1,
      "f": 15.4
    }
  },
  {
    "n": "Pret Warm Chicken Caesar Bacon Ciabatta",
    "k": 295.15,
    "p": 14.89,
    "c": 20.3,
    "f": 16.87,
    "g": 268,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 268,
      "k": 791.0,
      "p": 39.9,
      "c": 54.4,
      "f": 45.2
    }
  },
  {
    "n": "Pret Warm Three Cheese & Tomato Ciabatta",
    "k": 255.01,
    "p": 10.96,
    "c": 26.49,
    "f": 11.18,
    "g": 223.52,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 223.52,
      "k": 570.0,
      "p": 24.5,
      "c": 59.2,
      "f": 25.0
    }
  },
  {
    "n": "Pret Bacon, Cheese & Jalapeño Pastry",
    "k": 337.71,
    "p": 9.2,
    "c": 27.77,
    "f": 20.8,
    "g": 175,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 175,
      "k": 591.0,
      "p": 16.1,
      "c": 48.6,
      "f": 36.4
    }
  },
  {
    "n": "Pret Ham & Cheese Croissant",
    "k": 318.37,
    "p": 13.78,
    "c": 20.31,
    "f": 19.8,
    "g": 98,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 98,
      "k": 312.0,
      "p": 13.5,
      "c": 19.9,
      "f": 19.4
    }
  },
  {
    "n": "Pret Mozzarella & Tomato Croissant",
    "k": 343.4,
    "p": 11.88,
    "c": 22.19,
    "f": 22.65,
    "g": 108.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 108.62,
      "k": 373.0,
      "p": 12.9,
      "c": 24.1,
      "f": 24.6
    }
  },
  {
    "n": "Pret Sausage Roll",
    "k": 349.09,
    "p": 12.45,
    "c": 20.36,
    "f": 23.64,
    "g": 110,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 110,
      "k": 384.0,
      "p": 13.7,
      "c": 22.4,
      "f": 26.0
    }
  },
  {
    "n": "Pret Spinach & Feta Pastry",
    "k": 314.86,
    "p": 7.2,
    "c": 25.71,
    "f": 19.71,
    "g": 175,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 175,
      "k": 551.0,
      "p": 12.6,
      "c": 45.0,
      "f": 34.5
    }
  },
  {
    "n": "Pret Veggie Breakfast Ciabatta",
    "k": 180.93,
    "p": 8.32,
    "c": 19.65,
    "f": 7.25,
    "g": 205.6,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 205.6,
      "k": 372.0,
      "p": 17.1,
      "c": 40.4,
      "f": 14.9
    }
  },
  {
    "n": "Pret Sausage & Bacon Ciabatta",
    "k": 305.23,
    "p": 15.16,
    "c": 24.25,
    "f": 16.01,
    "g": 153,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 153,
      "k": 467.0,
      "p": 23.2,
      "c": 37.1,
      "f": 24.5
    }
  },
  {
    "n": "Pret Triple Bacon Ciabatta",
    "k": 272.88,
    "p": 15.34,
    "c": 30.25,
    "f": 9.58,
    "g": 118,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 118,
      "k": 322.0,
      "p": 18.1,
      "c": 35.7,
      "f": 11.3
    }
  },
  {
    "n": "Pret Triple Sausage Ciabatta",
    "k": 316.89,
    "p": 13.38,
    "c": 25.54,
    "f": 17.5,
    "g": 148,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 148,
      "k": 469.0,
      "p": 19.8,
      "c": 37.8,
      "f": 25.9
    }
  },
  {
    "n": "Pret Ultimate Breakfast Ciabatta",
    "k": 232.23,
    "p": 11.87,
    "c": 18.88,
    "f": 11.73,
    "g": 216.6,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 216.6,
      "k": 503.0,
      "p": 25.7,
      "c": 40.9,
      "f": 25.4
    }
  },
  {
    "n": "Pret British Sausages, Pret's Baked Beans & Egg Pot",
    "k": 139.02,
    "p": 8.98,
    "c": 4.88,
    "f": 7.93,
    "g": 246,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 246,
      "k": 342.0,
      "p": 22.1,
      "c": 12.0,
      "f": 19.5
    }
  },
  {
    "n": "Pret Roasted Mushroom, Pret's Baked Beans & Egg Pot",
    "k": 84.14,
    "p": 6.21,
    "c": 4.93,
    "f": 2.91,
    "g": 227,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 227,
      "k": 191.0,
      "p": 14.1,
      "c": 11.2,
      "f": 6.6
    }
  },
  {
    "n": "Pret All Butter Croissant",
    "k": 409.86,
    "p": 9.15,
    "c": 38.73,
    "f": 23.66,
    "g": 71,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 71,
      "k": 291.0,
      "p": 6.5,
      "c": 27.5,
      "f": 16.8
    }
  },
  {
    "n": "Pret Almond Croissant",
    "k": 424.44,
    "p": 8.67,
    "c": 43.22,
    "f": 23.44,
    "g": 90,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 90,
      "k": 382.0,
      "p": 7.8,
      "c": 38.9,
      "f": 21.1
    }
  },
  {
    "n": "Pret Chocolate Croissant",
    "k": 406.98,
    "p": 6.86,
    "c": 38.84,
    "f": 23.95,
    "g": 86,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 86,
      "k": 350.0,
      "p": 5.9,
      "c": 33.4,
      "f": 20.6
    }
  },
  {
    "n": "Pret Cinnamon Danish",
    "k": 372.07,
    "p": 6.04,
    "c": 43.51,
    "f": 18.83,
    "g": 111,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 111,
      "k": 413.0,
      "p": 6.7,
      "c": 48.3,
      "f": 20.9
    }
  },
  {
    "n": "Pret Pain aux Raisins",
    "k": 295.87,
    "p": 5.79,
    "c": 40.5,
    "f": 11.9,
    "g": 121,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 121,
      "k": 358.0,
      "p": 7.0,
      "c": 49.0,
      "f": 14.4
    }
  },
  {
    "n": "Pret Very Berry Croissant",
    "k": 339.77,
    "p": 5.0,
    "c": 47.39,
    "f": 13.86,
    "g": 88,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 88,
      "k": 299.0,
      "p": 4.4,
      "c": 41.7,
      "f": 12.2
    }
  },
  {
    "n": "Pret Bacon & Egg Mayo Breakfast Baguette",
    "k": 250.36,
    "p": 11.94,
    "c": 27.84,
    "f": 9.86,
    "g": 139,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 139,
      "k": 348.0,
      "p": 16.6,
      "c": 38.7,
      "f": 13.7
    }
  },
  {
    "n": "Pret Free-Range Egg & Avo Breakfast Baguette",
    "k": 228.61,
    "p": 8.1,
    "c": 25.69,
    "f": 9.88,
    "g": 151.79,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 151.79,
      "k": 347.0,
      "p": 12.3,
      "c": 39.0,
      "f": 15.0
    }
  },
  {
    "n": "Pret Roasted Tomato & Egg Mayo Breakfast Baguette",
    "k": 235.18,
    "p": 9.19,
    "c": 27.56,
    "f": 9.32,
    "g": 153.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 153.5,
      "k": 361.0,
      "p": 14.1,
      "c": 42.3,
      "f": 14.3
    }
  },
  {
    "n": "Pret Smoked Salmon & Egg Mayo Breakfast Baguette",
    "k": 236.24,
    "p": 11.74,
    "c": 25.97,
    "f": 9.19,
    "g": 149,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 149,
      "k": 352.0,
      "p": 17.5,
      "c": 38.7,
      "f": 13.7
    }
  },
  {
    "n": "Pret Acai & Almond Butter Bowl",
    "k": 181.1,
    "p": 4.34,
    "c": 23.41,
    "f": 6.91,
    "g": 186.64,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 186.64,
      "k": 338.0,
      "p": 8.1,
      "c": 43.7,
      "f": 12.9
    }
  },
  {
    "n": "Pret Bircher Muesli",
    "k": 157.16,
    "p": 6.55,
    "c": 20.35,
    "f": 5.14,
    "g": 213.8,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 213.8,
      "k": 336.0,
      "p": 14.0,
      "c": 43.5,
      "f": 11.0
    }
  },
  {
    "n": "Pret Blueberry Balance Bowl",
    "k": 145.87,
    "p": 5.92,
    "c": 15.5,
    "f": 6.24,
    "g": 218,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 218,
      "k": 318.0,
      "p": 12.9,
      "c": 33.8,
      "f": 13.6
    }
  },
  {
    "n": "Pret Five Berry Bowl",
    "k": 161.67,
    "p": 6.24,
    "c": 22.12,
    "f": 4.74,
    "g": 206.6,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 206.6,
      "k": 334.0,
      "p": 12.9,
      "c": 45.7,
      "f": 9.8
    }
  },
  {
    "n": "Pret Mango & Banana Sunshine Bowl",
    "k": 205.5,
    "p": 3.85,
    "c": 27.58,
    "f": 8.05,
    "g": 166.42,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 166.42,
      "k": 342.0,
      "p": 6.4,
      "c": 45.9,
      "f": 13.4
    }
  },
  {
    "n": "Pret The Big Apple Bowl",
    "k": 156.76,
    "p": 6.03,
    "c": 22.28,
    "f": 4.33,
    "g": 193.93,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 193.93,
      "k": 304.0,
      "p": 11.7,
      "c": 43.2,
      "f": 8.4
    }
  },
  {
    "n": "Pret Chicken Salad Sandwich",
    "k": 247.52,
    "p": 10.2,
    "c": 19.98,
    "f": 13.71,
    "g": 213.72,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 213.72,
      "k": 529.0,
      "p": 21.8,
      "c": 42.7,
      "f": 29.3
    }
  },
  {
    "n": "Pret Chicken, Avocado & Basil Sandwich",
    "k": 203.66,
    "p": 9.68,
    "c": 18.15,
    "f": 9.72,
    "g": 239.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 239.62,
      "k": 488.0,
      "p": 23.2,
      "c": 43.5,
      "f": 23.3
    }
  },
  {
    "n": "Pret Chicken, Avocado & Basil Half Sandwich",
    "k": 203.66,
    "p": 9.68,
    "c": 18.2,
    "f": 9.68,
    "g": 119.81,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 119.81,
      "k": 244.0,
      "p": 11.6,
      "c": 21.8,
      "f": 11.6
    }
  },
  {
    "n": "Pret Classic Super Club Sandwich",
    "k": 226.51,
    "p": 11.5,
    "c": 18.66,
    "f": 11.37,
    "g": 233.1,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 233.1,
      "k": 528.0,
      "p": 26.8,
      "c": 43.5,
      "f": 26.5
    }
  },
  {
    "n": "Pret Classic Super Club Half Sandwich",
    "k": 226.51,
    "p": 11.5,
    "c": 18.62,
    "f": 11.41,
    "g": 116.55,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 116.55,
      "k": 264.0,
      "p": 13.4,
      "c": 21.7,
      "f": 13.3
    }
  },
  {
    "n": "Pret Coronation Chicken Sandwich",
    "k": 226.47,
    "p": 10.39,
    "c": 22.23,
    "f": 10.21,
    "g": 214.6,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 214.6,
      "k": 486.0,
      "p": 22.3,
      "c": 47.7,
      "f": 21.9
    }
  },
  {
    "n": "Pret Egg Florentine Sandwich",
    "k": 189.29,
    "p": 9.77,
    "c": 18.76,
    "f": 7.92,
    "g": 242.48,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 242.48,
      "k": 459.0,
      "p": 23.7,
      "c": 45.5,
      "f": 19.2
    }
  },
  {
    "n": "Pret Free-Range Egg Mayo Sandwich",
    "k": 216.57,
    "p": 9.89,
    "c": 24.74,
    "f": 8.17,
    "g": 175,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 175,
      "k": 379.0,
      "p": 17.3,
      "c": 43.3,
      "f": 14.3
    }
  },
  {
    "n": "Pret Ham & Cheese Sandwich",
    "k": 272.84,
    "p": 15.41,
    "c": 21.94,
    "f": 13.26,
    "g": 194.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 194.62,
      "k": 531.0,
      "p": 30.0,
      "c": 42.7,
      "f": 25.8
    }
  },
  {
    "n": "Pret Mature Cheddar & Pret Pickle Sandwich",
    "k": 226.68,
    "p": 8.12,
    "c": 24.41,
    "f": 10.26,
    "g": 224.1,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 224.1,
      "k": 508.0,
      "p": 18.2,
      "c": 54.7,
      "f": 23.0
    }
  },
  {
    "n": "Pret New Yorker Club Sandwich",
    "k": 234.97,
    "p": 11.27,
    "c": 22.71,
    "f": 10.46,
    "g": 306,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 306,
      "k": 719.0,
      "p": 34.5,
      "c": 69.5,
      "f": 32.0
    }
  },
  {
    "n": "Pret Scottish Smoked Salmon Sandwich",
    "k": 263.76,
    "p": 14.08,
    "c": 25.87,
    "f": 11.03,
    "g": 157.72,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 157.72,
      "k": 416.0,
      "p": 22.2,
      "c": 40.8,
      "f": 17.4
    }
  },
  {
    "n": "Pret Tuna & Cucumber Sandwich",
    "k": 210.44,
    "p": 10.27,
    "c": 24.04,
    "f": 7.72,
    "g": 180.1,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 180.1,
      "k": 379.0,
      "p": 18.5,
      "c": 43.3,
      "f": 13.9
    }
  },
  {
    "n": "Pret Avo, Olive & Toms Baguette",
    "k": 238.23,
    "p": 5.49,
    "c": 24.12,
    "f": 12.5,
    "g": 236.75,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 236.75,
      "k": 564.0,
      "p": 13.0,
      "c": 57.1,
      "f": 29.6
    }
  },
  {
    "n": "Pret Avo, Olive & Toms Half Baguette",
    "k": 238.22,
    "p": 5.49,
    "c": 24.16,
    "f": 12.5,
    "g": 118.38,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 118.38,
      "k": 282.0,
      "p": 6.5,
      "c": 28.6,
      "f": 14.8
    }
  },
  {
    "n": "Pret Brie, Tomato & Basil Baguette",
    "k": 232.92,
    "p": 9.34,
    "c": 29.82,
    "f": 8.06,
    "g": 188.48,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 188.48,
      "k": 439.0,
      "p": 17.6,
      "c": 56.2,
      "f": 15.2
    }
  },
  {
    "n": "Pret Chicken Caesar & Bacon Half Baguette",
    "k": 273.39,
    "p": 13.85,
    "c": 24.95,
    "f": 12.66,
    "g": 109,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 109,
      "k": 298.0,
      "p": 15.1,
      "c": 27.2,
      "f": 13.8
    }
  },
  {
    "n": "Pret Chicken Caesar Bacon Baguette",
    "k": 273.39,
    "p": 13.9,
    "c": 24.91,
    "f": 12.66,
    "g": 218,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 218,
      "k": 596.0,
      "p": 30.3,
      "c": 54.3,
      "f": 27.6
    }
  },
  {
    "n": "Pret Chicken Salad Baguette",
    "k": 265.03,
    "p": 10.69,
    "c": 25.39,
    "f": 13.14,
    "g": 224.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 224.5,
      "k": 595.0,
      "p": 24.0,
      "c": 57.0,
      "f": 29.5
    }
  },
  {
    "n": "Pret Chicken Satay Baguette",
    "k": 223.28,
    "p": 11.48,
    "c": 26.94,
    "f": 7.32,
    "g": 240.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 240.5,
      "k": 537.0,
      "p": 27.6,
      "c": 64.8,
      "f": 17.6
    }
  },
  {
    "n": "Pret Coronation Chicken Baguette",
    "k": 238.37,
    "p": 10.99,
    "c": 25.99,
    "f": 9.54,
    "g": 227.38,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 227.38,
      "k": 542.0,
      "p": 25.0,
      "c": 59.1,
      "f": 21.7
    }
  },
  {
    "n": "Pret Coronation Chicken Half Baguette",
    "k": 238.37,
    "p": 10.99,
    "c": 26.04,
    "f": 9.5,
    "g": 113.69,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 113.69,
      "k": 271.0,
      "p": 12.5,
      "c": 29.6,
      "f": 10.8
    }
  },
  {
    "n": "Pret Italian Prosciutto Baguette",
    "k": 248.18,
    "p": 10.95,
    "c": 24.68,
    "f": 11.23,
    "g": 220,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 220,
      "k": 546.0,
      "p": 24.1,
      "c": 54.3,
      "f": 24.7
    }
  },
  {
    "n": "Pret Italian Prosciutto Half Baguette",
    "k": 248.55,
    "p": 10.98,
    "c": 24.67,
    "f": 11.25,
    "g": 110.24,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 110.24,
      "k": 274.0,
      "p": 12.1,
      "c": 27.2,
      "f": 12.4
    }
  },
  {
    "n": "Pret Mortadella, Mozzarella & Pistachio Baguette",
    "k": 271.14,
    "p": 12.06,
    "c": 20.71,
    "f": 15.09,
    "g": 263.7,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 263.7,
      "k": 715.0,
      "p": 31.8,
      "c": 54.6,
      "f": 39.8
    }
  },
  {
    "n": "Pret Pole & Line Caught Tuna Baguette",
    "k": 223.6,
    "p": 10.94,
    "c": 25.53,
    "f": 8.38,
    "g": 230.32,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 230.32,
      "k": 515.0,
      "p": 25.2,
      "c": 58.8,
      "f": 19.3
    }
  },
  {
    "n": "Pret Pole & Line Caught Tuna Half Baguette",
    "k": 223.17,
    "p": 10.94,
    "c": 25.53,
    "f": 8.34,
    "g": 115.16,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 115.16,
      "k": 257.0,
      "p": 12.6,
      "c": 29.4,
      "f": 9.6
    }
  },
  {
    "n": "Pret Posh Cheddar & Pickle Baguette",
    "k": 277.61,
    "p": 9.24,
    "c": 31.04,
    "f": 12.3,
    "g": 231.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 231.62,
      "k": 643.0,
      "p": 21.4,
      "c": 71.9,
      "f": 28.5
    }
  },
  {
    "n": "Pret Posh Cheddar & Pickle Half Baguette",
    "k": 275.92,
    "p": 9.17,
    "c": 30.85,
    "f": 12.25,
    "g": 116.7,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 116.7,
      "k": 322.0,
      "p": 10.7,
      "c": 36.0,
      "f": 14.3
    }
  },
  {
    "n": "Pret Chicken Satay Half Baguette",
    "k": 223.7,
    "p": 11.48,
    "c": 26.94,
    "f": 7.32,
    "g": 120.25,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 120.25,
      "k": 269.0,
      "p": 13.8,
      "c": 32.4,
      "f": 8.8
    }
  },
  {
    "n": "Pret Smoked Salmon, Egg Mayo & Avo Baguette",
    "k": 230.36,
    "p": 10.27,
    "c": 22.79,
    "f": 10.39,
    "g": 239.62,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 239.62,
      "k": 552.0,
      "p": 24.6,
      "c": 54.6,
      "f": 24.9
    }
  },
  {
    "n": "Pret Smoked Salmon, Soft Cheese & Dill Baguette",
    "k": 241.19,
    "p": 13.0,
    "c": 25.71,
    "f": 9.15,
    "g": 207.72,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 207.72,
      "k": 501.0,
      "p": 27.0,
      "c": 53.4,
      "f": 19.0
    }
  },
  {
    "n": "Pret Wiltshire Cured Ham & Grevé Baguette",
    "k": 267.87,
    "p": 14.16,
    "c": 25.8,
    "f": 11.64,
    "g": 222.5,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 222.5,
      "k": 596.0,
      "p": 31.5,
      "c": 57.4,
      "f": 25.9
    }
  },
  {
    "n": "Pret Avo & Herb Wrap",
    "k": 202.94,
    "p": 5.05,
    "c": 16.17,
    "f": 12.57,
    "g": 247.36,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 247.36,
      "k": 502.0,
      "p": 12.5,
      "c": 40.0,
      "f": 31.1
    }
  },
  {
    "n": "Pret Chicken Pesto & Rocket Wrap",
    "k": 242.13,
    "p": 10.37,
    "c": 18.02,
    "f": 13.94,
    "g": 213.11,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 213.11,
      "k": 516.0,
      "p": 22.1,
      "c": 38.4,
      "f": 29.7
    }
  },
  {
    "n": "Pret Chicken Satay Wrap",
    "k": 184.22,
    "p": 9.77,
    "c": 18.02,
    "f": 7.69,
    "g": 249.7,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 249.7,
      "k": 460.0,
      "p": 24.4,
      "c": 45.0,
      "f": 19.2
    }
  },
  {
    "n": "Pret Falafel, Avo & Chipotle Flatbread",
    "k": 187.93,
    "p": 4.48,
    "c": 24.67,
    "f": 7.23,
    "g": 265.53,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 265.53,
      "k": 499.0,
      "p": 11.9,
      "c": 65.5,
      "f": 19.2
    }
  },
  {
    "n": "Pret Falafel, Avo & Chipotle Half Flatbread",
    "k": 188.31,
    "p": 4.44,
    "c": 24.71,
    "f": 7.23,
    "g": 132.76,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 132.76,
      "k": 250.0,
      "p": 5.9,
      "c": 32.8,
      "f": 9.6
    }
  },
  {
    "n": "Pret Hoisin Duck Wrap",
    "k": 198.47,
    "p": 9.43,
    "c": 21.64,
    "f": 7.86,
    "g": 222.7,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 222.7,
      "k": 442.0,
      "p": 21.0,
      "c": 48.2,
      "f": 17.5
    }
  },
  {
    "n": "Pret Humous & Chipotle Wrap",
    "k": 168.27,
    "p": 5.16,
    "c": 20.0,
    "f": 6.5,
    "g": 246.03,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 246.03,
      "k": 414.0,
      "p": 12.7,
      "c": 49.2,
      "f": 16.0
    }
  },
  {
    "n": "Pret Mediterranean Style Tuna Flatbread",
    "k": 189.78,
    "p": 9.19,
    "c": 18.79,
    "f": 8.39,
    "g": 264.51,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 264.51,
      "k": 502.0,
      "p": 24.3,
      "c": 49.7,
      "f": 22.2
    }
  },
  {
    "n": "Pret Mediterranean Style Tuna Half Flatbread",
    "k": 189.79,
    "p": 9.15,
    "c": 18.83,
    "f": 8.39,
    "g": 132.25,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 132.25,
      "k": 251.0,
      "p": 12.1,
      "c": 24.9,
      "f": 11.1
    }
  },
  {
    "n": "Pret Shawarma Spiced Chicken Flatbread",
    "k": 177.73,
    "p": 11.18,
    "c": 22.25,
    "f": 4.2,
    "g": 254.88,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 254.88,
      "k": 453.0,
      "p": 28.5,
      "c": 56.7,
      "f": 10.7
    }
  },
  {
    "n": "Pret Shawarma Spiced Chicken Half Flatbread",
    "k": 177.34,
    "p": 11.14,
    "c": 22.28,
    "f": 4.16,
    "g": 127.44,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 127.44,
      "k": 226.0,
      "p": 14.2,
      "c": 28.4,
      "f": 5.3
    }
  },
  {
    "n": "Pret Iced Chai Latte",
    "k": 40.5,
    "p": 2.05,
    "c": 5.83,
    "f": 1.0,
    "g": 400,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 400,
      "k": 162.0,
      "p": 8.2,
      "c": 23.3,
      "f": 4.0
    }
  },
  {
    "n": "Pret Iced Hot Chocolate",
    "k": 52.39,
    "p": 2.1,
    "c": 8.11,
    "f": 0.98,
    "g": 376,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 376,
      "k": 197.0,
      "p": 7.9,
      "c": 30.5,
      "f": 3.7
    }
  },
  {
    "n": "Pret Iced Matcha Latte (coconut drink)",
    "k": 63.0,
    "p": 1.0,
    "c": 11.2,
    "f": 1.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 63.0,
      "p": 1.0,
      "c": 11.2,
      "f": 1.5
    }
  },
  {
    "n": "Pret Iced Matcha Latte (soya drink)",
    "k": 95.0,
    "p": 8.0,
    "c": 5.6,
    "f": 4.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 95.0,
      "p": 8.0,
      "c": 5.6,
      "f": 4.3
    }
  },
  {
    "n": "Pret Iced Matcha Latte (skimmed milk)",
    "k": 77.0,
    "p": 7.2,
    "c": 10.4,
    "f": 0.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 77.0,
      "p": 7.2,
      "c": 10.4,
      "f": 0.7
    }
  },
  {
    "n": "Pret Iced Matcha Latte (semi-skimmed milk)",
    "k": 103.0,
    "p": 7.6,
    "c": 10.2,
    "f": 3.5,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 103.0,
      "p": 7.6,
      "c": 10.2,
      "f": 3.5
    }
  },
  {
    "n": "Pret Iced Matcha Latte (oat drink)",
    "k": 100.0,
    "p": 1.2,
    "c": 17.0,
    "f": 2.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 100.0,
      "p": 1.2,
      "c": 17.0,
      "f": 2.7
    }
  },
  {
    "n": "Pret Caramel Frappé",
    "k": 83.6,
    "p": 2.75,
    "c": 8.5,
    "f": 4.29,
    "g": 506,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 506,
      "k": 423.0,
      "p": 13.9,
      "c": 43.0,
      "f": 21.7
    }
  },
  {
    "n": "Pret Classic Frappe",
    "k": 365.0,
    "p": 10.6,
    "c": 26.7,
    "f": 23.9,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 365.0,
      "p": 10.6,
      "c": 26.7,
      "f": 23.9
    }
  },
  {
    "n": "Pret Frozen Hot Chocolate",
    "k": 503.0,
    "p": 16.8,
    "c": 54.8,
    "f": 22.8,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 503.0,
      "p": 16.8,
      "c": 54.8,
      "f": 22.8
    }
  },
  {
    "n": "Pret Hazelnut Frappé",
    "k": 83.6,
    "p": 2.75,
    "c": 8.46,
    "f": 4.29,
    "g": 506,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 506,
      "k": 423.0,
      "p": 13.9,
      "c": 42.8,
      "f": 21.7
    }
  },
  {
    "n": "Pret Iced Black Americano",
    "k": 2.0,
    "p": 0.0,
    "c": 0.0,
    "f": 0.2,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 2.0,
      "p": 0.0,
      "c": 0.0,
      "f": 0.2
    }
  },
  {
    "n": "Pret Iced Latte (semi-skimmed milk)",
    "k": 98.0,
    "p": 6.8,
    "c": 10.0,
    "f": 3.4,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 98.0,
      "p": 6.8,
      "c": 10.0,
      "f": 3.4
    }
  },
  {
    "n": "Pret Iced Latte (soya drink)",
    "k": 113.0,
    "p": 9.3,
    "c": 6.1,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 113.0,
      "p": 9.3,
      "c": 6.1,
      "f": 5.3
    }
  },
  {
    "n": "Pret Iced Latte (oat drink)",
    "k": 149.0,
    "p": 0.8,
    "c": 31.3,
    "f": 2.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 149.0,
      "p": 0.8,
      "c": 31.3,
      "f": 2.3
    }
  },
  {
    "n": "Pret Iced Mocha (semi-skimmed milk)",
    "k": 159.0,
    "p": 8.0,
    "c": 21.4,
    "f": 4.0,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 159.0,
      "p": 8.0,
      "c": 21.4,
      "f": 4.0
    }
  },
  {
    "n": "Pret Iced Mocha (soya drink)",
    "k": 160.0,
    "p": 8.6,
    "c": 18.0,
    "f": 5.3,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 160.0,
      "p": 8.6,
      "c": 18.0,
      "f": 5.3
    }
  },
  {
    "n": "Pret Iced Mocha (skimmed milk)",
    "k": 143.0,
    "p": 8.0,
    "c": 23.2,
    "f": 1.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 143.0,
      "p": 8.0,
      "c": 23.2,
      "f": 1.7
    }
  },
  {
    "n": "Pret Iced Mocha (oat drink)",
    "k": 161.0,
    "p": 1.8,
    "c": 28.7,
    "f": 3.7,
    "g": 1,
    "each": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 1,
      "k": 161.0,
      "p": 1.8,
      "c": 28.7,
      "f": 3.7
    }
  },
  {
    "n": "Pret Mocha Frappé",
    "k": 86.61,
    "p": 3.01,
    "c": 8.46,
    "f": 4.39,
    "g": 508,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 508,
      "k": 440.0,
      "p": 15.3,
      "c": 43.0,
      "f": 22.3
    }
  },
  {
    "n": "Pret Vanilla Frappé",
    "k": 84.19,
    "p": 2.75,
    "c": 8.64,
    "f": 4.29,
    "g": 506,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 506,
      "k": 426.0,
      "p": 13.9,
      "c": 43.7,
      "f": 21.7
    }
  },
  {
    "n": "Pret Vanilla Matcha Frappe",
    "k": 87.6,
    "p": 2.95,
    "c": 9.02,
    "f": 4.39,
    "g": 492,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 492,
      "k": 431.0,
      "p": 14.5,
      "c": 44.4,
      "f": 21.6
    }
  },
  {
    "n": "Pret Apple Juice",
    "k": 50.4,
    "p": 0.12,
    "c": 12.28,
    "f": 0.08,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 250,
      "k": 126.0,
      "p": 0.3,
      "c": 30.7,
      "f": 0.2
    }
  },
  {
    "n": "Pret Berries & Banana Smoothie",
    "k": 44.44,
    "p": 0.38,
    "c": 10.02,
    "f": 0.13,
    "g": 450,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 450,
      "k": 200.0,
      "p": 1.7,
      "c": 45.1,
      "f": 0.6
    }
  },
  {
    "n": "Pret Easy Greens",
    "k": 17.5,
    "p": 0.0,
    "c": 4.4,
    "f": 0.0,
    "g": 200,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 200,
      "k": 35.0,
      "p": 0.0,
      "c": 8.8,
      "f": 0.0
    }
  },
  {
    "n": "Pret Ginger Shot",
    "k": 50.0,
    "p": 0.73,
    "c": 10.36,
    "f": 0.27,
    "g": 110,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 110,
      "k": 55.0,
      "p": 0.8,
      "c": 11.4,
      "f": 0.3
    }
  },
  {
    "n": "Pret Hot Shot",
    "k": 24.55,
    "p": 0.36,
    "c": 4.73,
    "f": 0.18,
    "g": 110,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 110,
      "k": 27.0,
      "p": 0.4,
      "c": 5.2,
      "f": 0.2
    }
  },
  {
    "n": "Pret Mango & Peach Smoothie",
    "k": 42.22,
    "p": 0.4,
    "c": 9.69,
    "f": 0.09,
    "g": 450,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 450,
      "k": 190.0,
      "p": 1.8,
      "c": 43.6,
      "f": 0.4
    }
  },
  {
    "n": "Pret Mango Smoothie",
    "k": 56.8,
    "p": 0.48,
    "c": 12.68,
    "f": 0.28,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 250,
      "k": 142.0,
      "p": 1.2,
      "c": 31.7,
      "f": 0.7
    }
  },
  {
    "n": "Pret Orange Juice",
    "k": 42.0,
    "p": 0.8,
    "c": 9.0,
    "f": 0.2,
    "g": 150,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 150,
      "k": 63.0,
      "p": 1.2,
      "c": 13.5,
      "f": 0.3
    }
  },
  {
    "n": "Pret Vitamin Volcano",
    "k": 46.0,
    "p": 0.48,
    "c": 11.0,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 250,
      "k": 115.0,
      "p": 1.2,
      "c": 27.5,
      "f": 0.0
    }
  },
  {
    "n": "Pret Coca-Cola 500ml",
    "k": 42.4,
    "p": 0.0,
    "c": 10.6,
    "f": 0.0,
    "g": 500,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 500,
      "k": 212.0,
      "p": 0.0,
      "c": 53.0,
      "f": 0.0
    }
  },
  {
    "n": "Pret Coca-Cola 330ml can",
    "k": 42.42,
    "p": 0.0,
    "c": 10.61,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 140.0,
      "p": 0.0,
      "c": 35.0,
      "f": 0.0
    }
  },
  {
    "n": "Pret Cranberry, Raspberry & Pomegranate Pret Still",
    "k": 22.5,
    "p": 0.1,
    "c": 4.79,
    "f": 0.22,
    "g": 511,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 511,
      "k": 115.0,
      "p": 0.5,
      "c": 24.5,
      "f": 1.1
    }
  },
  {
    "n": "Pret Ginger Kombucha",
    "k": 18.0,
    "p": 0.0,
    "c": 4.48,
    "f": 0.0,
    "g": 250,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 250,
      "k": 45.0,
      "p": 0.0,
      "c": 11.2,
      "f": 0.0
    }
  },
  {
    "n": "Pret Green Tea & Peach Pret Still",
    "k": 20.8,
    "p": 0.1,
    "c": 4.3,
    "f": 0.24,
    "g": 500,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 500,
      "k": 104.0,
      "p": 0.5,
      "c": 21.5,
      "f": 1.2
    }
  },
  {
    "n": "Pret Lemon & Ginger Pret Still",
    "k": 18.8,
    "p": 0.1,
    "c": 3.9,
    "f": 0.2,
    "g": 500,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 500,
      "k": 94.0,
      "p": 0.5,
      "c": 19.5,
      "f": 1.0
    }
  },
  {
    "n": "Pret Mango & Passion Fruit Pret Still",
    "k": 22.4,
    "p": 0.1,
    "c": 4.7,
    "f": 0.24,
    "g": 500,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 500,
      "k": 112.0,
      "p": 0.5,
      "c": 23.5,
      "f": 1.2
    }
  },
  {
    "n": "Pret Rhubarb Lemonade",
    "k": 32.42,
    "p": 0.0,
    "c": 8.09,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 107.0,
      "p": 0.0,
      "c": 26.7,
      "f": 0.0
    }
  },
  {
    "n": "Pret Sparkling Apple Fizz",
    "k": 31.52,
    "p": 0.0,
    "c": 7.91,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 104.0,
      "p": 0.0,
      "c": 26.1,
      "f": 0.0
    }
  },
  {
    "n": "Pret Sparkling Ginger Beer",
    "k": 36.06,
    "p": 0.0,
    "c": 9.0,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 119.0,
      "p": 0.0,
      "c": 29.7,
      "f": 0.0
    }
  },
  {
    "n": "Pret Sparkling Grape & Elderflower",
    "k": 29.7,
    "p": 0.0,
    "c": 7.39,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 98.0,
      "p": 0.0,
      "c": 24.4,
      "f": 0.0
    }
  },
  {
    "n": "Pret poppi Lemon Lime",
    "k": 7.88,
    "p": 0.0,
    "c": 1.48,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 26.0,
      "p": 0.0,
      "c": 4.9,
      "f": 0.0
    }
  },
  {
    "n": "Pret poppi Orange",
    "k": 7.88,
    "p": 0.0,
    "c": 1.48,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 26.0,
      "p": 0.0,
      "c": 4.9,
      "f": 0.0
    }
  },
  {
    "n": "Pret poppi Raspberry Rose",
    "k": 8.18,
    "p": 0.0,
    "c": 1.48,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 27.0,
      "p": 0.0,
      "c": 4.9,
      "f": 0.0
    }
  },
  {
    "n": "Pret poppi Strawberry & Lemon",
    "k": 8.18,
    "p": 0.0,
    "c": 1.61,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 27.0,
      "p": 0.0,
      "c": 5.3,
      "f": 0.0
    }
  },
  {
    "n": "Pret poppi Wild Berry",
    "k": 7.27,
    "p": 0.0,
    "c": 1.39,
    "f": 0.0,
    "g": 330,
    "ml": true,
    "cat": "drinks",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330,
      "k": 24.0,
      "p": 0.0,
      "c": 4.6,
      "f": 0.0
    }
  },
  {
    "n": "Pret Chipotle Chicken Super Plate",
    "k": 133.0,
    "p": 9.4,
    "c": 9.08,
    "f": 6.0,
    "g": 533.1,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 533.1,
      "k": 709.0,
      "p": 50.1,
      "c": 48.4,
      "f": 32.0
    }
  },
  {
    "n": "Pret Korean BBQ Tofu Super Plate",
    "k": 99.56,
    "p": 4.77,
    "c": 11.31,
    "f": 3.41,
    "g": 451,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 451,
      "k": 449.0,
      "p": 21.5,
      "c": 51.0,
      "f": 15.4
    }
  },
  {
    "n": "Pret Miso Salmon Super Plate",
    "k": 149.1,
    "p": 7.05,
    "c": 8.5,
    "f": 9.23,
    "g": 510.4,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 510.4,
      "k": 761.0,
      "p": 36.0,
      "c": 43.4,
      "f": 47.1
    }
  },
  {
    "n": "Pret Shawarma Chicken Super Plate",
    "k": 140.38,
    "p": 11.24,
    "c": 6.95,
    "f": 6.77,
    "g": 447.35,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 447.35,
      "k": 628.0,
      "p": 50.3,
      "c": 31.1,
      "f": 30.3
    }
  },
  {
    "n": "Pret Butternut & Humous Mezze Bowl",
    "k": 119.43,
    "p": 3.99,
    "c": 12.21,
    "f": 5.14,
    "g": 330.75,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 330.75,
      "k": 395.0,
      "p": 13.2,
      "c": 40.4,
      "f": 17.0
    }
  },
  {
    "n": "Pret Butternut & Humous Side Salad",
    "k": 107.19,
    "p": 3.96,
    "c": 9.14,
    "f": 5.18,
    "g": 139,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 139,
      "k": 149.0,
      "p": 5.5,
      "c": 12.7,
      "f": 7.2
    }
  },
  {
    "n": "Pret Chef's Italian Chicken Salad",
    "k": 168.21,
    "p": 8.09,
    "c": 3.84,
    "f": 13.18,
    "g": 312.7,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 312.7,
      "k": 526.0,
      "p": 25.3,
      "c": 12.0,
      "f": 41.2
    }
  },
  {
    "n": "Pret Chicken & Greens Protein Plate",
    "k": 104.61,
    "p": 12.55,
    "c": 5.36,
    "f": 3.3,
    "g": 272.45,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 272.45,
      "k": 285.0,
      "p": 34.2,
      "c": 14.6,
      "f": 9.0
    }
  },
  {
    "n": "Pret Classic Green Side Salad",
    "k": 129.93,
    "p": 4.91,
    "c": 4.48,
    "f": 10.03,
    "g": 138.54,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 138.54,
      "k": 180.0,
      "p": 6.8,
      "c": 6.2,
      "f": 13.9
    }
  },
  {
    "n": "Pret Miso Chicken Rice Bowl",
    "k": 119.7,
    "p": 8.27,
    "c": 10.66,
    "f": 4.51,
    "g": 321.65,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 321.65,
      "k": 385.0,
      "p": 26.6,
      "c": 34.3,
      "f": 14.5
    }
  },
  {
    "n": "Pret Smoked Salmon & Egg Protein Plate",
    "k": 142.41,
    "p": 11.03,
    "c": 2.66,
    "f": 9.41,
    "g": 290,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 290,
      "k": 413.0,
      "p": 32.0,
      "c": 7.7,
      "f": 27.3
    }
  },
  {
    "n": "Pret Tuna Nicoise Salad",
    "k": 119.34,
    "p": 9.9,
    "c": 2.84,
    "f": 7.49,
    "g": 299.14,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 299.14,
      "k": 357.0,
      "p": 29.6,
      "c": 8.5,
      "f": 22.4
    }
  },
  {
    "n": "Pret Chicken & Edamame Protein Pot",
    "k": 150.4,
    "p": 20.52,
    "c": 5.4,
    "f": 4.7,
    "g": 129.65,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 129.65,
      "k": 195.0,
      "p": 26.6,
      "c": 7.0,
      "f": 6.1
    }
  },
  {
    "n": "Pret Egg & Spinach Protein Pot",
    "k": 104.46,
    "p": 11.56,
    "c": 2.33,
    "f": 5.38,
    "g": 98.6,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 98.6,
      "k": 103.0,
      "p": 11.4,
      "c": 2.3,
      "f": 5.3
    }
  },
  {
    "n": "Pret Smoked Salmon & Egg Protein Pot",
    "k": 130.62,
    "p": 12.39,
    "c": 1.82,
    "f": 8.07,
    "g": 104.12,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 104.12,
      "k": 136.0,
      "p": 12.9,
      "c": 1.9,
      "f": 8.4
    }
  },
  {
    "n": "Pret Salt & Cider Vinegar Crisps",
    "k": 515.0,
    "p": 4.75,
    "c": 53.25,
    "f": 30.5,
    "g": 40,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 40,
      "k": 206.0,
      "p": 1.9,
      "c": 21.3,
      "f": 12.2
    }
  },
  {
    "n": "Pret Mature Cheddar & Red Onion Crisps",
    "k": 525.0,
    "p": 6.5,
    "c": 51.25,
    "f": 31.75,
    "g": 40,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 40,
      "k": 210.0,
      "p": 2.6,
      "c": 20.5,
      "f": 12.7
    }
  },
  {
    "n": "Pret Salted Popcorn",
    "k": 468.97,
    "p": 8.62,
    "c": 48.97,
    "f": 23.79,
    "g": 29,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 29,
      "k": 136.0,
      "p": 2.5,
      "c": 14.2,
      "f": 6.9
    }
  },
  {
    "n": "Pret Sea Salt Crisps",
    "k": 532.5,
    "p": 6.0,
    "c": 55.0,
    "f": 31.0,
    "g": 40,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 40,
      "k": 213.0,
      "p": 2.4,
      "c": 22.0,
      "f": 12.4
    }
  },
  {
    "n": "Pret Smoky Chipotle Crisps",
    "k": 520.0,
    "p": 5.5,
    "c": 52.5,
    "f": 31.0,
    "g": 40,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 40,
      "k": 208.0,
      "p": 2.2,
      "c": 21.0,
      "f": 12.4
    }
  },
  {
    "n": "Pret Sweet & Salt Popcorn",
    "k": 523.33,
    "p": 5.67,
    "c": 50.67,
    "f": 31.0,
    "g": 30,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 30,
      "k": 157.0,
      "p": 1.7,
      "c": 15.2,
      "f": 9.3
    }
  },
  {
    "n": "Pret Pastel De Nata",
    "k": 261.67,
    "p": 4.83,
    "c": 35.33,
    "f": 10.33,
    "g": 60,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 60,
      "k": 157.0,
      "p": 2.9,
      "c": 21.2,
      "f": 6.2
    }
  },
  {
    "n": "Pret Chocolate Bar",
    "k": 542.86,
    "p": 4.43,
    "c": 53.29,
    "f": 33.57,
    "g": 70,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 70,
      "k": 380.0,
      "p": 3.1,
      "c": 37.3,
      "f": 23.5
    }
  },
  {
    "n": "Pret Chocolate Brownie Bar",
    "k": 493.85,
    "p": 6.15,
    "c": 46.15,
    "f": 30.62,
    "g": 65,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 65,
      "k": 321.0,
      "p": 4.0,
      "c": 30.0,
      "f": 19.9
    }
  },
  {
    "n": "Pret Dark Chocolate Corn Cakes",
    "k": 482.35,
    "p": 7.06,
    "c": 61.18,
    "f": 21.76,
    "g": 17,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 17,
      "k": 82.0,
      "p": 1.2,
      "c": 10.4,
      "f": 3.7
    }
  },
  {
    "n": "Pret Dark Chocolate with Sea Salt",
    "k": 573.33,
    "p": 9.0,
    "c": 31.67,
    "f": 43.0,
    "g": 30,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 30,
      "k": 172.0,
      "p": 2.7,
      "c": 9.5,
      "f": 12.9
    }
  },
  {
    "n": "Pret Love Bar",
    "k": 497.14,
    "p": 5.43,
    "c": 58.86,
    "f": 25.71,
    "g": 70,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 70,
      "k": 348.0,
      "p": 3.8,
      "c": 41.2,
      "f": 18.0
    }
  },
  {
    "n": "Pret Milk Chocolate Bar",
    "k": 573.33,
    "p": 7.67,
    "c": 44.33,
    "f": 39.33,
    "g": 30,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 30,
      "k": 172.0,
      "p": 2.3,
      "c": 13.3,
      "f": 11.8
    }
  },
  {
    "n": "Pret Popcorn Bar",
    "k": 517.65,
    "p": 5.0,
    "c": 64.12,
    "f": 26.18,
    "g": 34,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 34,
      "k": 176.0,
      "p": 1.7,
      "c": 21.8,
      "f": 8.9
    }
  },
  {
    "n": "Pret Bar",
    "k": 435.94,
    "p": 6.25,
    "c": 54.06,
    "f": 20.94,
    "g": 64,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 64,
      "k": 279.0,
      "p": 4.0,
      "c": 34.6,
      "f": 13.4
    }
  },
  {
    "n": "Pret Cranberries in Coats",
    "k": 470.0,
    "p": 1.0,
    "c": 73.0,
    "f": 19.0,
    "g": 50,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 50,
      "k": 235.0,
      "p": 0.5,
      "c": 36.5,
      "f": 9.5
    }
  },
  {
    "n": "Pret Dark Chocolate Salted Almonds",
    "k": 565.79,
    "p": 14.47,
    "c": 32.63,
    "f": 39.74,
    "g": 38,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 38,
      "k": 215.0,
      "p": 5.5,
      "c": 12.4,
      "f": 15.1
    }
  },
  {
    "n": "Pret Nuts, Fruit, Chocolate",
    "k": 560.0,
    "p": 16.29,
    "c": 38.29,
    "f": 36.57,
    "g": 35,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 35,
      "k": 196.0,
      "p": 5.7,
      "c": 13.4,
      "f": 12.8
    }
  },
  {
    "n": "Pret A Mango",
    "k": 337.14,
    "p": 2.0,
    "c": 76.86,
    "f": 1.14,
    "g": 35,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 35,
      "k": 118.0,
      "p": 0.7,
      "c": 26.9,
      "f": 0.4
    }
  },
  {
    "n": "Pret Chocolate Chunk Cookie",
    "k": 432.89,
    "p": 5.39,
    "c": 64.34,
    "f": 16.45,
    "g": 76,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 76,
      "k": 329.0,
      "p": 4.1,
      "c": 48.9,
      "f": 12.5
    }
  },
  {
    "n": "Pret Chocolate Hazelnut Praline Cookie",
    "k": 471.11,
    "p": 6.11,
    "c": 56.0,
    "f": 24.22,
    "g": 90,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 90,
      "k": 424.0,
      "p": 5.5,
      "c": 50.4,
      "f": 21.8
    }
  },
  {
    "n": "Pret Double Berry Muffin",
    "k": 355.65,
    "p": 5.32,
    "c": 43.06,
    "f": 17.42,
    "g": 124,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 124,
      "k": 441.0,
      "p": 6.6,
      "c": 53.4,
      "f": 21.6
    }
  },
  {
    "n": "Pret Loaded Chocolate Chunk Banana Bread",
    "k": 430.77,
    "p": 5.77,
    "c": 45.62,
    "f": 24.38,
    "g": 130,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 130,
      "k": 560.0,
      "p": 7.5,
      "c": 59.3,
      "f": 31.7
    }
  },
  {
    "n": "Pret Nutty Pistachio & Almond Loaf Cake",
    "k": 464.62,
    "p": 9.46,
    "c": 26.69,
    "f": 35.0,
    "g": 130,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 130,
      "k": 604.0,
      "p": 12.3,
      "c": 34.7,
      "f": 45.5
    }
  },
  {
    "n": "Pret Gingerbread Biscuit Godfrey",
    "k": 465.12,
    "p": 4.88,
    "c": 77.21,
    "f": 14.65,
    "g": 43,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 43,
      "k": 200.0,
      "p": 2.1,
      "c": 33.2,
      "f": 6.3
    }
  },
  {
    "n": "Pret Raspberry & White Chocolate Cookie",
    "k": 457.78,
    "p": 5.0,
    "c": 62.0,
    "f": 20.67,
    "g": 90,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 90,
      "k": 412.0,
      "p": 4.5,
      "c": 55.8,
      "f": 18.6
    }
  },
  {
    "n": "Pret Triple Chocolate Cookie",
    "k": 460.0,
    "p": 6.11,
    "c": 57.56,
    "f": 22.22,
    "g": 90,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 90,
      "k": 414.0,
      "p": 5.5,
      "c": 51.8,
      "f": 20.0
    }
  },
  {
    "n": "Pret Zingy Lemon & Almond Loaf Cake",
    "k": 438.52,
    "p": 6.96,
    "c": 33.11,
    "f": 30.52,
    "g": 135,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 135,
      "k": 592.0,
      "p": 9.4,
      "c": 44.7,
      "f": 41.2
    }
  },
  {
    "n": "Pret Apple",
    "k": 53.12,
    "p": 0.38,
    "c": 11.81,
    "f": 0.12,
    "g": 160,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 160,
      "k": 85.0,
      "p": 0.6,
      "c": 18.9,
      "f": 0.2
    }
  },
  {
    "n": "Pret Banana",
    "k": 102.7,
    "p": 1.22,
    "c": 23.24,
    "f": 0.27,
    "g": 74,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 74,
      "k": 76.0,
      "p": 0.9,
      "c": 17.2,
      "f": 0.2
    }
  },
  {
    "n": "Pret Fruit Salad Pot",
    "k": 47.56,
    "p": 0.58,
    "c": 10.09,
    "f": 0.18,
    "g": 225,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 225,
      "k": 107.0,
      "p": 1.3,
      "c": 22.7,
      "f": 0.4
    }
  },
  {
    "n": "Pret Mango & Lime Fruit Pot",
    "k": 48.0,
    "p": 0.67,
    "c": 9.4,
    "f": 0.6,
    "g": 150,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 150,
      "k": 72.0,
      "p": 1.0,
      "c": 14.1,
      "f": 0.9
    }
  },
  {
    "n": "Pret Super Fruit Pot",
    "k": 51.76,
    "p": 0.82,
    "c": 10.0,
    "f": 0.59,
    "g": 170,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 170,
      "k": 88.0,
      "p": 1.4,
      "c": 17.0,
      "f": 1.0
    }
  },
  {
    "n": "Pret Kids' Cheese & Tomato Triangles",
    "k": 211.49,
    "p": 10.26,
    "c": 24.76,
    "f": 7.39,
    "g": 174.48,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 174.48,
      "k": 369.0,
      "p": 17.9,
      "c": 43.2,
      "f": 12.9
    }
  },
  {
    "n": "Pret Kids' Chicken & Cucumber Triangles",
    "k": 221.38,
    "p": 10.81,
    "c": 24.29,
    "f": 8.54,
    "g": 172.1,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 172.1,
      "k": 381.0,
      "p": 18.6,
      "c": 41.8,
      "f": 14.7
    }
  },
  {
    "n": "Pret Kids' Ham Triangles",
    "k": 244.07,
    "p": 11.78,
    "c": 34.58,
    "f": 5.93,
    "g": 118,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 118,
      "k": 288.0,
      "p": 13.9,
      "c": 40.8,
      "f": 7.0
    }
  },
  {
    "n": "Pret Kids' Humous & Cucumber Bowl",
    "k": 93.96,
    "p": 3.36,
    "c": 3.36,
    "f": 6.6,
    "g": 89.4,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 89.4,
      "k": 84.0,
      "p": 3.0,
      "c": 3.0,
      "f": 5.9
    }
  },
  {
    "n": "Pret Kids' Mango & Banana Yogurt Pot",
    "k": 102.02,
    "p": 6.16,
    "c": 9.39,
    "f": 4.34,
    "g": 99,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 99,
      "k": 101.0,
      "p": 6.1,
      "c": 9.3,
      "f": 4.3
    }
  },
  {
    "n": "Pret Kids' Pizza Toastie",
    "k": 274.64,
    "p": 12.25,
    "c": 32.1,
    "f": 10.07,
    "g": 138,
    "cat": "fastfood",
    "eat": true,
    "src": "pret-uk",
    "ref": {
      "g": 138,
      "k": 379.0,
      "p": 16.9,
      "c": 44.3,
      "f": 13.9
    }
  }
]
